# Configure for using linaro toolchain
PREFERRED_VERSION_gcc-cross = "linaro-4.8"
PREFERRED_VERSION_gcc-cross-initial = "linaro-4.8"
PREFERRED_VERSION_gcc-cross-intermediate = "linaro-4.8"
PREFERRED_VERSION_gcc-crosssdk = "linaro-4.8"
PREFERRED_VERSION_gcc-crosssdk-initial = "linaro-4.8"
PREFERRED_VERSION_gcc-crosssdk-intermediate = "linaro-4.8"
PREFERRED_VERSION_gcc-cross-canadian-${TRANSLATED_TARGET_ARCH} = "linaro-4.8"
