require linux.inc
require linux-dtb.inc

DESCRIPTION = "Linux kernel for the koelsch board"
COMPATIBLE_MACHINE = "koelsch"

PR = "r0"
PV_append = "+git${SRCREV}"

SRCREV = "4938ff7a961bcf44ef53c4a928f6cf9c4e6ddb4d"
SRC_URI = "git://git.yoctoproject.org/linux-yocto-3.4.git;protocol=git;branch=ltsi	\
	file://0001-drm-Move-drm_format_num_planes-to-drm_crtc.c.patch	\
	file://0002-drm-Add-drm_format_plane_cpp-utility-function.patch	\
	file://0003-drm-Add-drm_format_-horz-vert-_chroma_subsampling-ut.patch	\
	file://0004-drm-Add-sanity-checks-to-framebuffer-creation.patch	\
	file://0005-drm-Fix-EDID-color-format-parsing.patch	\
	file://0006-drm-Parse-color-format-information-in-CEA-blocks.patch	\
	file://0007-drm-add-the-VIC-number-to-the-CEA-EDID-modes.patch	\
	file://0008-drm-add-DRM_MODE_FLAG_DBLCLK-to-CEA-modes-requiring-.patch	\
	file://0009-drm-edid-Document-drm_mode_find_dmt.patch	\
	file://0010-drm-edid-Rewrite-drm_mode_find_dmt-search-loop.patch	\
	file://0011-drm-edid-Allow-drm_mode_find_dmt-to-hunt-for-reduced.patch	\
	file://0012-drm-edid-Remove-a-misleading-comment.patch	\
	file://0013-drm-edid-s-drm_gtf_modes_for_range-drm_dmt_modes_for.patch	\
	file://0014-drm-edid-Add-the-reduced-blanking-DMT-modes-to-the-D.patch	\
	file://0015-drm-edid-Fix-some-comment-typos-in-the-DMT-mode-list.patch	\
	file://0016-drm-edid-Do-drm_dmt_modes_for_range-for-all-range-de.patch	\
	file://0017-drm-edid-Give-the-est3-mode-struct-a-real-name.patch	\
	file://0018-drm-edid-Add-extra_modes.patch	\
	file://0019-drm-edid-Generate-modes-from-extra_modes-for-range-d.patch	\
	file://0020-drm-edid-add-missing-NULL-checks.patch	\
	file://0021-drm-replace-open-coded-ARRAY_SIZE-with-macro.patch	\
	file://0022-drm-edid-Add-a-workaround-for-1366x768-HD-panel.patch	\
	file://0023-drm-Unify-and-fix-idr-error-handling.patch	\
	file://0024-drm-edid-Try-harder-to-fix-up-base-EDID-blocks.patch	\
	file://0025-drm-Store-vendor-IDs-directly-in-the-EDID-quirk-stru.patch	\
	file://0026-drm-edid-fix-collision-between-two-patches-breaking-.patch	\
	file://0027-drm-kms-reduce-some-messages-to-debug-level-v2.patch	\
	file://0028-drm-add-drm_property_change_is_valid.patch	\
	file://0029-drm-WARN-when-drm_connector_attach_property-fails.patch	\
	file://0030-drm-create-struct-drm_object_properties-and-use-it.patch	\
	file://0031-drm-add-generic-ioctls-to-get-set-properties-on-any-.patch	\
	file://0032-drm-make-the-connector-properties-code-use-the-objec.patch	\
	file://0033-drm-add-count-to-struct-drm_object_properties.patch	\
	file://0034-drm-add-CRTC-properties.patch	\
	file://0035-drm-Don-t-initialize-local-ret-variable-when-not-nee.patch	\
	file://0036-drm-Miscellaneous-typo-fixes-and-documentation-updat.patch	\
	file://0037-drm-Constify-drm_mode_config_funcs-pointer.patch	\
	file://0038-drm-Make-the-CRTC-gamma_set-operation-optional.patch	\
	file://0039-drm-add-bitmask-property-type.patch	\
	file://0040-drm-add-plane-properties.patch	\
	file://0041-drm-Constify-params-to-format_check-and-framebuffer_.patch	\
	file://0042-drm-Use-stdint-types-for-consistency.patch	\
	file://0043-drm-edid-quirks-ViewSonic-VA2026w.patch	\
	file://0044-drm-edid-Make-the-header-fixup-threshold-tunable.patch	\
	file://0045-drm-increase-DRM_OBJECT_MAX_PROPERTY-to-24.patch	\
	file://0046-drm-edid-Don-t-add-inferred-modes-with-higher-resolu.patch	\
	file://0047-drm-fb-helper-delay-hotplug-handling-when-partially-.patch	\
	file://0048-drm-fb-helper-don-t-call-drm_crtc_helper_set_config.patch	\
	file://0049-drm-remove-the-list_head-from-drm_mode_set.patch	\
	file://0050-drm-edid-Fix-potential-memory-leak-in-edid_load.patch	\
	file://0051-drm-fb-helper-don-t-clobber-output-routing-in-setup_.patch	\
	file://0052-drm-Remove-two-unused-fields-from-struct-drm_display.patch	\
	file://0053-Documentation-DocBook-DRM-framework-documentation.patch	\
	file://0054-drm-remove-the-raw_edid-field-from-struct-drm_displa.patch	\
	file://0055-drm-Initialize-object-type-when-using-DRM_MODE-macro.patch	\
	file://0056-drm-Add-misssing-static-storage-class-specifier-in-d.patch	\
	file://0057-drm-Add-EDID_QUIRK_FORCE_REDUCED_BLANKING-for-ASUS-V.patch	\
	file://0058-drm-fb-helper-don-t-call-drm_helper_connector_dpms-d.patch	\
	file://0059-drm-consistently-name-interlaced-modes.patch	\
	file://0060-drm-edid-Add-some-bounds-checking.patch	\
	file://0061-drm-edid-Add-bounds-checking-to-HDMI-VSDB-parsing.patch	\
	file://0062-drm-edid-Refactor-HDMI-VSDB-detection.patch	\
	file://0063-drm-edid-add-support-for-E-DDC.patch	\
	file://0064-drm-edid-limit-printk-when-facing-bad-edid.patch	\
	file://0065-DRM-Add-DRM-GEM-CMA-helper.patch	\
	file://0066-drm-Add-NV24-and-NV42-pixel-formats.patch	\
	file://0067-drm-refcnt-drm_framebuffer-v4.1.patch	\
	file://0068-drm-support-for-rotated-scanout.patch	\
	file://0069-drm-Export-drm_probe_ddc.patch	\
	file://0070-UAPI-Refer-to-the-DRM-UAPI-headers-with-.-and-from-c.patch	\
	file://0071-drm-rename-drm_dp_i2c_helper.c-to-drm_dp_helper.c.patch	\
	file://0072-drm-dp-helper-extract-drm_dp_channel_eq_ok.patch	\
	file://0073-drm-Be-more-paranoid-with-integer-overflows.patch	\
	file://0074-drm-Constify-some-function-arguments.patch	\
	file://0075-drm-Ignore-blob-propertys-in-drm_property_change_is_.patch	\
	file://0076-drm-add-helper-to-sort-panels-to-the-head-of-the-con.patch	\
	file://0077-drm-fb_helper-Fix-checkpatch-errors.patch	\
	file://0078-drm-fb_helper-Convert-printk-to-pr_-and-dev_.patch	\
	file://0079-drm-drm_fb_helper-Remove-unnecessary-braces.patch	\
	file://0080-drm-get-cea-video-id-code-for-a-given-display-mode.patch	\
	file://0081-drm-fix-documentation-for-drm_crtc_set_mode.patch	\
	file://0082-drm-Reject-addfb2-with-undefined-flag-bits-set.patch	\
	file://0083-drm-crtc-Remove-redundant-NULL-check-before-kfree.patch	\
	file://0084-drm-crtc-Fix-potential-NULL-pointer-dereference.patch	\
	file://0085-drm-fb_helper-Fix-potential-NULL-pointer-dereference.patch	\
	file://0086-drm-add-drm_send_vblank_event-helper-v5.patch	\
	file://0087-drm-extract-drm_kms_helper_hotplug_event.patch	\
	file://0088-drm-handle-HPD-and-polled-connectors-separately.patch	\
	file://0089-drm-run-the-hpd-irq-event-code-directly.patch	\
	file://0090-drm-properly-init-reset-connector-status.patch	\
	file://0091-drm-don-t-start-the-poll-engine-in-probe_single_conn.patch	\
	file://0092-drm-don-t-poll-forced-connectors.patch	\
	file://0093-drm-use-memchr_inv.patch	\
	file://0094-drm-don-t-unnecessarily-enable-the-polling-work.patch	\
	file://0095-drm-edid-tune-down-debug-message-in-parse_hdmi_vsdb.patch	\
	file://0096-drm-doc-Helpers-are-not-a-Midlayer.patch	\
	file://0097-drm-doc-integrate-crtc-helper-api-into-docbook.patch	\
	file://0098-drm-doc-integrate-fb-helper-reference-into-docs.patch	\
	file://0099-drm-doc-add-new-dp-helpers-into-drm-DocBook.patch	\
	file://0100-drm-add-drm_mode_cea_vic.patch	\
	file://0101-drm-remove-legacy-drm_connector_property-fxns.patch	\
	file://0102-drm-edid-Update-range-descriptor-struct-for-EDID-1.4.patch	\
	file://0103-drm-edid-Add-packed-attribute-to-new-gtf2-and-cvt-st.patch	\
	file://0104-DRM-Add-DRM-KMS-FB-CMA-helper.patch	\
	file://0105-drm-Make-the-.mode_fixup-operations-mode-argument-a-.patch	\
	file://0106-drm-Constify-gem_vm_ops-pointer.patch	\
	file://0107-i2c-add-Renesas-R-Car-I2C-driver.patch	\
	file://0108-i2c-rcar-used-devm_request_and_ioremap-instead-of-de.patch	\
	file://0109-i2c-rcar-fix-section-mismatch.patch	\
	file://0110-ARM-shmobile-r8a7779-add-I2C-driver-support.patch	\
	file://0111-dma-buf-mmap-support.patch	\
	file://0112-common-dma-mapping-introduce-dma_get_sgtable-functio.patch	\
	file://0113-dma-buf-add-vmap-interface.patch	\
	file://0114-ARM-dma-mapping-add-support-for-dma_get_sgtable.patch	\
	file://0115-devres-Add-devres_release.patch	\
	file://0116-ARM-7376-1-clkdev-Implement-managed-clk_get.patch	\
	file://0117-ARM-7534-1-clk-Make-the-managed-clk-functions-generi.patch	\
	file://0118-ARM-7537-1-clk-Fix-release-in-devm_clk_put.patch	\
	file://0119-drm-GEM-CMA-Split-object-creation-into-object-alloc-.patch	\
	file://0120-drm-GEM-CMA-Add-DRM-PRIME-support.patch	\
	file://0121-drm-Renesas-R-Car-Display-Unit-DRM-driver.patch	\
	file://0122-drm-rcar-du-Use-drm_encoder_cleanup-directly-as-.des.patch	\
	file://0123-drm-rcar-du-Enable-alpha-blending-support.patch	\
	file://0124-drm-rcar-du-Don-t-re-reserve-hardware-plane-at-each-.patch	\
	file://0125-drm-rcar-du-Fix-planes-allocation-for-multiplanar-fo.patch	\
	file://0126-drm-rcar-du-Add-DRM-PRIME-support.patch	\
	file://0127-drm-rcar-du-Fix-race-condition-between-page-flip-req.patch	\
	file://0128-drm-rcar-du-Add-configurable-z-order-support-for-pla.patch	\
	file://0129-drm-rcar-du-Support-configurable-color-keying-for-pl.patch	\
	file://0130-drm-rcar-du-Update-plane-format-after-releasing-hard.patch	\
	file://0131-drm-rcar-du-Fix-register-access-for-global-registers.patch	\
	file://0132-drm-rcar-du-Fix-plane-index-wrap-around-for-multi-pl.patch	\
	file://0133-drm-rcar-du-Enable-the-DE-signal.patch	\
	file://0134-drm-rcar-du-Split-hardware-and-KMS-planes.patch	\
	file://0135-drm-rcar-du-Add-support-for-the-second-CRTC.patch	\
	file://0136-drm-rcar-du-Name-the-encoder-platform-data-union.patch	\
	file://0137-drm-rcar-du-Fix-crash-when-disabling-an-already-disa.patch	\
	file://0138-drm-rcar-du-Prepare-unprepare-clock.patch	\
	file://0139-drm-rcar-du-Centralize-DU-device-core-resource-manag.patch	\
	file://0140-drm-rcar-du-Reorganize-CRTC-start-stop-and-power-man.patch	\
	file://0141-drm-rcar-du-Create-common-encoder-and-connector-stru.patch	\
	file://0142-drm-rcar-du-Add-support-for-cloned-mode-on-DU1.patch	\
	file://0143-drm-rcar-du-Add-FBDEV-emulation-support.patch	\
	file://0145-ARM-local-timers-Add-A15-architected-timer-support.patch	\
	file://0146-ARM-architected-timers-Add-A15-specific-sched_clock-.patch	\
	file://0147-ARM-architected-timers-add-DT-support.patch	\
	file://0148-ARM-architected-timers-add-support-for-UP-timer.patch	\
	file://0149-ARM-architected-timers-remove-support-for-non-DT-pla.patch	\
	file://0150-ARM-7451-1-arch-timer-implement-read_current_timer-a.patch	\
	file://0151-ARM-7452-1-delay-allow-timer-based-delay-implementat.patch	\
	file://0152-ARM-7444-1-kernel-add-arch-timer-C3STOP-feature.patch	\
	file://0153-ARM-7523-1-arch_timers-enable-the-use-of-the-virtual.patch	\
	file://0154-ARM-7522-1-arch_timers-register-a-time-cycle-counter.patch	\
	file://0155-ARM-7538-1-delay-add-registration-mechanism-for-dela.patch	\
	file://0156-ARM-7461-1-topology-Add-arch_scale_freq_power-functi.patch	\
	file://0157-ARM-7462-1-topology-factorize-the-update-of-sibling-.patch	\
	file://0158-ARM-7463-1-topology-Update-cpu_power-according-to-DT.patch	\
	file://0159-ARM-kernel-update-topology-to-use-new-MPIDR-macros.patch	\
	file://0160-ARM-kernel-enhance-MPIDR-macro-definitions.patch	\
	file://0161-ARM-shmobile-Register-ARM-architected-timer.patch	\
	file://0162-ARM-mm-implement-LoUIS-API-for-cache-maintenance-ops.patch	\
	file://0163-ARM-kernel-update-__cpu_disable-to-use-cache-LoUIS-m.patch	\
	file://0164-ARM-kernel-update-cpu_suspend-code-to-use-cache-LoUI.patch	\
	file://0165-ARM-mm-rename-jump-labels-in-v7_flush_dcache_all-fun.patch	\
	file://0166-ARM-7542-1-mm-fix-cache-LoUIS-API-for-xscale-and-fer.patch	\
	file://0167-ARM-kernel-smp_setup_processor_id-updates.patch	\
	file://0168-ARM-kernel-add-device-tree-init-map-function.patch	\
	file://0169-ARM-kernel-add-cpu-logical-map-DT-init-in-setup_arch.patch	\
	file://0170-ARM-kernel-add-logical-mappings-look-up.patch	\
	file://0171-ARM-SoC-add-per-platform-SMP-operations.patch	\
	file://0172-ARM-SoC-convert-shmobile-SMP-to-SMP-operations.patch	\
	file://0173-irqchip-add-basic-infrastructure.patch	\
	file://0174-irqdomain-augment-add_simple-to-allocate-descs.patch	\
	file://0175-irqdomain-stop-screaming-about-preallocated-irqdescs.patch	\
	file://0176-irqchip-Renesas-INTC-External-IRQ-pin-driver.patch	\
	file://0177-irqchip-intc-irqpin-Cache-mapped-IRQ.patch	\
	file://0178-ARM-shmobile-irq_pin-for-static-IRQ-pin-assignment.patch	\
	file://0179-ARM-shmobile-INTC-External-IRQ-pin-driver-on-r8a7779.patch	\
	file://0180-irqchip-intc-irqpin-Whitespace-fixes.patch	\
	file://0181-irqchip-intc-irqpin-Add-force-comments.patch	\
	file://0182-irqchip-intc-irqpin-Make-use-of-devm-functions.patch	\
	file://0183-irqchip-intc-irqpin-GPL-header-for-platform-data.patch	\
	file://0184-irqchip-Renesas-IRQC-driver.patch	\
	file://0185-ARM-shmobile-Make-r8a7779-INTC-irqpin-platform-data-.patch	\
	file://0186-irqchip-intc-irqpin-Initial-DT-support.patch	\
	file://0187-irqchip-irqc-Add-DT-support.patch	\
	file://0188-ARM-gic-use-a-private-mapping-for-CPU-target-interfa.patch	\
	file://0189-ARM-GIC-fix-GIC-cpumask-initialization.patch	\
	file://0190-ARM-GIC-remove-assembly-ifdefs-from-gic.h.patch	\
	file://0191-ARM-OMAP-use-SGI0-to-wake-secondary-CPUs.patch	\
	file://0192-ARM-7498-1-mach-shmobile-Use-SGI0-to-wake-secondary-.patch	\
	file://0193-ARM-Realview-use-SGI0-to-wake-secondary-CPUs.patch	\
	file://0194-ARM-7485-1-EXYNOS-use-SGI0-to-wake-secondary-CPUs.patch	\
	file://0195-ARM-MSM-use-SGI0-to-wake-secondary-CPUs.patch	\
	file://0196-ARM-mach-ux500-use-SGI0-to-wake-up-the-other-core.patch	\
	file://0197-ARM-7536-1-smp-Formalize-an-IPI-for-wakeup.patch	\
	file://0198-ARM-7571-1-SMP-add-function-arch_send_wakeup_ipi_mas.patch	\
	file://0199-ARM-GIC-remove-direct-use-of-gic_raise_softirq.patch	\
	file://0200-arm-add-set_handle_irq-to-register-the-parent-IRQ-co.patch	\
	file://0201-ARM-GIC-set-handle_arch_irq-in-GIC-initialization.patch	\
	file://0202-ARM-remove-mach-.handle_irq-for-GIC-users.patch	\
	file://0203-irqchip-Move-ARM-GIC-to-drivers-irqchip.patch	\
	file://0204-ARM-use-common-irqchip_init-for-GIC-init.patch	\
	file://0205-irqchip-Move-ARM-gic.h-to-include-linux-irqchip-arm-.patch	\
	file://0206-irqchip-fix-typo-when-moving-gic_raise_softirq.patch	\
	file://0207-ARM-shmobile-defconfig-Begin-common-shmobile-defconf.patch	\
	file://0208-ARM-shmobile-prune-defconfig.patch	\
	file://0209-ARM-shmobile-make-defconfig-canonical.patch	\
	file://0210-ARM-shmobile-Add-kzm9d-to-consolidated-defconfig.patch	\
	file://0211-ARM-shmobile-Add-mackerel-to-consolidated-defconfig.patch	\
	file://0212-ARM-shmobile-Add-lager-to-consolidated-defconfig.patch	\
	file://0213-ARM-shmobile-Initial-r8a7790-SoC-support.patch	\
	file://0214-ARM-shmobile-r8a7790-SCIF-support.patch	\
	file://0215-ARM-shmobile-r8a7790-IRQC-support.patch	\
	file://0216-ARM-shmobile-r8a7790-PFC-support.patch	\
	file://0217-ARM-shmobile-r8a7790-SoC-64-bit-DT-support.patch	\
	file://0218-ARM-shmobile-Add-second-I-O-range-for-r8a7790-PFC.patch	\
	file://0219-ARM-shmobile-force-enable-of-r8a7790-arch-timer.patch	\
	file://0220-Documentation-pinctrl-add-missing-spi0_0-grp-in-exam.patch	\
	file://0221-pinctrl-mark-const-init-data-with-__initconst-instea.patch	\
	file://0222-pinctrl-implement-pinctrl-deferred-probing.patch	\
	file://0223-pinctrl-fix-a-minor-harmless-typo.patch	\
	file://0224-Documentation-pinctrl.txt-Fix-some-misspelled-macros.patch	\
	file://0225-trivial-pinctrl-core-remove-extraneous-code-lines.patch	\
	file://0226-pinctrl-document-semantics-vs-GPIO.patch	\
	file://0227-pinctrl-Fix-potential-memory-leak-in-pinctrl_registe.patch	\
	file://0228-pinctrl-fix-missing-unlock-on-error-in-pinctrl_group.patch	\
	file://0229-pinctrl-fix-comment-mistake.patch	\
	file://0230-pinctrl-skip-deferral-of-hogs.patch	\
	file://0231-pinctrl-core-get-devname-from-pinctrl_dev.patch	\
	file://0232-drivers-pinctrl-grab-default-handles-from-device-cor.patch	\
	file://0233-gpio-add-flags-to-export-GPIOs-when-requesting.patch	\
	file://0234-gpio-Move-DT-support-code-into-drivers-gpio.patch	\
	file://0235-gpiolib-Implement-devm_gpio_request_one.patch	\
	file://0236-pinctrl-allow-pctldevs-to-decode-pin-config-in-debug.patch	\
	file://0237-gpio-Adjust-of_xlate-API-to-support-multiple-GPIO-ch.patch	\
	file://0238-gpiolib-quiet-gpiochip_add-boot-message-noise.patch	\
	file://0239-gpiolib-Remove-const-from-data-argument-of-gpiochip_.patch	\
	file://0240-gpio-of-fix-a-typo-of-comment-message.patch	\
	file://0241-gpio-propagate-of_parse_phandle_with_args-errors.patch	\
	file://0242-gpiolib-Defer-failed-gpio-requests-by-default.patch	\
	file://0243-gpio-of_get_named_gpio_flags-return-EPROBE_DEFER-if-.patch	\
	file://0244-gpio-Fix-debug-message-in-of_get_named_gpio_flags.patch	\
	file://0245-gpiolib-Use-seq_file-s-iterator-interface.patch	\
	file://0246-gpio-Document-device_node-s-det_debounce.patch	\
	file://0247-gpiolib-Refactor-gpio_export.patch	\
	file://0248-gpiolib-add-gpio-get-direction-callback-support.patch	\
	file://0249-gpiolib-unlock-on-error-in-gpio_export.patch	\
	file://0250-gpiolib-provide-provision-to-register-pin-ranges.patch	\
	file://0251-gpiolib-fix-up-function-prototypes-etc.patch	\
	file://0252-gpiolib-of-staticize-the-pin-range-calls.patch	\
	file://0253-gpiolib-remove-duplicate-pin-range-code.patch	\
	file://0254-gpiolib-call-pin-removal-in-chip-removal-function.patch	\
	file://0255-gpiolib-separation-of-pin-concerns.patch	\
	file://0256-gpiolib-iron-out-include-ladder-mistakes.patch	\
	file://0257-gpiolib-let-gpiochip_add_pin_range-specify-offset.patch	\
	file://0258-gpiolib-rename-find_pinctrl_.patch	\
	file://0259-gpiolib-return-any-error-code-from-range-creation.patch	\
	file://0260-gpiolib-rename-pin-range-arguments.patch	\
	file://0261-gpiolib-Fix-use-after-free-in-gpiochip_add_pin_range.patch	\
	file://0262-gpio-use-pinctrl-device-name-for-add-range.patch	\
	file://0263-gpio-fix-warning-of-struct-gpio_chip-declaration.patch	\
	file://0264-gpio-devm_gpio_-support-should-not-depend-on-GPIOLIB.patch	\
	file://0265-gpiolib-remove-gpiochip_reserve.patch	\
	file://0266-gpiolib-add-missing-braces-in-gpio_direction_show.patch	\
	file://0267-gpiolib-link-all-gpio_chips-using-a-list.patch	\
	file://0268-gpiolib-use-gpio_chips-list-in-gpiolib_sysfs_init.patch	\
	file://0269-pinctrl-generic-dump-pin-configuration.patch	\
	file://0270-Revert-pinctrl-remove-pinctrl_remove_gpio_range.patch	\
	file://0271-pinctrl-Declare-operation-structures-as-const.patch	\
	file://0272-pinctrl-generic-Fix-compilation-error.patch	\
	file://0273-sh-pfc-Split-out-gpio-chip-support.patch	\
	file://0274-sh-pfc-Make-gpio-chip-support-optional-where-possibl.patch	\
	file://0275-sh-pfc-Kill-off-unused-pinmux-bias-flags.patch	\
	file://0276-sh-pfc-Verify-pin-type-encoding-size-at-build-time.patch	\
	file://0277-sh-pfc-Shuffle-PFC-support-core.patch	\
	file://0278-sh-pfc-Dumb-GPIO-stringification.patch	\
	file://0279-sh-pfc-Rudimentary-pinctrl-backed-GPIO-support.patch	\
	file://0280-sh-pfc-pinctrl-legacy-function-support.patch	\
	file://0281-sh-pfc-Make-pr_fmt-consistent-across-pfc-drivers.patch	\
	file://0282-sh-pfc-Export-pinctrl-binding-init-symbol.patch	\
	file://0283-sh-pfc-Ignore-pinmux-GPIOs-with-invalid-enum-IDs.patch	\
	file://0284-sh-pfc-pinctrl-legacy-group-support.patch	\
	file://0285-sh-pfc-Prefer-DRV_NAME-over-KBUILD_MODNAME.patch	\
	file://0286-sh-pfc-pin-config-get-set-support.patch	\
	file://0287-sh-pfc-Build-fix-for-pinctrl_remove_gpio_range-chang.patch	\
	file://0288-sh-pfc-Fix-up-init-ordering-mess.patch	\
	file://0289-sh-pfc-Release-spinlock-in-sh_pfc_gpio_request_enabl.patch	\
	file://0290-sh-pfc-Fix-up-GPIO-mux-type-reconfig-case.patch	\
	file://0291-sh-pfc-Error-out-on-pinctrl-init-resolution-failure.patch	\
	file://0292-ARM-shmobile-move-custom-gpio-functions-to-sh-gpio.h.patch	\
	file://0293-Drivers-misc-remove-__dev-attributes.patch	\
	file://0294-sh-sh7723-Rename-GPIO_FN_SIUOSPD-to-GPIO_FN_SIUAOSPD.patch	\
	file://0295-sh-sh7757-Fix-GPIO_FN_ET0_MDIO-and-GPIO_FN_ET1_MDIO-.patch	\
	file://0296-sh-sh7786-Fix-port-E-G-and-J-GPIOs.patch	\
	file://0297-sh-sh7786-Fix-last-GPIO-index.patch	\
	file://0298-sh-shx3-Fix-last-GPIO-index.patch	\
	file://0299-sh-pfc-Split-platform-data-from-the-sh_pfc-structure.patch	\
	file://0300-sh-pfc-Move-private-definitions-and-declarations-to-.patch	\
	file://0301-sh-pfc-Merge-PFC-core-and-pinctrl.patch	\
	file://0302-sh-pfc-Merge-PFC-core-and-gpio.patch	\
	file://0303-sh-pfc-Move-platform-device-and-driver-to-the-core.patch	\
	file://0304-sh-pfc-Use-devm_kzalloc.patch	\
	file://0305-sh-pfc-Use-devm_ioremap_nocache.patch	\
	file://0306-sh-pfc-Let-the-compiler-decide-whether-to-inline-fun.patch	\
	file://0307-sh-pfc-Remove-check-for-impossible-error-condition.patch	\
	file://0308-sh-pfc-Sort-headers-alphabetically.patch	\
	file://0309-sh-pfc-Use-sh_pfc_-namespace-prefix-through-the-whol.patch	\
	file://0310-sh-pfc-Split-platform-device-and-platform-driver-reg.patch	\
	file://0311-sh-pfc-Support-passing-resources-through-platform-de.patch	\
	file://0312-ARM-shmobile-Select-PINCTRL.patch	\
	file://0313-ARM-shmobile-r8a7740-Register-PFC-platform-device.patch	\
	file://0314-ARM-shmobile-r8a7779-Register-PFC-platform-device.patch	\
	file://0315-ARM-shmobile-sh7372-Register-PFC-platform-device.patch	\
	file://0316-ARM-shmobile-sh73a0-Register-PFC-platform-device.patch	\
	file://0317-ARM-shmobile-r8a7740-Add-pin-control-resources.patch	\
	file://0318-ARM-shmobile-sh7372-Add-pin-control-resources.patch	\
	file://0319-ARM-shmobile-sh73a0-Add-pin-control-resources.patch	\
	file://0320-sh-Add-PFC-platform-device-registration-helper-funct.patch	\
	file://0321-sh-sh7203-Register-PFC-platform-device.patch	\
	file://0322-sh-sh7720-Register-PFC-platform-device.patch	\
	file://0323-sh-sh7722-Register-PFC-platform-device.patch	\
	file://0324-sh-sh7723-Register-PFC-platform-device.patch	\
	file://0325-sh-sh7724-Register-PFC-platform-device.patch	\
	file://0326-sh-sh7757-Register-PFC-platform-device.patch	\
	file://0327-sh-sh7785-Register-PFC-platform-device.patch	\
	file://0328-sh-sh7786-Register-PFC-platform-device.patch	\
	file://0329-sh-shx3-Register-PFC-platform-device.patch	\
	file://0330-sh-pfc-Remove-platform-device-registration.patch	\
	file://0331-sh-pfc-Remove-unused-resource-and-num_resources-plat.patch	\
	file://0332-sh-pfc-Move-driver-from-drivers-sh-to-drivers-pinctr.patch	\
	file://0333-sh-pfc-Support-pinmux-info-in-driver-data-instead-of.patch	\
	file://0334-sh-pfc-Add-r8a7740-pinmux-support.patch	\
	file://0335-ARM-shmobile-r8a7779-PFC-rename-PENCx-USB_PENCx.patch	\
	file://0336-sh-pfc-Add-r8a7779-pinmux-support.patch	\
	file://0337-sh-pfc-Add-sh7372-pinmux-support.patch	\
	file://0338-sh-pfc-Add-sh73a0-pinmux-support.patch	\
	file://0339-sh-pfc-Add-sh7203-pinmux-support.patch	\
	file://0340-sh-pfc-Add-sh7264-pinmux-support.patch	\
	file://0341-sh-pfc-Add-sh7269-pinmux-support.patch	\
	file://0342-sh-pfc-Add-sh7720-pinmux-support.patch	\
	file://0343-sh-pfc-Add-sh7722-pinmux-support.patch	\
	file://0344-sh-pfc-Add-sh7723-pinmux-support.patch	\
	file://0345-sh-pfc-Add-sh7724-pinmux-support.patch	\
	file://0346-sh-pfc-Add-sh7734-pinmux-support.patch	\
	file://0347-sh-pfc-Add-sh7757-pinmux-support.patch	\
	file://0348-sh-pfc-Add-sh7785-pinmux-support.patch	\
	file://0349-sh-pfc-Add-sh7786-pinmux-support.patch	\
	file://0350-sh-pfc-Add-shx3-pinmux-support.patch	\
	file://0351-ARM-shmobile-Remove-SH7367-support.patch	\
	file://0352-ARM-shmobile-Remove-SH7377-support.patch	\
	file://0353-ARM-shmobile-r8a7740-Use-driver-provided-pinmux-info.patch	\
	file://0354-ARM-shmobile-r8a7779-Use-driver-provided-pinmux-info.patch	\
	file://0355-ARM-shmobile-sh7372-Use-driver-provided-pinmux-info.patch	\
	file://0356-ARM-shmobile-sh73a0-Use-driver-provided-pinmux-info.patch	\
	file://0357-sh-sh7203-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0358-sh-sh7720-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0359-sh-sh7722-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0360-sh-sh7723-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0361-sh-sh7724-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0362-sh-sh7757-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0363-sh-sh7785-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0364-sh-sh7786-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0365-sh-shx3-pinmux-Use-driver-provided-pinmux-info.patch	\
	file://0366-sh-Remove-unused-sh_pfc_register_info-function.patch	\
	file://0367-sh-pfc-Remove-pinmux_info-definition.patch	\
	file://0368-sh-pfc-Move-sh_pfc.h-from-include-linux-to-driver-di.patch	\
	file://0369-sh-pfc-Declare-operation-structures-as-const.patch	\
	file://0370-sh-pfc-Don-t-define-the-per-device-pinctrl-struct-in.patch	\
	file://0371-sh-pfc-Fix-a-typo-and-simplify-a-definition-on-sh73a.patch	\
	file://0372-sh-pfc-Drop-the-sh_pfc_pinctrl-spinlock.patch	\
	file://0373-sh-pfc-Don-t-take-the-sh_pfc-spinlock-in-sh_pfc_map_.patch	\
	file://0374-sh-pfc-Use-GPIO_FN-instead-of-PINMUX_GPIO-where-poss.patch	\
	file://0375-sh-pfc-Replace-first_gpio-and-last_gpio-with-nr_gpio.patch	\
	file://0376-sh-pfc-Replace-SoC-info-data-and-mark-ranges-with-a-.patch	\
	file://0377-sh-pfc-Remove-unused-sh_pfc_soc_info-reserved_id-fie.patch	\
	file://0378-sh-pfc-Initialize-pinmux_gpio-flags-statically.patch	\
	file://0379-sh-pfc-Make-struct-pinmux_gpio-enum_id-field-const.patch	\
	file://0380-sh-pfc-Shrink-the-pinctrl-GPIO-range-to-include-real.patch	\
	file://0381-sh-pfc-Don-t-needlessly-check-GPIO-type-in-sh_gpio_f.patch	\
	file://0382-sh-pfc-Split-pins-and-functions-definition-tables.patch	\
	file://0383-sh-pfc-Split-pins-and-functions-into-separate-gpio_c.patch	\
	file://0384-sh-pfc-Rename-struct-pinmux_pin-to-struct-sh_pfc_pin.patch	\
	file://0385-sh-pfc-Look-up-IRQ-table-entries-by-GPIO-number.patch	\
	file://0386-sh-pfc-Share-the-PORT_10_REV-PORT_32-and-PORT_32_REV.patch	\
	file://0387-sh-pfc-Use-pinmux-identifiers-in-the-pin-muxing-API.patch	\
	file://0388-sh-pfc-Simplify-the-sh_pfc_gpio_is_pin-logic.patch	\
	file://0389-sh-pfc-Add-function-to-retrieve-a-pin-instance-from-.patch	\
	file://0390-sh-pfc-Replace-pinctrl_add_gpio_range-with-gpiochip_.patch	\
	file://0391-sh-pfc-Add-support-for-sparse-pin-numbers.patch	\
	file://0392-ARM-shmobile-ag5evm-Use-gpio_request_one.patch	\
	file://0393-ARM-shmobile-kota2-Use-gpio_request_one.patch	\
	file://0394-ARM-shmobile-kzm9g-Use-gpio_request_one.patch	\
	file://0395-ARM-shmobile-sh73a0-Support-sparse-GPIO-numbers.patch	\
	file://0396-ARM-shmobile-ap4evb-Use-gpio_request_one.patch	\
	file://0397-ARM-shmobile-use-common-extra-gpio-functions-on-ap4e.patch	\
	file://0398-ARM-shmobile-ap4-evb-Replace-GPIO_PORTx-enum-with-GP.patch	\
	file://0399-ARM-shmobile-armadillo800eva-Use-gpio_request_one.patch	\
	file://0400-ARM-shmobile-armadillo800eva-Use-gpio_set_value-to-s.patch	\
	file://0401-ARM-shmobile-armadillo-Replace-GPIO_PORTx-enum-with-.patch	\
	file://0402-ARM-shmobile-bonito-Use-gpio_request_one.patch	\
	file://0403-ARM-shmobile-bonito-Replace-GPIO_PORTx-enum-with-GPI.patch	\
	file://0404-ARM-shmobile-mackerel-Use-gpio_request_one.patch	\
	file://0405-ARM-shmobile-use-common-extra-gpio-functions-on-Mack.patch	\
	file://0406-ARM-shmobile-mackerel-Replace-GPIO_PORTx-enum-with-G.patch	\
	file://0407-sh-pfc-Expose-real-groups-and-functions-in-pinctrl-p.patch	\
	file://0408-sh-pfc-Fix-return-value-check-in-sh_pfc_register_pin.patch	\
	file://0409-sh-pfc-Move-GPIO-registers-access-functions-to-gpio..patch	\
	file://0410-sh-pfc-Don-t-map-data-registers-individually.patch	\
	file://0411-sh-pfc-Drop-unused-support-for-1-1-physical-to-virtu.patch	\
	file://0412-sh-pfc-Don-t-modify-pinmux_data_reg-SoC-data.patch	\
	file://0413-sh-pfc-Don-t-modify-sh_pfc_pin-SoC-data.patch	\
	file://0414-sh-pfc-Remove-configuration-dry-run-and-free.patch	\
	file://0415-sh-pfc-Constify-all-SoC-data.patch	\
	file://0416-sh-pfc-Use-proper-error-codes.patch	\
	file://0417-sh-pfc-Implement-generic-pinconf-support.patch	\
	file://0418-sh-pfc-Merge-sh_pfc_reconfig_pin-into-sh_pfc_gpio_se.patch	\
	file://0419-sh-pfc-Clean-up-pin-configuration-type-handling.patch	\
	file://0420-sh-pfc-Convert-message-printing-from-pr_-to-dev_.patch	\
	file://0421-sh-pfc-Return-an-error-if-a-pin-doesn-t-support-the-.patch	\
	file://0422-sh-pfc-r8a7779-Add-DU-pin-groups-and-functions.patch	\
	file://0423-sh-pfc-r8a7779-Add-SDHI-and-MMCIF-pin-groups-and-fun.patch	\
	file://0424-sh-pfc-r8a7779-Add-SCIF-pin-groups-and-functions.patch	\
	file://0425-sh-pfc-r8a7779-Add-HSPI-pin-groups-and-functions.patch	\
	file://0426-sh-pfc-r8a7779-Add-USB0-and-USB1-PENC-pinmux-support.patch	\
	file://0427-sh-pfc-r8a7779-Add-USB-pin-groups-and-functions.patch	\
	file://0428-sh-pfc-r8a7779-Add-LBSC-pin-groups-and-functions.patch	\
	file://0429-sh-pfc-r8a7779-Add-INTC-pin-groups-and-functions.patch	\
	file://0430-ARM-shmobile-marzen-Register-pinctrl-mappings-for-SD.patch	\
	file://0431-ARM-shmobile-marzen-Register-pinctrl-mappings-for-SC.patch	\
	file://0432-ARM-shmobile-marzen-Register-pinctrl-mappings-for-LB.patch	\
	file://0433-ARM-shmobile-marzen-Register-pinctrl-mappings-for-IN.patch	\
	file://0434-sh-pfc-r8a7779-Remove-DU1_DOTCLKOUT1-GPIO.patch	\
	file://0435-sh-pfc-r8a7779-Remove-SDHI-and-MMCIF-function-GPIOS.patch	\
	file://0436-sh-pfc-r8a7779-Remove-SCIF-function-GPIOS.patch	\
	file://0437-sh-pfc-r8a7779-Remove-HSPI-function-GPIOS.patch	\
	file://0438-sh-pfc-r8a7779-Remove-USB-function-GPIOS.patch	\
	file://0439-sh-pfc-r8a7779-Remove-LBSC-function-GPIOS.patch	\
	file://0440-sh-pfc-r8a7779-Remove-INTC-function-GPIOS.patch	\
	file://0441-ARM-shmobile-r8a7779-Remove-DU-function-GPIOs.patch	\
	file://0442-ARM-shmobile-r8a7779-Remove-SDHI-and-MMCIF-function-.patch	\
	file://0443-ARM-shmobile-r8a7779-Remove-SCIF-function-GPIOs.patch	\
	file://0444-ARM-shmobile-r8a7779-Remove-HSPI-function-GPIOs.patch	\
	file://0445-ARM-shmobile-r8a7779-Remove-USB-function-GPIOs.patch	\
	file://0446-ARM-shmobile-r8a7779-Remove-LBSC-function-GPIOs.patch	\
	file://0447-ARM-shmobile-r8a7779-Remove-INTC-function-GPIOs.patch	\
	file://0448-gpio-Renesas-R-Car-GPIO-driver-V3.patch	\
	file://0449-sh-pfc-r8a7779-Remove-function-GPIOs.patch	\
	file://0450-sh-pfc-r8a7779-Don-t-use-GPIO-enum-entries.patch	\
	file://0451-ARM-shmobile-r8a7779-Remove-all-GPIOs.patch	\
	file://0452-ARM-shmobile-add-gic_iid-macro-for-ICCIAR-interrupt-.patch	\
	file://0453-gpio-rcar-Add-pinctrl-support.patch	\
	file://0454-sh-pfc-Make-function-GPIOs-support-optional.patch	\
	file://0455-sh-pfc-Make-GPIO-support-optional.patch	\
	file://0456-sh-pfc-Skip-gpiochip-registration-when-no-GPIO-resou.patch	\
	file://0457-sh-pfc-Configure-pins-as-GPIOs-at-request-time-when-.patch	\
	file://0458-ARM-shmobile-r8a7779-Register-GPIO-devices.patch	\
	file://0459-sh-pfc-r8a7779-Remove-GPIO-data.patch	\
	file://0460-ARM-shmobile-marzen-Add-GPIO-LEDs.patch	\
	file://0461-sh-pfc-r8a7779-Split-DU-input-and-output-pixel-clock.patch	\
	file://0462-sh-pfc-Initial-r8a7790-PFC-support.patch	\
	file://0463-sh-pfc-Remove-dependency-on-GPIOLIB.patch	\
	file://0464-gpio-rcar-Add-RCAR_GP_PIN-macro.patch	\
	file://0465-sh-pfc-r8a7790-Add-ETH-pin-groups-and-functions.patch	\
	file://0466-sh-pfc-r8a7790-Add-INTC-pin-groups-and-functions.patch	\
	file://0467-sh-pfc-r8a7790-Add-SCIF-SCIFA-and-SCIFB-pin-groups-a.patch	\
	file://0468-sh-pfc-r8a7790-Remove-GPIO-data.patch	\
	file://0469-sh-pfc-r8a7790-Remove-function-GPIOs.patch	\
	file://0470-sh-pfc-r8a7790-Don-t-use-GPIO-enum-entries.patch	\
	file://0471-ARM-shmobile-r8a7790-Register-GPIO-devices.patch	\
	file://0472-ARM-shmobile-r8a7790-Remove-all-GPIOs.patch	\
	file://0473-ARM-shmobile-Initial-r8a7790-Lager-board-support.patch	\
	file://0474-ARM-shmobile-use-r8a7790-timer-setup-code-on-Lager.patch	\
	file://0475-ARM-shmobile-lager-Initialize-pinmux.patch	\
	file://0476-ARM-shmobile-lager-Change-bootargs-in-DTS.patch	\
	file://0477-ARM-shmobile-r8a7790-Add-standard-drivers-clock-supp.patch	\
	file://0478-ARM-shmobile-r8a7790-Add-SMP-support.patch	\
	file://0479-ARM-shmobile-Fix-shmobile_defconfig-for-r8a7790.patch	\
	file://0480-ARM-shmobile-r8a7790-Remove-static-memory-map-region.patch	\
	file://0481-ARM-shmobile-r8a7790-Fix-SMP-to-pre-platform-SMP-ope.patch	\
	file://0482-ARM-shmobile-r8a7790-Add-RGX-support.patch	\
	file://0483-ARM-shmobile-r8a7790-Add-RGX-clock-enable.patch	\
	file://0484-ARM-shmobile-r8a7790-Add-power-management-support.patch	\
	file://0485-ARM-shmobile-r8a7790-Add-power-management-support-fo.patch	\
	file://0486-ARM-shmobile-lager-Fix-the-clock-frequency-of-arch_t.patch	\
	file://0487-ARM-shmobile-r8a7790-Add-CONFIG_MODULES-to-defconfig.patch	\
	file://0488-net-sh_eth-Add-R8A7790-support.patch	\
	file://0489-ARM-shmobile-r8a7790-Add-sh_eth-driver-support.patch	\
	file://0490-net-sh_eth-Change-PHY-LED-mode-to-Link-signal-for-La.patch	\
	file://0491-ARM-shmobile-r8a7790-Add-rcar-du-driver-support.patch	\
	file://0492-drm-rcar-du-Don-t-modify-mode-active-size-in-encoder.patch	\
	file://0493-drm-rcar-du-Use-the-mode-active-size-in-mode-set.patch	\
	file://0494-drm-rcar-du-Take-offsets-into-account-in-the-mode_se.patch	\
	file://0495-drm-rcar-du-Fix-plane-source-position-configuration.patch	\
	file://0496-drm-cma-helper-Support-double-buffering-through-fbde.patch	\
	file://0497-drm-rcar-du-Add-a-module-argument-to-enable-panning-.patch	\
	file://0498-drm-fb_helper-Support-FBIO_WAITFORVSYNC.patch	\
	file://0499-drm-rcar-du-Add-FBIOPAN_DISPLAY-triple-buffer-suppor.patch	\
	file://0500-drm-Fix-FBIOPAN_DISPLAY-ywrapstep.patch	\
	file://0501-drm-rcar-du-Add-LVDS-interface-function.patch	\
	file://0502-drm-rcar-du-Add-signal-selection-support.patch	\
	file://0503-ARM-shmobile-r8a7790-Add-DU1-support.patch	\
	file://0504-ARM-shmobile-r8a7790-Add-LVDS-interface-support.patch	\
	file://0505-usb-Add-ohci-ehci-host-driver-for-r8a7790.patch	\
	file://0506-ARM-shmobile-r8a7790-Add-ohci-ehci-host-driver-suppo.patch	\
	file://0507-ARM-shmobile-r8a7790-Fix-HS-USB-register-access-usin.patch	\
	file://0508-mmc-sh_mobile_sdhi-Add-buffer-access-size-switch-opt.patch	\
	file://0509-mmc-tmio-Add-CTL_RESET_SDIO-register-access-pass-opt.patch	\
	file://0510-mmc-tmio-Add-CTL_CLK_AND_WAIT_CTL-register-access-pa.patch	\
	file://0511-mmc-tmio-Add-busy-check-bit-switch-option.patch	\
	file://0512-mmc-card-Add-single-read-option-in-two-blocks-access.patch	\
	file://0513-mmc-tmio-Fix-odd-size-access.patch	\
	file://0514-mmc-tmio-Add-SD-clock-start-stop-wait-pass-option.patch	\
	file://0515-mmc-tmio-Add-error-IRQ-status-clear.patch	\
	file://0516-mmc-core-Add-MMC-password-protection-lock-unlock-sup.patch	\
	file://0517-mmc-core-Fix-block-size-after-password-protection.patch	\
	file://0518-mmc-sh_mobile_sdhi-Add-write-protection-notify-inter.patch	\
	file://0519-mmc-sh_mobile_sdhi-Add-dma_filter-in-private-data.patch	\
	file://0520-mmc-tmio-Fix-PIO-fall-back.patch	\
	file://0521-mmc-tmio-Add-return-processing-from-PIO-fall-back-to.patch	\
	file://0522-ARM-shmobile-r8a7790-Add-SD-driver-support.patch	\
	file://0523-mtd-devices-Add-Spansion-S25FL512S-support.patch	\
	file://0524-spi-Add-QSPI-driver.patch	\
	file://0525-ARM-shmobile-r8a7790-Add-QSPI-driver-support.patch	\
	file://0526-i2c-rcar-Add-extended-clock-division-factor-field-su.patch	\
	file://0527-ARM-shmobile-r8a7790-Add-rcar-i2c-driver-support.patch	\
	file://0528-dma-sh-Add-shdma-desc-driver.patch	\
	file://0529-ARM-shmobile-r8a7790-Add-shdma-desc-driver-support.patch	\
	file://0530-dma-sh-Add-audma-pp-driver.patch	\
	file://0531-ARM-shmobile-r8a7790-Add-audma-pp-driver-support.patch	\
	file://0532-sound-soc-sh-Add-scu_pcm-driver.patch	\
	file://0533-ARM-shmobile-r8a7790-Add-scu_pcm-driver-support.patch	\
	file://0534-sh-pfc-r8a7790-Rename-DU1_DOTCLKIN-to-DU_DOTCLKIN1.patch	\
	file://0535-sh-pfc-r8a7790-Add-DU-pin-groups-and-functions.patch	\
	file://0536-gpio-rcar-Make-the-platform-data-gpio_base-field-sig.patch	\
	file://0537-gpio-rcar-Add-support-for-IRQ_TYPE_EDGE_BOTH.patch	\
	file://0538-ARM-shmobile-lager-Add-GPIO-LEDs.patch	\
	file://0539-ARM-mach-shmobile-lager-support-GPIO-switches.patch	\
	file://0540-ARM-shmobile-r8a7790-Configure-R-Car-GPIO-for-IRQ_TY.patch	\
	file://0541-r8a7779-add-SDHI-clock-support.patch	\
	file://0542-ARM-shmobile-r8a7779-use-__iomem-pointers-for-MMIO.patch	\
	file://0543-ARM-shmobile-r8a7779-add-HSPI-clock-support.patch	\
	file://0544-ARM-shmobile-r8a7779-add-I2C-clock-support.patch	\
	file://0545-ARM-shmobile-r8a7779-add-USB-EHCI-clock-support.patch	\
	file://0546-ARM-shmobile-r8a7779-add-USB-OHCI-clock-support.patch	\
	file://0547-r8a7779-Add-Display-Unit-clock-support.patch	\
	file://0548-ARM-GIC-remove-direct-use-of-gic_raise_softirq.patch	\
	file://0549-irqchip-Move-ARM-GIC-to-drivers-irqchip.patch	\
	file://0550-irqchip-Move-ARM-gic.h-to-include-linux-irqchip-arm-.patch	\
	file://0551-ARM-shmobile-Initial-r8a7790-SoC-support.patch	\
	file://0552-drm-make-buffer-management-work-without-DRM_MASTER.patch	\
	file://0553-drm-change-ioctl-permissions.patch	\
	file://0554-drm-pass-dev-to-drm_vm_-open-close-_locked.patch	\
	file://0555-drm-gem-Split-drm_gem_mmap-into-object-search-and-ob.patch	\
	file://0556-drm-GEM-CMA-Split-object-mapping-into-GEM-mapping-an.patch	\
	file://0557-drm-rcar-du-Add-XRGB1555-format-support.patch	\
	file://0558-drm-rcar-du-Add-plane-property-to-set-global-alpha-v.patch	\
	file://0559-drm-rcar-du-Don-t-clean-up-mode-setting-if-it-hasn-t.patch	\
	file://0560-ARM-shmobile-r8a7779-Add-DU-support.patch	\
	file://0561-ARM-shmobile-marzen-Add-Display-Unit-support.patch	\
	file://0562-ARM-7376-1-clkdev-Implement-managed-clk_get.patch	\
	file://0563-ARM-7534-1-clk-Make-the-managed-clk-functions-generi.patch	\
	file://0564-libata-add-R-Car-SATA-driver.patch	\
	file://0565-libata-do-not-limit-R-Car-SATA-driver-to-shmobile.patch	\
	file://0566-ARM-mach-shmobile-r8a7779-add-SATA-support.patch	\
	file://0567-ARM-mach-shmobile-marzen-add-SATA-support.patch	\
	file://0568-ARM-mach-shmobile-marzen-add-SATA-support.patch	\
	file://0569-ARM-SoC-convert-shmobile-SMP-to-SMP-operations.patch	\
	file://0570-drm-rcar-du-Use-drm_send_vblank_event.patch	\
	file://0571-drm-rcar-du-Add-missing-alpha-plane-register-definit.patch	\
	file://0572-ARM-make-sched_clock-just-call-a-function-pointer.patch	\
	file://0573-arm-arch_timer-balance-device_node-refcounting.patch	\
	file://0574-arm-arch_timer-remove-redundant-available-check.patch	\
	file://0575-arm-arch_timer-use-u64-u32-for-register-data.patch	\
	file://0576-arm-arch_timer-standardise-counter-reading.patch	\
	file://0577-arm-arch_timer-split-cntfrq-accessor.patch	\
	file://0578-arm-arch_timer-factor-out-register-accessors.patch	\
	file://0579-arm-arch_timer-divorce-from-local_timer-api.patch	\
	file://0580-arm-arch_timer-add-arch_counter_set_user_access.patch	\
	file://0581-arm-arch_timer-move-core-to-drivers-clocksource.patch	\
	file://0582-ARM-arch_timer-include-linux-errno.h.patch	\
	file://0583-ARM-arch_timer-use-full-64-bit-counter-for-sched_clo.patch	\
	file://0584-arm-arch_timer-Do-not-set-C3STOP-in-case-CPU_IDLE-n.patch	\
	file://0585-irqchip-intc-irqpin-Add-support-for-shared-interrupt.patch	\
	file://0586-irqchip-renesas-intc-irqpin-DT-binding-for-sense-bit.patch	\
	file://0587-Revert-sh-sci-PM-Avoid-deadlocking-runtime-PM.patch	\
	file://0588-Revert-sh-sci-PM-Use-power.irq_safe.patch	\
	file://0589-Partially-revert-serial-sh-sci-console-Runtime-PM-su.patch	\
	file://0590-serial-sh-sci-console-runtime-PM-support-revisit.patch	\
	file://0591-serial-sh-sci-fix-condition-test-to-set-SCBRR.patch	\
	file://0592-serial-sh-sci-support-lower-baud-rate.patch	\
	file://0593-serial-sh-sci-mask-SCTFDR-RFDR-according-to-fifosize.patch	\
	file://0594-serial-sh-sci-fix-common-SCIFB-regmap-definition.patch	\
	file://0595-serial-sh-sci-add-locking-to-console-write-function-.patch	\
	file://0596-serial-sh-sci-fix-possible-race-cases-on-SCSCR-regis.patch	\
	file://0597-serial-sh-sci-HSCIF-support.patch	\
	file://0598-sh-pfc-r8a7790-Add-TPU-pin-groups-and-functions.patch	\
	file://0599-pinctrl-sh-pfc-fix-r8a7790-Function-Select-register-.patch	\
	file://0600-pinctrl-sh-pfc-fix-a-typo-in-pfc-r8a7790.patch	\
	file://0601-pinctrl-r8a7790-add-pinmux-data-for-MMCIF-and-SDHI-i.patch	\
	file://0602-sh-pfc-r8a7790-add-HSCIF-pin-groups.patch	\
	file://0603-pinctrl-r8a7790-fix-two-pin-numbers.patch	\
	file://0604-gpio-rcar-R-Car-GPIO-IRQ-share-interrupt.patch	\
	file://0605-gpio-rcar-Add-DT-support.patch	\
	file://0606-gpio-rcar-Use-OUTDT-when-reading-GPIOs-configured-as.patch	\
	file://0607-drm-Improve-manual-IRQ-installation-documentation.patch	\
	file://0608-lib-devres-Introduce-devm_ioremap_resource.patch	\
	file://0609-drm-rcar-du-Use-devm_ioremap_resource.patch	\
	file://0610-drm-rcar-du-Add-platform-module-device-table.patch	\
	file://0611-drm-rcar-du-Don-t-ignore-rcar_du_crtc_create-return-.patch	\
	file://0612-drm-rcar-du-Support-per-CRTC-clock-and-IRQ.patch	\
	file://0613-drm-rcar-du-Fix-buffer-pitch-alignment.patch	\
	file://0614-drm-rcar-du-Clarify-comment-regarding-plane-Y-source.patch	\
	file://0615-drm-rcar-du-Split-LVDS-encoder-and-connector.patch	\
	file://0616-drm-rcar-du-Split-VGA-encoder-and-connector.patch	\
	file://0617-drm-rcar-du-Merge-LVDS-and-VGA-encoder-code.patch	\
	file://0618-drm-rcar-du-Rename-platform-data-fields-to-match-wha.patch	\
	file://0619-drm-rcar-du-Create-rcar_du_planes-structure.patch	\
	file://0620-drm-rcar-du-Rename-rcar_du_plane_-init-register-to-r.patch	\
	file://0621-drm-rcar-du-Introduce-CRTCs-groups.patch	\
	file://0622-drm-rcar-du-Use-dynamic-number-of-CRTCs-instead-of-C.patch	\
	file://0623-drm-rcar-du-Remove-register-definitions-for-the-seco.patch	\
	file://0624-drm-rcar-du-Move-output-routing-configuration-to-gro.patch	\
	file://0625-drm-rcar-du-Add-support-for-the-R8A7790-DU.patch	\
	file://0626-drm-rcar-du-Fix-buffer-pitch-alignment-for-R8A7790-D.patch	\
	file://0627-drm-rcar-du-Add-support-for-multiple-groups.patch	\
	file://0628-drm-rcar-du-Add-support-for-DEFR8-register.patch	\
	file://0629-drm-rcar-du-Rework-output-routing-support.patch	\
	file://0630-drm-rcar-du-Configure-RGB-output-routing-to-DPAD0.patch	\
	file://0631-drm-rcar-du-Add-internal-LVDS-encoder-support.patch	\
	file://0632-Revert-ARM-shmobile-r8a7779-Add-DU-support.patch	\
	file://0633-Revert-ARM-shmobile-marzen-Add-Display-Unit-support.patch	\
	file://0634-ARM-shmobile-r8a7779-Add-DU-support.patch	\
	file://0635-ARM-shmobile-marzen-Add-Display-Unit-support.patch	\
	file://0636-ARM-shmobile-add-struct-clk_ratio-and-fixed-ratio-cl.patch	\
	file://0637-ARM-shmobile-remove-from-SH_FIXED_RATIO_CLK-macro.patch	\
	file://0638-ARM-shmobile-use-do-while-on-SH_CLK_SET_RATIO.patch	\
	file://0639-ARM-shmobile-r8a7790-add-main-clock.patch	\
	file://0640-ARM-shmobile-r8a7790-add-div4-clocks.patch	\
	file://0641-ARM-shmobile-r8a7790-add-div6-clocks.patch	\
	file://0642-ARM-sh-mobile-r8a7790-Make-private-clock-arrays-stat.patch	\
	file://0643-ARM-mach-shmobile-clock-r8a7790-add-TPU-PWM-support.patch	\
	file://0644-ARM-shmobile-r8a7790-HSCIF-support.patch	\
	file://0645-ARM-shmobile-r8a7790-add-clock-definitions-and-alias.patch	\
	file://0646-ARM-shmobile-r8a7790-HSCIF-support.patch	\
	file://0647-ARM-shmobile-r8a7790-don-t-use-external-clock-for-SC.patch	\
	file://0648-ARM-shmobile-r8a7790-Add-DU-clocks.patch	\
	file://0649-ARM-shmobile-r8a7790-Add-DU-support.patch	\
	file://0650-ARM-shmobile-r8a7790-Add-LVDS-clocks.patch	\
	file://0651-ARM-shmobile-r8a7790-Add-LVDS-support.patch	\
	file://0652-ARM-shmobile-lager-Add-Display-Unit-support.patch	\
	file://0653-sh-pfc-r8a7790-Fix-some-pins-definition.patch	\
	file://0654-ARM-shmobile-r8a7790-Add-sysdma-lower-channel-driver.patch	\
	file://0655-ARM-shmobile-r8a7790-Add-shdma-desc-clock-support.patch	\
	file://0656-ARM-shmobile-r8a7790-Add-DVC-route-support.patch	\
	file://0657-dma-sh-Add-descriptor-operating-mode.patch	\
	file://0658-ARM-shmobile-r8a7790-Add-descriptor-operating-mode-s.patch	\
	file://0659-i2c-rcar-Add-fixed-clock-setting-interface.patch	\
	file://0660-ARM-shmobile-r8a7790-Fix-I2C2-clock-setting.patch	\
	file://0661-ARM-shmobile-defconfig-Add-R-Car-GPIO-driver-support.patch	\
	file://0662-libata-sata_rcar-Add-r8a7790-quirk-to-R-Car-SATA-dri.patch	\
	file://0663-ARM-shmobile-r8a7790-Add-SATA-driver-support.patch	\
	file://0664-USB-xhci-fix-bit-definitions-for-IMAN-register.patch	\
	file://0665-usb-Add-Renesas-R-Car-xhci-host-driver.patch	\
	file://0666-usb-Add-xhci-host-driver-support-for-r8a7790.patch	\
	file://0667-ARM-shmobile-r8a7790-Add-xhci-host-driver-support.patch	\
	file://0668-sh-pfc-r8a7790-Add-USB-pin-groups.patch	\
	file://0669-ARM-shmobile-lager-Enable-USB-pin-groups.patch	\
	file://0670-ASoC-ak4642-prevent-un-necessary-changes-to-SG_SL1-w.patch	\
	file://0671-ASoC-sh-scu-Fix-SRC-timing-signal-select-for-recordi.patch	\
	file://0672-ASoC-sh-scu-Fix-SRC-initialize-process.patch	\
	file://0673-ASoC-sh-scu-Add-DVC-support.patch	\
	file://0674-ASoC-sh-scu-Add-syncronous-SRC-support.patch	\
	file://0675-ASoC-sh-scu-Fix-concurrent-playback-and-recording.patch	\
	file://0676-ASoC-sh-scu-Add-audma-descriptor-operating-mode-supp.patch	\
	file://0677-ASoC-sh-scu-Add-SRC-control-interface.patch	\
	file://0678-ASoC-sh-scu-Add-DVC-control-interface.patch	\
	file://0679-ASoC-sh-scu-Fix-work-queue-using-private-worker-thre.patch	\
	file://0680-ASoC-sh-scu-Fix-SSICR-register-mask.patch	\
	file://0681-ARM-shmobile-r8a7790-Fix-SDHI2-SDHI3-clock-rate.patch	\
	file://0682-mmc-tmio-Add-SDIO-status-reserved-bits-for-SH-Mobile.patch	\
	file://0683-ARM-shmobile-r8a7790-Add-SDIO-support.patch	\
	file://0684-sh-clkfwk-bugfix-sh_clk_div_enable-care-sh_clk_div_s.patch	\
	file://0685-mmc-sh_mmcif-add-support-for-bundled-MMCIF-IRQs.patch	\
	file://0686-mmc-sh_mmcif-Add-r8a7790-quirk-to-SH-MMC-driver.patch	\
	file://0687-ARM-shmobile-r8a7790-Add-MMC-driver-support.patch	\
	file://0688-spi-Add-SH-Mobile-series-as-dependency-to-MSIOF-cont.patch	\
	file://0689-spi-msiof-Fix-chipselect-signal-select.patch	\
	file://0690-sh-pfc-r8a7790-Add-MSIOF-pin-groups.patch	\
	file://0691-ARM-shmobile-r8a7790-Add-MSIOF-driver-support.patch	\
	file://0692-ARM-shmobile-lager-Enable-MSIOF-pin-groups.patch	\
	file://0693-sh-pfc-r8a7790-Add-VIN-pin-groups.patch	\
	file://0694-media-video-Add-Renesas-VIN-driver.patch	\
	file://0695-media-video-Add-ADV7180-decoder-driver.patch	\
	file://0696-media-video-Add-ADV7612-HDMI-receiver-driver.patch	\
	file://0697-ARM-shmobile-r8a7790-Add-VIN-driver-support.patch	\
	file://0698-ARM-shmobile-defconfig-Increase-FORCE_MAX_ZONEORDER-.patch	\
	file://0699-drivers-Fix-gpu-order-for-i2c-codec-support.patch	\
	file://0700-video-Add-generic-HDMI-helpers.patch	\
	file://0701-drm-rcar-du-Fix-PLL-multiplicatin-rate.patch	\
	file://0702-drm-i2c-Add-ADV7511-driver.patch	\
	file://0703-drm-Add-ADV7511-driver-support.patch	\
	file://0704-drm-Add-legacy-function-interface-for-ADV7511-driver.patch	\
	file://0705-drm-adv7511-Remove-audio-initialize.patch	\
	file://0706-drm-adv7511-Add-EDID-ready-wait.patch	\
	file://0707-drm-adv7511-Add-rcar-du-support.patch	\
	file://0708-drm-rcar-du-Add-HDMI-support.patch	\
	file://0709-drm-rcar-du-Fix-irq_enable-for-FBIO_WAITFORVSYNC.patch	\
	file://0710-drm-Add-display-resolution-parameters.patch	\
	file://0711-ARM-shmobile-defconfig-Enable-HDMI-for-lager.patch	\
	file://0712-ARM-shmobile-lager-Add-HDMI-support.patch	\
	file://0713-ARM-shmobile-defconfig-Enable-EXT2-and-EXT3-FS.patch	\
	file://0714-net-sh_eth-adjust-rx-ring-indices-for-Fast-Ethernet-.patch	\
	file://0715-ARM-shmobile-defconfig-Increase-SERIAL_SH_SCI_NR_UAR.patch	\
	file://0716-thermal-add-Renesas-R-Car-thermal-sensor-support.patch	\
	file://0717-thermal-solve-compilation-errors-in-rcar_thermal.patch	\
	file://0718-thermal-solve-compilation-errors-in-rcar_thermal-bac.patch	\
	file://0719-thermal-rcar_thermal-remove-explicitly-used-devm_kfr.patch	\
	file://0720-thermal-rcar-fixup-the-unit-of-temperature.patch	\
	file://0721-thermal-rcar-add-rcar_zone_to_priv-macro.patch	\
	file://0722-thermal-rcar-add-.get_trip_type-temp-and-.notify-sup.patch	\
	file://0723-thermal-rcar-use-parenthesis-on-macro.patch	\
	file://0724-thermal-rcar-enable-CPCTL-to-use-hardware-TSC-decidi.patch	\
	file://0725-thermal-rcar-use-mutex-lock-instead-of-spin-lock.patch	\
	file://0726-thermal-rcar-multi-channel-support.patch	\
	file://0727-thermal-rcar-add-read-write-functions-for-common-pri.patch	\
	file://0728-thermal-rcar-add-interrupt-support.patch	\
	file://0729-thermal-rcar-remove-machine_power_off-from-rcar_ther.patch	\
	file://0730-thermal-rcar-add-Device-Tree-support.patch	\
	file://0731-thermal-rcar-remove-__devinitconst.patch	\
	file://0732-thermal-rcar-fix-missing-unlock-on-error-in-rcar_the.patch	\
	file://0733-Thermal-rcar-Convert-to-devm_ioremap_resource.patch	\
	file://0734-thermal-rcar_thermal-propagate-return-value-of-therm.patch	\
	file://0735-thermal-rcar-tidyup-registration-failure-case.patch	\
	file://0736-thermal-rcar-add-pm_runtime_xxx-support.patch	\
	file://0737-ARM-shmobile-marzen-enable-thermal-sensor.patch	\
	file://0738-ARM-shmobile-r8a7790-add-clocks-for-thermal.patch	\
	file://0739-ARM-shmobile-r8a7790-add-thermal-driver-support.patch	\
	file://0740-sh-pfc-Add-r8a7791-PFC-support.patch	\
	file://0741-net-sh_eth-Add-r8a7791-support.patch	\
	file://0742-ARM-shmobile-Add-r8a7791-support.patch	\
	file://0743-ARM-shmobile-Add-koelsch-support.patch	\
	file://0744-ARM-shmobile-Remove-lager-configuration-from-shmobil.patch	\
	file://0745-ARM-shmobile-lager-Add-defconfig-file.patch	\
	file://0746-ARM-shmobile-keolsch-Enable-standard-driver-in-defco.patch	\
	file://0747-ARM-shmobile-lager-Enable-HIGHMEM-and-CMA-in-defconf.patch	\
	file://0748-ARM-shmobile-lager-Increase-kernel-memory-size-in-DT.patch	\
	file://0749-ARM-shmobile-koelsch-Enable-HIGHMEM-and-CMA-in-defco.patch	\
	file://0750-ARM-shmobile-r8a7791-Add-I2C-driver-support.patch	\
	file://0751-ARM-shmobile-r8a7790-Fix-I2C-resource-size.patch	\
	file://0752-dma-sh-Fix-copyright-and-author.patch	\
	file://0753-ARM-shmobile-lager-Remove-CONFIG_SH_DMAE-in-defconfi.patch	\
	file://0754-ARM-shmobile-koelsch-Remove-CONFIG_SH_DMAE-in-defcon.patch	\
	file://0755-dma-Fix-shdma-make-rules.patch	\
	file://0756-dma-shdma-desc-Fix-max-channel-number.patch	\
	file://0757-dma-shdma-desc-Fix-verbose-calculation-of-channel-ad.patch	\
	file://0758-dma-shdma-desc-Fix-dma-reset.patch	\
	file://0759-ARM-shmobile-r8a7790-Remove-dma-channel-clear-offset.patch	\
	file://0760-ARM-shmobile-r8a7791-Add-shdma-desc-driver-support.patch	\
	file://0761-ARM-shmobile-r8a7791-Add-audma-pp-driver-support.patch	\
	file://0762-ARM-shmobile-r8a7790-Fix-MSIOF-clock-and-device-id.patch	\
	file://0763-ARM-shmobile-r8a7790-Add-MSIOF-clocks.patch	\
	file://0764-ARM-shmobile-lager-Move-MSIOF-spi_board_info-to-boar.patch	\
	file://0765-ARM-shmobile-r8a7790-Fix-QSPI-platform_device-data.patch	\
	file://0766-ARM-shmobile-lager-Move-QSPI-spi_board_info-to-board.patch	\
	file://0767-sh-pfc-r8a7791-Add-MSIOF-pin-groups.patch	\
	file://0768-ARM-shmobile-r8a7791-Add-MSIOF-driver-support.patch	\
	file://0769-ARM-shmobile-koelsch-Add-MSIOF-support.patch	\
	file://0770-ARM-shmobile-r8a7791-Add-QSPI-driver-support.patch	\
	file://0771-ARM-shmobile-koelsch-Add-QSPI-support.patch	\
	file://0772-sh-pfc-r8a7791-Add-SCIF-pin-groups.patch	\
	file://0773-ARM-shmobile-r8a7791-Add-SCIF-driver-support.patch	\
	file://0774-ARM-shmobile-koelsch-Fix-SCIF-pinctrl-map.patch	\
	file://0775-sh-pfc-r8a7791-Add-USB-pin-groups.patch	\
	file://0776-ARM-shmobile-r8a7791-Add-USB-driver-support.patch	\
	file://0777-ARM-shmobile-koelsch-Add-USB-pinctrl-map.patch	\
	file://0778-sh-pfc-r8a7791-Add-MMC-pin-groups.patch	\
	file://0779-mmc-sh_mmcif-Add-r8a7791-support.patch	\
	file://0780-ARM-shmobile-r8a7791-Add-MMC-driver-support.patch	\
	file://0781-libata-sata_rcar-Add-r8a7791-support.patch	\
	file://0782-ARM-shmobile-r8a7791-Add-SATA-driver-support.patch	\
	file://0783-sh-pfc-r8a7791-Add-VIN-pin-groups.patch	\
	file://0784-ARM-shmobile-r8a7791-Add-VIN-driver-support.patch	\
	file://0785-ARM-shmobile-koelsch-Add-VIN-support.patch	\
	file://0786-ARM-shmobile-r8a7790-Add-SCIF2-support.patch	\
	file://0787-ARM-shmobile-r8a7791-Fix-SDHI-DMA-slave-configuratio.patch	\
	file://0788-ARM-shmobile-r8a7790-Fix-USB-clock-check.patch	\
	file://0789-ARM-shmobile-r8a7790-Fix-USB-ioremap-error.patch	\
	file://0790-sh-pfc-Fix-copyright.patch	\
	file://0791-ARM-shmobile-Fix-r8a7791-support.patch	\
	file://0792-mfd-Add-DA9063-driver.patch	\
	file://0793-ARM-shmobile-lager-Add-restart-function.patch	\
	file://0794-ARM-shmobile-r8a7791-Add-SGX-support.patch	\
	file://0795-ARM-shmobile-r8a7791-Add-SGX-clock-enable.patch	\
	file://0796-ARM-shmobile-r8a7791-Add-power-management-support.patch	\
	file://0797-ARM-shmobile-r8a7791-Add-power-management-support-fo.patch	\
	file://0798-mmc-tmio_mmc-Fix-copyright.patch	\
	file://0799-sh-pfc-r8a7791-Add-SDHI-pin-groups.patch	\
	file://0800-ARM-shmobile-r8a7791-Add-SD-driver-support.patch	\
	file://0801-ARM-shmobile-koelsch-Add-SD-driver-support.patch	\
	file://0802-ARM-shmobile-lager-Move-SD-support-to-board-dependen.patch	\
	file://0803-ASoC-sh-scu-Fix-author.patch	\
	file://0804-ASoC-sh-scu-Fix-return-value-of-mute-setting.patch	\
	file://0805-ASoC-sh-scu-Add-channel-parameter-to-DAPM-callbacks.patch	\
	file://0806-ASoC-sh-scu-Fix-inverted-stereo-in-case-of-SRC-path.patch	\
	file://0807-ASoC-sh-scu-Fix-SSI-start-and-stop-procedure.patch	\
	file://0808-ASoC-sh-scu-Fix-DVC-volume-control.patch	\
	file://0809-ASoC-sh-scu-Fix-route-check-variable.patch	\
	file://0810-ASoC-sh-scu-Add-codec-powerup-wait.patch	\
	file://0811-ASoC-sh-scu-Add-variable-period-size-support.patch	\
	file://0812-ASoC-sh-scu-Add-koelsch-support.patch	\
	file://0813-ARM-shmobile-r8a7791-Add-scu_pcm-driver-support.patch	\
	file://0814-ARM-shmobile-koelsch-Add-scu_pcm-support-in-defconfi.patch	\
	file://0815-Revert-drm-Add-display-resolution-parameters.patch	\
	file://0816-Revert-drm-rcar-du-Fix-irq_enable-for-FBIO_WAITFORVS.patch	\
	file://0817-Revert-drm-rcar-du-Add-HDMI-support.patch	\
	file://0818-Revert-drm-adv7511-Add-rcar-du-support.patch	\
	file://0819-Revert-drm-adv7511-Add-EDID-ready-wait.patch	\
	file://0820-Revert-drm-adv7511-Remove-audio-initialize.patch	\
	file://0821-Revert-drm-Add-legacy-function-interface-for-ADV7511.patch	\
	file://0822-Revert-drm-Add-ADV7511-driver-support.patch	\
	file://0823-Revert-drm-i2c-Add-ADV7511-driver.patch	\
	file://0824-Revert-drm-rcar-du-Fix-PLL-multiplicatin-rate.patch	\
	file://0825-Revert-video-Add-generic-HDMI-helpers.patch	\
	file://0826-Revert-drivers-Fix-gpu-order-for-i2c-codec-support.patch	\
	file://0827-Revert-drm-rcar-du-Add-LVDS-interface-function.patch	\
	file://0828-Revert-drm-Fix-FBIOPAN_DISPLAY-ywrapstep.patch	\
	file://0829-Revert-drm-rcar-du-Add-FBIOPAN_DISPLAY-triple-buffer.patch	\
	file://0830-Revert-drm-fb_helper-Support-FBIO_WAITFORVSYNC.patch	\
	file://0831-Revert-drm-rcar-du-Add-a-module-argument-to-enable-p.patch	\
	file://0832-Revert-drm-cma-helper-Support-double-buffering-throu.patch	\
	file://0833-Revert-ARM-shmobile-Initial-r8a7790-SoC-support.patch	\
	file://0834-drm-review-locking-rules-in-drm_crtc.c.patch	\
	file://0835-drm-drivers-Unified-handling-of-unimplemented-fb-cre.patch	\
	file://0836-drm-encapsulate-crtc-set_config-calls.patch	\
	file://0837-drm-add-drm_modeset_lock-unlock_all.patch	\
	file://0838-drm-add-per-crtc-locks.patch	\
	file://0839-drm-only-take-the-crtc-lock-for-cursor_set.patch	\
	file://0840-drm-only-take-the-crtc-lock-for-cursor_move.patch	\
	file://0841-drm-revamp-locking-around-fb-creation-destruction.patch	\
	file://0842-drm-create-drm_framebuffer_lookup.patch	\
	file://0843-media-v4l2-dev-make-it-possible-to-skip-locking-for-.patch	\
	file://0844-media-v4l2-dev-ioctl-determine-the-valid-ioctls-upfr.patch	\
	file://0845-media-v4l2-ioctl-handle-priority-handling-based-on-a.patch	\
	file://0846-media-v4l2-framework-add-support-for-the-new-dv_timi.patch	\
	file://0847-media-v4l2-ioctl-set-readbuffers-to-2-in-g_parm.patch	\
	file://0848-media-v4l2-ioctl.c-move-a-block-of-code-down-no-othe.patch	\
	file://0849-media-v4l2-ioctl.c-introduce-INFO_FL_CLEAR-to-replac.patch	\
	file://0850-media-v4l2-ioctl.c-v4l2-ioctl-add-debug-and-callback.patch	\
	file://0851-media-v4l2-ioctl.c-remove-an-unnecessary-ifdef.patch	\
	file://0852-media-v4l2-ioctl.c-use-the-new-table-for-querycap-an.patch	\
	file://0853-media-v4l2-ioctl.c-use-the-new-table-for-priority-io.patch	\
	file://0854-media-v4l2-ioctl.c-use-the-new-table-for-format-fram.patch	\
	file://0855-media-v4l2-ioctl.c-use-the-new-table-for-overlay-str.patch	\
	file://0856-media-v4l2-ioctl.c-use-the-new-table-for-std-tuner-m.patch	\
	file://0857-media-v4l2-ioctl.c-use-the-new-table-for-queuing-par.patch	\
	file://0858-media-v4l2-ioctl.c-use-the-new-table-for-control-ioc.patch	\
	file://0859-media-v4l2-ioctl.c-use-the-new-table-for-selection-i.patch	\
	file://0860-media-v4l2-ioctl.c-use-the-new-table-for-compression.patch	\
	file://0861-media-v4l2-ioctl.c-use-the-new-table-for-debug-ioctl.patch	\
	file://0862-media-v4l2-ioctl.c-use-the-new-table-for-preset-timi.patch	\
	file://0863-media-v4l2-ioctl.c-use-the-new-table-for-the-remaini.patch	\
	file://0864-media-v4l2-ioctl.c-finalize-table-conversion.patch	\
	file://0865-media-v4l2-dev.c-add-debug-sysfs-entry.patch	\
	file://0866-media-v4l2-ioctl-remove-v4l_-i2c_-print_ioctl.patch	\
	file://0867-media-v4l2-dev-rename-two-functions.patch	\
	file://0868-media-v4l2-dev-ioctl.c-add-vb2_queue-support-to-vide.patch	\
	file://0869-media-Fix-circular-graph-traversal.patch	\
	file://0870-media-media-add-new-mediabus-format-enums-for-dm365.patch	\
	file://0871-media-V4L-DocBook-Add-V4L2_MBUS_FMT_YUV10_1X30-media.patch	\
	file://0872-media-soc_camera-Add-RGB666-RGB888-formats.patch	\
	file://0873-v4l-Add-media-format-codes-for-ARGB8888-and-AYUV8888.patch	\
	file://0874-media-v4l-Add-fourcc-definitions-for-new-formats.patch	\
	file://0875-v4l-Add-V4L2_PIX_FMT_NV16M-and-V4L2_PIX_FMT_NV61M-fo.patch	\
	file://0876-media-v4l-Define-video-buffer-flags-for-timestamp-ty.patch	\
	file://0877-media-v4l-Define-video-buffer-flag-for-the-COPY-time.patch	\
	file://0878-media-v4l-Add-DMABUF-as-a-memory-type.patch	\
	file://0879-media-v4l-vb-remove-warnings-about-MEMORY_DMABUF.patch	\
	file://0880-media-v4l-vb2-add-support-for-shared-buffer-dma_buf.patch	\
	file://0881-media-v4l2-dev-add-new-VFL_DIR_-defines.patch	\
	file://0882-media-v4l2-dev-add-flag-to-have-the-core-lock-all-fi.patch	\
	file://0883-media-videodev2.h-add-enum-query-cap-dv_timings-ioct.patch	\
	file://0884-media-Fix-query-enum_dv_timings-regression.patch	\
	file://0885-media-v4l2-dev.c-fix-g_parm-regression-in-determine_.patch	\
	file://0886-media-media-Add-link_validate-op-to-check-links-to-t.patch	\
	file://0887-media-v4l-Implement-v4l2_subdev_link_validate.patch	\
	file://0888-media-v4l-Helper-function-for-obtaining-timestamps.patch	\
	file://0889-media-vb2-Add-support-for-non-monotonic-timestamps.patch	\
	file://0890-ARM-shmobile-wait-for-MSTP-clock-status-to-toggle-wh.patch	\
	file://0891-ARM-shmobile-r8a7790-Add-VSP1-clocks.patch	\
	file://0892-ARM-shmobile-r8a7790-Enable-status-checks-for-VSP1-c.patch	\
	file://0893-ARM-shmobile-r8a7790-Add-VSP1-support.patch	\
	file://0894-clocksource-sh_cmt-Convert-timer-lock-to-raw-spinloc.patch	\
	file://0895-ARM-shmobile-Sort-r8a7790-MSTP-entries.patch	\
	file://0896-ARM-shmobile-Add-r8a7790-CMT00-clock-event.patch	\
	file://0897-ARM-shmobile-Introduce-r8a7790_read_mode_pins.patch	\
	file://0898-ARM-shmobile-Setup-r8a7790-arch-timer-based-on-MD-pi.patch	\
	file://0899-Drivers-clocksource-remove-__dev-attributes.patch	\
	file://0900-clocksource-sh_cmt-Take-care-of-clk_put-when-setup_i.patch	\
	file://0901-clocksource-sh_cmt-Initialize-max_match_value-and-lo.patch	\
	file://0902-clocksource-sh_cmt-Introduce-per-register-functions.patch	\
	file://0903-clocksource-sh_cmt-Consolidate-platform_set_drvdata-.patch	\
	file://0904-clocksource-sh_cmt-CMSTR-and-CMCSR-register-access-u.patch	\
	file://0905-clocksource-sh_cmt-CMCNT-and-CMCOR-register-access-u.patch	\
	file://0906-clocksource-sh_cmt-Add-control-register-callbacks.patch	\
	file://0907-clocksource-sh_cmt-Add-CMT-register-layout-comment.patch	\
	file://0908-clocksource-sh_cmt-Set-initcall-level-to-subsys.patch	\
	file://0909-clocksource-sh_cmt-32-bit-control-register-support.patch	\
	file://0910-drm-revamp-framebuffer-cleanup-interfaces.patch	\
	file://0911-drm-reference-framebuffers-which-are-on-the-idr.patch	\
	file://0912-drm-refcounting-for-sprite-framebuffers.patch	\
	file://0913-drm-Don-t-set-the-plane-fb-to-NULL-on-successfull-se.patch	\
	file://0914-drm-fb_helper-Support-FBIO_WAITFORVSYNC.patch	\
	file://0915-Revert-drm-rcar-du-Add-internal-LVDS-encoder-support.patch	\
	file://0916-Revert-drm-rcar-du-Configure-RGB-output-routing-to-D.patch	\
	file://0917-Revert-drm-rcar-du-Rework-output-routing-support.patch	\
	file://0918-Revert-drm-rcar-du-Add-support-for-DEFR8-register.patch	\
	file://0919-Revert-drm-rcar-du-Add-support-for-multiple-groups.patch	\
	file://0920-Revert-drm-rcar-du-Fix-buffer-pitch-alignment-for-R8.patch	\
	file://0921-Revert-drm-rcar-du-Add-support-for-the-R8A7790-DU.patch	\
	file://0922-Revert-drm-rcar-du-Move-output-routing-configuration.patch	\
	file://0923-Revert-drm-rcar-du-Remove-register-definitions-for-t.patch	\
	file://0924-Revert-drm-rcar-du-Use-dynamic-number-of-CRTCs-inste.patch	\
	file://0925-Revert-drm-rcar-du-Introduce-CRTCs-groups.patch	\
	file://0926-Revert-drm-rcar-du-Rename-rcar_du_plane_-init-regist.patch	\
	file://0927-Revert-drm-rcar-du-Create-rcar_du_planes-structure.patch	\
	file://0928-Revert-drm-rcar-du-Rename-platform-data-fields-to-ma.patch	\
	file://0929-Revert-drm-rcar-du-Merge-LVDS-and-VGA-encoder-code.patch	\
	file://0930-Revert-drm-rcar-du-Split-VGA-encoder-and-connector.patch	\
	file://0931-Revert-drm-rcar-du-Split-LVDS-encoder-and-connector.patch	\
	file://0932-Revert-drm-rcar-du-Clarify-comment-regarding-plane-Y.patch	\
	file://0933-Revert-drm-rcar-du-Fix-buffer-pitch-alignment.patch	\
	file://0934-Revert-drm-rcar-du-Support-per-CRTC-clock-and-IRQ.patch	\
	file://0935-Revert-drm-rcar-du-Don-t-ignore-rcar_du_crtc_create-.patch	\
	file://0936-Revert-drm-rcar-du-Add-platform-module-device-table.patch	\
	file://0937-Revert-drm-rcar-du-Use-devm_ioremap_resource.patch	\
	file://0938-Revert-drm-rcar-du-Add-missing-alpha-plane-register-.patch	\
	file://0939-Revert-drm-rcar-du-Use-drm_send_vblank_event.patch	\
	file://0940-Revert-drm-rcar-du-Enable-extended-range-for-display.patch	\
	file://0941-Revert-drm-rcar-du-Don-t-clean-up-mode-setting-if-it.patch	\
	file://0942-Revert-drm-rcar-du-Fix-plane-source-position-configu.patch	\
	file://0943-Revert-drm-rcar-du-Take-offsets-into-account-in-the-.patch	\
	file://0944-Revert-drm-rcar-du-Use-the-mode-active-size-in-mode-.patch	\
	file://0945-Revert-drm-rcar-du-Don-t-modify-mode-active-size-in-.patch	\
	file://0946-Revert-drm-rcar-du-Add-plane-property-to-set-global-.patch	\
	file://0947-Revert-drm-rcar-du-Add-XRGB1555-format-support.patch	\
	file://0948-Revert-drm-rcar-du-Add-FBDEV-emulation-support.patch	\
	file://0949-Revert-drm-rcar-du-Add-support-for-cloned-mode-on-DU.patch	\
	file://0950-Revert-drm-rcar-du-Create-common-encoder-and-connect.patch	\
	file://0951-Revert-drm-rcar-du-Reorganize-CRTC-start-stop-and-po.patch	\
	file://0952-Revert-drm-rcar-du-Centralize-DU-device-core-resourc.patch	\
	file://0953-Revert-drm-rcar-du-Prepare-unprepare-clock.patch	\
	file://0954-Revert-drm-rcar-du-Fix-crash-when-disabling-an-alrea.patch	\
	file://0955-Revert-drm-rcar-du-Name-the-encoder-platform-data-un.patch	\
	file://0956-Revert-drm-rcar-du-Add-support-for-the-second-CRTC.patch	\
	file://0957-Revert-drm-rcar-du-Split-hardware-and-KMS-planes.patch	\
	file://0958-Revert-drm-rcar-du-Enable-the-DE-signal.patch	\
	file://0959-Revert-drm-rcar-du-Fix-plane-index-wrap-around-for-m.patch	\
	file://0960-Revert-drm-rcar-du-Fix-register-access-for-global-re.patch	\
	file://0961-Revert-drm-rcar-du-Update-plane-format-after-releasi.patch	\
	file://0962-Revert-drm-rcar-du-Support-configurable-color-keying.patch	\
	file://0963-Revert-drm-rcar-du-Add-configurable-z-order-support-.patch	\
	file://0964-Revert-drm-rcar-du-Fix-race-condition-between-page-f.patch	\
	file://0965-Revert-drm-rcar-du-Add-DRM-PRIME-support.patch	\
	file://0966-Revert-drm-rcar-du-Fix-planes-allocation-for-multipl.patch	\
	file://0967-Revert-drm-rcar-du-Don-t-re-reserve-hardware-plane-a.patch	\
	file://0968-Revert-drm-rcar-du-Enable-alpha-blending-support.patch	\
	file://0969-Revert-drm-rcar-du-Use-drm_encoder_cleanup-directly-.patch	\
	file://0970-Revert-drm-Renesas-R-Car-Display-Unit-DRM-driver.patch	\
	file://0971-drm-Renesas-R-Car-Display-Unit-DRM-driver.patch	\
	file://0972-drm-rcar-du-Use-drm_encoder_cleanup-directly-as-.des.patch	\
	file://0973-drm-rcar-du-Enable-alpha-blending-support.patch	\
	file://0974-drm-rcar-du-Don-t-re-reserve-hardware-plane-at-each-.patch	\
	file://0975-drm-rcar-du-Fix-planes-allocation-for-multiplanar-fo.patch	\
	file://0976-drm-rcar-du-Add-DRM-PRIME-support.patch	\
	file://0977-drm-rcar-du-Fix-race-condition-between-page-flip-req.patch	\
	file://0978-drm-rcar-du-Add-configurable-z-order-support-for-pla.patch	\
	file://0979-drm-rcar-du-Support-configurable-color-keying-for-pl.patch	\
	file://0980-drm-rcar-du-Update-plane-format-after-releasing-hard.patch	\
	file://0981-drm-rcar-du-Fix-register-access-for-global-registers.patch	\
	file://0982-drm-rcar-du-Fix-plane-index-wrap-around-for-multi-pl.patch	\
	file://0983-drm-rcar-du-Enable-the-DE-signal.patch	\
	file://0984-drm-rcar-du-Split-hardware-and-KMS-planes.patch	\
	file://0985-drm-rcar-du-Add-support-for-the-second-CRTC.patch	\
	file://0986-drm-rcar-du-Name-the-encoder-platform-data-union.patch	\
	file://0987-drm-rcar-du-Fix-crash-when-disabling-an-already-disa.patch	\
	file://0988-drm-rcar-du-Prepare-unprepare-clock.patch	\
	file://0989-drm-rcar-du-Centralize-DU-device-core-resource-manag.patch	\
	file://0990-drm-rcar-du-Reorganize-CRTC-start-stop-and-power-man.patch	\
	file://0991-drm-rcar-du-Create-common-encoder-and-connector-stru.patch	\
	file://0992-drm-rcar-du-Add-support-for-cloned-mode-on-DU1.patch	\
	file://0993-drm-rcar-du-Add-XRGB1555-format-support.patch	\
	file://0994-drm-rcar-du-Add-plane-property-to-set-global-alpha-v.patch	\
	file://0995-drm-rcar-du-Don-t-modify-mode-active-size-in-encoder.patch	\
	file://0996-drm-rcar-du-Use-the-mode-active-size-in-mode-set.patch	\
	file://0997-drm-rcar-du-Take-offsets-into-account-in-the-mode_se.patch	\
	file://0998-drm-rcar-du-Fix-plane-source-position-configuration.patch	\
	file://0999-drm-rcar-du-Don-t-clean-up-mode-setting-if-it-hasn-t.patch	\
	file://1000-drm-rcar-du-Enable-extended-range-for-display-timing.patch	\
	file://1001-drm-rcar-du-Use-drm_send_vblank_event.patch	\
	file://1002-drm-rcar-du-Enable-compilation-on-all-ARM-platforms.patch	\
	file://1003-drm-rcar-du-Don-t-add-default-modes-to-VGA-connector.patch	\
	file://1004-drm-rcar-du-Don-t-ignore-rcar_du_crtc_create-return-.patch	\
	file://1005-drm-rcar-du-Fix-buffer-pitch-alignment.patch	\
	file://1006-drm-rcar-du-Add-missing-alpha-plane-register-definit.patch	\
	file://1007-drm-rcar-du-Use-devm_ioremap_resource.patch	\
	file://1008-drm-rcar-du-Add-platform-module-device-table.patch	\
	file://1009-drm-rcar-du-Support-per-CRTC-clock-and-IRQ.patch	\
	file://1010-drm-rcar-du-Clarify-comment-regarding-plane-Y-source.patch	\
	file://1011-drm-rcar-du-Split-LVDS-encoder-and-connector.patch	\
	file://1012-drm-rcar-du-Split-VGA-encoder-and-connector.patch	\
	file://1013-drm-rcar-du-Merge-LVDS-and-VGA-encoder-code.patch	\
	file://1014-drm-rcar-du-Rename-platform-data-fields-to-match-wha.patch	\
	file://1015-drm-rcar-du-Create-rcar_du_planes-structure.patch	\
	file://1016-drm-rcar-du-Rename-rcar_du_plane_-init-register-to-r.patch	\
	file://1017-drm-rcar-du-Introduce-CRTCs-groups.patch	\
	file://1018-drm-rcar-du-Use-dynamic-number-of-CRTCs-instead-of-C.patch	\
	file://1019-drm-rcar-du-Remove-register-definitions-for-the-seco.patch	\
	file://1020-drm-rcar-du-Move-output-routing-configuration-to-gro.patch	\
	file://1021-drm-rcar-du-Add-support-for-the-R8A7790-DU.patch	\
	file://1022-drm-rcar-du-Fix-buffer-pitch-alignment-for-R8A7790-D.patch	\
	file://1023-drm-rcar-du-Add-support-for-multiple-groups.patch	\
	file://1024-drm-rcar-du-Add-support-for-DEFR8-register.patch	\
	file://1025-drm-rcar-du-Rework-output-routing-support.patch	\
	file://1026-drm-rcar-du-Configure-RGB-output-routing-to-DPAD0.patch	\
	file://1027-drm-rcar-du-Add-internal-LVDS-encoder-support.patch	\
	file://1028-HACK-drm-rcar-du-Add-default-modes-to-VGA-connector.patch	\
	file://1029-drm-rcar-du-Add-FBDEV-emulation-support.patch	\
	file://1030-drm-cma-helper-Support-double-buffering-through-fbde.patch	\
	file://1031-drm-rcar-du-Add-a-module-argument-to-enable-panning-.patch	\
	file://1032-ARM-shmobile-lager-Add-VSP1-support.patch	\
	file://1033-drm-Add-live-source-object.patch	\
	file://1034-drm-Connect-live-source-to-plane.patch	\
	file://1035-drm-rcar-du-Add-VSP1-support-to-the-planes-allocator.patch	\
	file://1036-drm-rcar-du-Add-VSP1-live-source-support.patch	\
	file://1037-v4l-Renesas-VSP1-driver.patch	\
	file://1038-Revert-ARM-shmobile-marzen-Add-Display-Unit-support.patch	\
	file://1039-Revert-ARM-shmobile-r8a7779-Add-DU-support.patch	\
	file://1040-ARM-shmobile-r8a7779-Add-DU-support.patch	\
	file://1041-ARM-shmobile-marzen-Add-Display-Unit-support.patch	\
	file://1042-Partially-Revert-drm-Renesas-R-Car-Display-Unit-DRM-.patch	\
	file://1043-drm-Add-live-source-object.patch	\
	file://1044-drm-rcar-du-Add-FBIOPAN_DISPLAY-triple-buffer-suppor.patch	\
	file://1045-drm-Fix-FBIOPAN_DISPLAY-ywrapstep.patch	\
	file://1046-drivers-Fix-gpu-order-for-i2c-codec-support.patch	\
	file://1047-drm-Fix-rcar-du-order-for-i2c-codec-support.patch	\
	file://1048-video-Add-generic-HDMI-helpers.patch	\
	file://1049-drm-i2c-Add-ADV7511-driver.patch	\
	file://1050-drm-Add-ADV7511-driver-support.patch	\
	file://1051-drm-Add-legacy-function-interface-for-ADV7511-driver.patch	\
	file://1052-drm-adv7511-Remove-audio-initialize.patch	\
	file://1053-drm-adv7511-Add-EDID-ready-wait.patch	\
	file://1054-drm-adv7511-Add-rcar-du-support.patch	\
	file://1055-drm-rcar-du-Add-HDMI-support.patch	\
	file://1056-drm-Add-display-resolution-parameters.patch	\
	file://1057-sh-pfc-r8a7791-Fix-pin-names.patch	\
	file://1058-sh-pfc-r8a7791-Add-DU-pin-groups.patch	\
	file://1059-drm-rcar-du-Add-r8a7791-support.patch	\
	file://1060-drm-rcar-du-HDMI-hotplug-detect-support.patch	\
	file://1061-drm-rcar-du-Fix-RGB-output-port-for-r8a7790.patch	\
	file://1062-drm-Fix-frame-buffer-resolution-is-set-as-HDMI.patch	\
	file://1063-drm-rcar-du-Add-LVDS-CH-control-register-workaround.patch	\
	file://1064-drm-rcar-du-Add-no-LVDS-interface-feature.patch	\
	file://1065-drm-rcar-du-Add-external-clock-use-feature.patch	\
	file://1066-ARM-shmobile-r8a7791-Add-DU-support.patch	\
	file://1067-ARM-shmobile-koelsch-Add-DU-support.patch	\
	file://1068-ARM-shmobile-r8a7790-Fix-MMC-clock-support.patch	\
	file://1069-ARM-shmobile-lager-Move-MMC-support-to-board-depende.patch	\
	file://1070-ARM-shmobile-r8a7791-Fix-MMC-clock-support.patch	\
	file://1071-ARM-shmobile-koelsch-Move-MMC-support-to-board-depen.patch	\
	file://1072-ASoC-sh-lager-Fix-control-names.patch	\
	file://1073-ASoC-sh-koelsch-Fix-control-names.patch	\
	file://1074-ARM-shmobile-r8a7790-Fix-SDHI-clock-support.patch	\
	file://1075-ARM-shmobile-r8a7791-Fix-SDHI-clock-support.patch	\
	file://1076-mmc-tmio-Add-disable-auto-CMD12.patch	\
	file://1077-mmc-sh_mobile_sdhi-Add-disable-auto-CMD12-support.patch	\
	file://1078-drm-rcar-du-Disable-alpha-blending-of-lowest-planes.patch	\
	file://1079-drm-Add-CRTC-selector-for-FBDev-access-support.patch	\
	file://1080-ARM-shmobile-lager-Enable-DRM_FBDEV_CRTC-in-defconfi.patch	\
	file://1081-ARM-shmobile-koelsch-Enable-DRM_FBDEV_CRTC-in-defcon.patch	\
	file://1082-net-sh_eth-Fix-bit-shift-position-of-receive-frame-s.patch	\
	file://1083-net-sh_eth-Fix-cache-invalidation-omission-of-receiv.patch	\
	"

S = "${WORKDIR}/git"

FILESEXTRAPATHS_prepend_koelsch := "${THISDIR}/${PN}:"

KERNEL_DEFCONFIG = "koelsch_defconfig"

do_configure_prepend() {
        install -m 0644 ${S}/arch/${ARCH}/configs/${KERNEL_DEFCONFIG} ${WORKDIR}/defconfig || die "No default configuration for ${MACHINE} / ${KERNEL_DEFCONFIG} available."
}

