require linux.inc
require linux-dtb.inc

DESCRIPTION = "Linux kernel for the lager board"
COMPATIBLE_MACHINE = "lager"

PR = "r0"
PV_append = "+git${SRCREV}"

SRCREV = "4938ff7a961bcf44ef53c4a928f6cf9c4e6ddb4d"
SRC_URI = "git://git.yoctoproject.org/linux-yocto-3.4.git;protocol=git;branch=ltsi \
	file://0001-drm-Move-drm_format_num_planes-to-drm_crtc.c.patch \
	file://0002-drm-Add-drm_format_plane_cpp-utility-function.patch \
	file://0003-drm-Add-drm_format_-horz-vert-_chroma_subsampling-ut.patch \
	file://0004-drm-Add-sanity-checks-to-framebuffer-creation.patch \
	file://0005-drm-Fix-EDID-color-format-parsing.patch \
	file://0006-drm-Parse-color-format-information-in-CEA-blocks.patch \
	file://0007-drm-add-the-VIC-number-to-the-CEA-EDID-modes.patch \
	file://0008-drm-add-DRM_MODE_FLAG_DBLCLK-to-CEA-modes-requiring-.patch \
	file://0009-drm-edid-Document-drm_mode_find_dmt.patch \
	file://0010-drm-edid-Rewrite-drm_mode_find_dmt-search-loop.patch \
	file://0011-drm-edid-Allow-drm_mode_find_dmt-to-hunt-for-reduced.patch \
	file://0012-drm-edid-Remove-a-misleading-comment.patch \
	file://0013-drm-edid-s-drm_gtf_modes_for_range-drm_dmt_modes_for.patch \
	file://0014-drm-edid-Add-the-reduced-blanking-DMT-modes-to-the-D.patch \
	file://0015-drm-edid-Fix-some-comment-typos-in-the-DMT-mode-list.patch \
	file://0016-drm-edid-Do-drm_dmt_modes_for_range-for-all-range-de.patch \
	file://0017-drm-edid-Give-the-est3-mode-struct-a-real-name.patch \
	file://0018-drm-edid-Add-extra_modes.patch \
	file://0019-drm-edid-Generate-modes-from-extra_modes-for-range-d.patch \
	file://0020-drm-edid-add-missing-NULL-checks.patch \
	file://0021-drm-replace-open-coded-ARRAY_SIZE-with-macro.patch \
	file://0022-drm-edid-Add-a-workaround-for-1366x768-HD-panel.patch \
	file://0023-drm-Unify-and-fix-idr-error-handling.patch \
	file://0024-drm-edid-Try-harder-to-fix-up-base-EDID-blocks.patch \
	file://0025-drm-Store-vendor-IDs-directly-in-the-EDID-quirk-stru.patch \
	file://0026-drm-edid-fix-collision-between-two-patches-breaking-.patch \
	file://0027-drm-kms-reduce-some-messages-to-debug-level-v2.patch \
	file://0028-drm-add-drm_property_change_is_valid.patch \
	file://0029-drm-WARN-when-drm_connector_attach_property-fails.patch \
	file://0030-drm-create-struct-drm_object_properties-and-use-it.patch \
	file://0031-drm-add-generic-ioctls-to-get-set-properties-on-any-.patch \
	file://0032-drm-make-the-connector-properties-code-use-the-objec.patch \
	file://0033-drm-add-count-to-struct-drm_object_properties.patch \
	file://0034-drm-add-CRTC-properties.patch \
	file://0035-drm-Don-t-initialize-local-ret-variable-when-not-nee.patch \
	file://0036-drm-Miscellaneous-typo-fixes-and-documentation-updat.patch \
	file://0037-drm-Constify-drm_mode_config_funcs-pointer.patch \
	file://0038-drm-Make-the-CRTC-gamma_set-operation-optional.patch \
	file://0039-drm-add-bitmask-property-type.patch \
	file://0040-drm-add-plane-properties.patch \
	file://0041-drm-Constify-params-to-format_check-and-framebuffer_.patch \
	file://0042-drm-Use-stdint-types-for-consistency.patch \
	file://0043-drm-edid-quirks-ViewSonic-VA2026w.patch \
	file://0044-drm-edid-Make-the-header-fixup-threshold-tunable.patch \
	file://0045-drm-increase-DRM_OBJECT_MAX_PROPERTY-to-24.patch \
	file://0046-drm-edid-Don-t-add-inferred-modes-with-higher-resolu.patch \
	file://0047-drm-fb-helper-delay-hotplug-handling-when-partially-.patch \
	file://0048-drm-fb-helper-don-t-call-drm_crtc_helper_set_config.patch \
	file://0049-drm-remove-the-list_head-from-drm_mode_set.patch \
	file://0050-drm-edid-Fix-potential-memory-leak-in-edid_load.patch \
	file://0051-drm-fb-helper-don-t-clobber-output-routing-in-setup_.patch \
	file://0052-drm-Remove-two-unused-fields-from-struct-drm_display.patch \
	file://0053-Documentation-DocBook-DRM-framework-documentation.patch \
	file://0054-drm-remove-the-raw_edid-field-from-struct-drm_displa.patch \
	file://0055-drm-Initialize-object-type-when-using-DRM_MODE-macro.patch \
	file://0056-drm-Add-misssing-static-storage-class-specifier-in-d.patch \
	file://0057-drm-Add-EDID_QUIRK_FORCE_REDUCED_BLANKING-for-ASUS-V.patch \
	file://0058-drm-fb-helper-don-t-call-drm_helper_connector_dpms-d.patch \
	file://0059-drm-consistently-name-interlaced-modes.patch \
	file://0060-drm-edid-Add-some-bounds-checking.patch \
	file://0061-drm-edid-Add-bounds-checking-to-HDMI-VSDB-parsing.patch \
	file://0062-drm-edid-Refactor-HDMI-VSDB-detection.patch \
	file://0063-drm-edid-add-support-for-E-DDC.patch \
	file://0064-drm-edid-limit-printk-when-facing-bad-edid.patch \
	file://0065-DRM-Add-DRM-GEM-CMA-helper.patch \
	file://0066-drm-Add-NV24-and-NV42-pixel-formats.patch \
	file://0067-drm-refcnt-drm_framebuffer-v4.1.patch \
	file://0068-drm-support-for-rotated-scanout.patch \
	file://0069-drm-Export-drm_probe_ddc.patch \
	file://0070-UAPI-Refer-to-the-DRM-UAPI-headers-with-.-and-from-c.patch \
	file://0071-drm-rename-drm_dp_i2c_helper.c-to-drm_dp_helper.c.patch \
	file://0072-drm-dp-helper-extract-drm_dp_channel_eq_ok.patch \
	file://0073-drm-Be-more-paranoid-with-integer-overflows.patch \
	file://0074-drm-Constify-some-function-arguments.patch \
	file://0075-drm-Ignore-blob-propertys-in-drm_property_change_is_.patch \
	file://0076-drm-add-helper-to-sort-panels-to-the-head-of-the-con.patch \
	file://0077-drm-fb_helper-Fix-checkpatch-errors.patch \
	file://0078-drm-fb_helper-Convert-printk-to-pr_-and-dev_.patch \
	file://0079-drm-drm_fb_helper-Remove-unnecessary-braces.patch \
	file://0080-drm-get-cea-video-id-code-for-a-given-display-mode.patch \
	file://0081-drm-fix-documentation-for-drm_crtc_set_mode.patch \
	file://0082-drm-Reject-addfb2-with-undefined-flag-bits-set.patch \
	file://0083-drm-crtc-Remove-redundant-NULL-check-before-kfree.patch \
	file://0084-drm-crtc-Fix-potential-NULL-pointer-dereference.patch \
	file://0085-drm-fb_helper-Fix-potential-NULL-pointer-dereference.patch \
	file://0086-drm-add-drm_send_vblank_event-helper-v5.patch \
	file://0087-drm-extract-drm_kms_helper_hotplug_event.patch \
	file://0088-drm-handle-HPD-and-polled-connectors-separately.patch \
	file://0089-drm-run-the-hpd-irq-event-code-directly.patch \
	file://0090-drm-properly-init-reset-connector-status.patch \
	file://0091-drm-don-t-start-the-poll-engine-in-probe_single_conn.patch \
	file://0092-drm-don-t-poll-forced-connectors.patch \
	file://0093-drm-use-memchr_inv.patch \
	file://0094-drm-don-t-unnecessarily-enable-the-polling-work.patch \
	file://0095-drm-edid-tune-down-debug-message-in-parse_hdmi_vsdb.patch \
	file://0096-drm-doc-Helpers-are-not-a-Midlayer.patch \
	file://0097-drm-doc-integrate-crtc-helper-api-into-docbook.patch \
	file://0098-drm-doc-integrate-fb-helper-reference-into-docs.patch \
	file://0099-drm-doc-add-new-dp-helpers-into-drm-DocBook.patch \
	file://0100-drm-add-drm_mode_cea_vic.patch \
	file://0101-drm-remove-legacy-drm_connector_property-fxns.patch \
	file://0102-drm-edid-Update-range-descriptor-struct-for-EDID-1.4.patch \
	file://0103-drm-edid-Add-packed-attribute-to-new-gtf2-and-cvt-st.patch \
	file://0104-DRM-Add-DRM-KMS-FB-CMA-helper.patch \
	file://0105-drm-Make-the-.mode_fixup-operations-mode-argument-a-.patch \
	file://0106-drm-Constify-gem_vm_ops-pointer.patch \
	file://0107-i2c-add-Renesas-R-Car-I2C-driver.patch \
	file://0108-i2c-rcar-used-devm_request_and_ioremap-instead-of-de.patch \
	file://0109-i2c-rcar-fix-section-mismatch.patch \
	file://0110-ARM-shmobile-r8a7779-add-I2C-driver-support.patch \
	file://0111-dma-buf-mmap-support.patch \
	file://0112-common-dma-mapping-introduce-dma_get_sgtable-functio.patch \
	file://0113-dma-buf-add-vmap-interface.patch \
	file://0114-ARM-dma-mapping-add-support-for-dma_get_sgtable.patch \
	file://0115-devres-Add-devres_release.patch \
	file://0116-ARM-7376-1-clkdev-Implement-managed-clk_get.patch \
	file://0117-ARM-7534-1-clk-Make-the-managed-clk-functions-generi.patch \
	file://0118-ARM-7537-1-clk-Fix-release-in-devm_clk_put.patch \
	file://0119-drm-GEM-CMA-Split-object-creation-into-object-alloc-.patch \
	file://0120-drm-GEM-CMA-Add-DRM-PRIME-support.patch \
	file://0121-drm-Renesas-R-Car-Display-Unit-DRM-driver.patch \
	file://0122-drm-rcar-du-Use-drm_encoder_cleanup-directly-as-.des.patch \
	file://0123-drm-rcar-du-Enable-alpha-blending-support.patch \
	file://0124-drm-rcar-du-Don-t-re-reserve-hardware-plane-at-each-.patch \
	file://0125-drm-rcar-du-Fix-planes-allocation-for-multiplanar-fo.patch \
	file://0126-drm-rcar-du-Add-DRM-PRIME-support.patch \
	file://0127-drm-rcar-du-Fix-race-condition-between-page-flip-req.patch \
	file://0128-drm-rcar-du-Add-configurable-z-order-support-for-pla.patch \
	file://0129-drm-rcar-du-Support-configurable-color-keying-for-pl.patch \
	file://0130-drm-rcar-du-Update-plane-format-after-releasing-hard.patch \
	file://0131-drm-rcar-du-Fix-register-access-for-global-registers.patch \
	file://0132-drm-rcar-du-Fix-plane-index-wrap-around-for-multi-pl.patch \
	file://0133-drm-rcar-du-Enable-the-DE-signal.patch \
	file://0134-drm-rcar-du-Split-hardware-and-KMS-planes.patch \
	file://0135-drm-rcar-du-Add-support-for-the-second-CRTC.patch \
	file://0136-drm-rcar-du-Name-the-encoder-platform-data-union.patch \
	file://0137-drm-rcar-du-Fix-crash-when-disabling-an-already-disa.patch \
	file://0138-drm-rcar-du-Prepare-unprepare-clock.patch \
	file://0139-drm-rcar-du-Centralize-DU-device-core-resource-manag.patch \
	file://0140-drm-rcar-du-Reorganize-CRTC-start-stop-and-power-man.patch \
	file://0141-drm-rcar-du-Create-common-encoder-and-connector-stru.patch \
	file://0142-drm-rcar-du-Add-support-for-cloned-mode-on-DU1.patch \
	file://0143-drm-rcar-du-Add-FBDEV-emulation-support.patch \
	file://0144-ARM-local-timers-Add-A15-architected-timer-support.patch \
	file://0145-ARM-architected-timers-Add-A15-specific-sched_clock-.patch \
	file://0146-ARM-architected-timers-add-DT-support.patch \
	file://0147-ARM-architected-timers-add-support-for-UP-timer.patch \
	file://0148-ARM-architected-timers-remove-support-for-non-DT-pla.patch \
	file://0149-ARM-7451-1-arch-timer-implement-read_current_timer-a.patch \
	file://0150-ARM-7452-1-delay-allow-timer-based-delay-implementat.patch \
	file://0151-ARM-7444-1-kernel-add-arch-timer-C3STOP-feature.patch \
	file://0152-ARM-7523-1-arch_timers-enable-the-use-of-the-virtual.patch \
	file://0153-ARM-7522-1-arch_timers-register-a-time-cycle-counter.patch \
	file://0154-ARM-7538-1-delay-add-registration-mechanism-for-dela.patch \
	file://0155-ARM-7461-1-topology-Add-arch_scale_freq_power-functi.patch \
	file://0156-ARM-7462-1-topology-factorize-the-update-of-sibling-.patch \
	file://0157-ARM-7463-1-topology-Update-cpu_power-according-to-DT.patch \
	file://0158-ARM-kernel-update-topology-to-use-new-MPIDR-macros.patch \
	file://0159-ARM-kernel-enhance-MPIDR-macro-definitions.patch \
	file://0160-ARM-shmobile-Register-ARM-architected-timer.patch \
	file://0161-ARM-mm-implement-LoUIS-API-for-cache-maintenance-ops.patch \
	file://0162-ARM-kernel-update-__cpu_disable-to-use-cache-LoUIS-m.patch \
	file://0163-ARM-kernel-update-cpu_suspend-code-to-use-cache-LoUI.patch \
	file://0164-ARM-mm-rename-jump-labels-in-v7_flush_dcache_all-fun.patch \
	file://0165-ARM-7542-1-mm-fix-cache-LoUIS-API-for-xscale-and-fer.patch \
	file://0166-ARM-kernel-smp_setup_processor_id-updates.patch \
	file://0167-ARM-kernel-add-device-tree-init-map-function.patch \
	file://0168-ARM-kernel-add-cpu-logical-map-DT-init-in-setup_arch.patch \
	file://0169-ARM-kernel-add-logical-mappings-look-up.patch \
	file://0170-ARM-SoC-add-per-platform-SMP-operations.patch \
	file://0171-ARM-SoC-convert-shmobile-SMP-to-SMP-operations.patch \
	file://0172-irqchip-add-basic-infrastructure.patch \
	file://0173-irqdomain-augment-add_simple-to-allocate-descs.patch \
	file://0174-irqdomain-stop-screaming-about-preallocated-irqdescs.patch \
	file://0175-irqchip-Renesas-INTC-External-IRQ-pin-driver.patch \
	file://0176-irqchip-intc-irqpin-Cache-mapped-IRQ.patch \
	file://0177-ARM-shmobile-irq_pin-for-static-IRQ-pin-assignment.patch \
	file://0178-ARM-shmobile-INTC-External-IRQ-pin-driver-on-r8a7779.patch \
	file://0179-irqchip-intc-irqpin-Whitespace-fixes.patch \
	file://0180-irqchip-intc-irqpin-Add-force-comments.patch \
	file://0181-irqchip-intc-irqpin-Make-use-of-devm-functions.patch \
	file://0182-irqchip-intc-irqpin-GPL-header-for-platform-data.patch \
	file://0183-irqchip-Renesas-IRQC-driver.patch \
	file://0184-ARM-shmobile-Make-r8a7779-INTC-irqpin-platform-data-.patch \
	file://0185-irqchip-intc-irqpin-Initial-DT-support.patch \
	file://0186-irqchip-irqc-Add-DT-support.patch \
	file://0187-ARM-gic-use-a-private-mapping-for-CPU-target-interfa.patch \
	file://0188-ARM-GIC-fix-GIC-cpumask-initialization.patch \
	file://0189-ARM-GIC-remove-assembly-ifdefs-from-gic.h.patch \
	file://0190-ARM-OMAP-use-SGI0-to-wake-secondary-CPUs.patch \
	file://0191-ARM-7498-1-mach-shmobile-Use-SGI0-to-wake-secondary-.patch \
	file://0192-ARM-Realview-use-SGI0-to-wake-secondary-CPUs.patch \
	file://0193-ARM-7485-1-EXYNOS-use-SGI0-to-wake-secondary-CPUs.patch \
	file://0194-ARM-MSM-use-SGI0-to-wake-secondary-CPUs.patch \
	file://0195-ARM-mach-ux500-use-SGI0-to-wake-up-the-other-core.patch \
	file://0196-ARM-7536-1-smp-Formalize-an-IPI-for-wakeup.patch \
	file://0197-ARM-7571-1-SMP-add-function-arch_send_wakeup_ipi_mas.patch \
	file://0198-ARM-GIC-remove-direct-use-of-gic_raise_softirq.patch \
	file://0199-arm-add-set_handle_irq-to-register-the-parent-IRQ-co.patch \
	file://0200-ARM-GIC-set-handle_arch_irq-in-GIC-initialization.patch \
	file://0201-ARM-remove-mach-.handle_irq-for-GIC-users.patch \
	file://0202-irqchip-Move-ARM-GIC-to-drivers-irqchip.patch \
	file://0203-ARM-use-common-irqchip_init-for-GIC-init.patch \
	file://0204-irqchip-Move-ARM-gic.h-to-include-linux-irqchip-arm-.patch \
	file://0205-irqchip-fix-typo-when-moving-gic_raise_softirq.patch \
	file://0206-ARM-shmobile-defconfig-Begin-common-shmobile-defconf.patch \
	file://0207-ARM-shmobile-prune-defconfig.patch \
	file://0208-ARM-shmobile-make-defconfig-canonical.patch \
	file://0209-ARM-shmobile-Add-kzm9d-to-consolidated-defconfig.patch \
	file://0210-ARM-shmobile-Add-mackerel-to-consolidated-defconfig.patch \
	file://0211-ARM-shmobile-Add-lager-to-consolidated-defconfig.patch \
	file://0212-ARM-shmobile-Initial-r8a7790-SoC-support.patch \
	file://0213-ARM-shmobile-r8a7790-SCIF-support.patch \
	file://0214-ARM-shmobile-r8a7790-IRQC-support.patch \
	file://0215-ARM-shmobile-r8a7790-PFC-support.patch \
	file://0216-ARM-shmobile-r8a7790-SoC-64-bit-DT-support.patch \
	file://0217-ARM-shmobile-Add-second-I-O-range-for-r8a7790-PFC.patch \
	file://0218-ARM-shmobile-force-enable-of-r8a7790-arch-timer.patch \
	file://0219-Documentation-pinctrl-add-missing-spi0_0-grp-in-exam.patch \
	file://0220-pinctrl-mark-const-init-data-with-__initconst-instea.patch \
	file://0221-pinctrl-implement-pinctrl-deferred-probing.patch \
	file://0222-pinctrl-fix-a-minor-harmless-typo.patch \
	file://0223-Documentation-pinctrl.txt-Fix-some-misspelled-macros.patch \
	file://0224-trivial-pinctrl-core-remove-extraneous-code-lines.patch \
	file://0225-pinctrl-document-semantics-vs-GPIO.patch \
	file://0226-pinctrl-Fix-potential-memory-leak-in-pinctrl_registe.patch \
	file://0227-pinctrl-fix-missing-unlock-on-error-in-pinctrl_group.patch \
	file://0228-pinctrl-fix-comment-mistake.patch \
	file://0229-pinctrl-skip-deferral-of-hogs.patch \
	file://0230-pinctrl-core-get-devname-from-pinctrl_dev.patch \
	file://0231-drivers-pinctrl-grab-default-handles-from-device-cor.patch \
	file://0232-gpio-add-flags-to-export-GPIOs-when-requesting.patch \
	file://0233-gpio-Move-DT-support-code-into-drivers-gpio.patch \
	file://0234-gpiolib-Implement-devm_gpio_request_one.patch \
	file://0235-pinctrl-allow-pctldevs-to-decode-pin-config-in-debug.patch \
	file://0236-gpio-Adjust-of_xlate-API-to-support-multiple-GPIO-ch.patch \
	file://0237-gpiolib-quiet-gpiochip_add-boot-message-noise.patch \
	file://0238-gpiolib-Remove-const-from-data-argument-of-gpiochip_.patch \
	file://0239-gpio-of-fix-a-typo-of-comment-message.patch \
	file://0240-gpio-propagate-of_parse_phandle_with_args-errors.patch \
	file://0241-gpiolib-Defer-failed-gpio-requests-by-default.patch \
	file://0242-gpio-of_get_named_gpio_flags-return-EPROBE_DEFER-if-.patch \
	file://0243-gpio-Fix-debug-message-in-of_get_named_gpio_flags.patch \
	file://0244-gpiolib-Use-seq_file-s-iterator-interface.patch \
	file://0245-gpio-Document-device_node-s-det_debounce.patch \
	file://0246-gpiolib-Refactor-gpio_export.patch \
	file://0247-gpiolib-add-gpio-get-direction-callback-support.patch \
	file://0248-gpiolib-unlock-on-error-in-gpio_export.patch \
	file://0249-gpiolib-provide-provision-to-register-pin-ranges.patch \
	file://0250-gpiolib-fix-up-function-prototypes-etc.patch \
	file://0251-gpiolib-of-staticize-the-pin-range-calls.patch \
	file://0252-gpiolib-remove-duplicate-pin-range-code.patch \
	file://0253-gpiolib-call-pin-removal-in-chip-removal-function.patch \
	file://0254-gpiolib-separation-of-pin-concerns.patch \
	file://0255-gpiolib-iron-out-include-ladder-mistakes.patch \
	file://0256-gpiolib-let-gpiochip_add_pin_range-specify-offset.patch \
	file://0257-gpiolib-rename-find_pinctrl_.patch \
	file://0258-gpiolib-return-any-error-code-from-range-creation.patch \
	file://0259-gpiolib-rename-pin-range-arguments.patch \
	file://0260-gpiolib-Fix-use-after-free-in-gpiochip_add_pin_range.patch \
	file://0261-gpio-use-pinctrl-device-name-for-add-range.patch \
	file://0262-gpio-fix-warning-of-struct-gpio_chip-declaration.patch \
	file://0263-gpio-devm_gpio_-support-should-not-depend-on-GPIOLIB.patch \
	file://0264-gpiolib-remove-gpiochip_reserve.patch \
	file://0265-gpiolib-add-missing-braces-in-gpio_direction_show.patch \
	file://0266-gpiolib-link-all-gpio_chips-using-a-list.patch \
	file://0267-gpiolib-use-gpio_chips-list-in-gpiolib_sysfs_init.patch \
	file://0268-pinctrl-generic-dump-pin-configuration.patch \
	file://0269-Revert-pinctrl-remove-pinctrl_remove_gpio_range.patch \
	file://0270-pinctrl-Declare-operation-structures-as-const.patch \
	file://0271-pinctrl-generic-Fix-compilation-error.patch \
	file://0272-sh-pfc-Split-out-gpio-chip-support.patch \
	file://0273-sh-pfc-Make-gpio-chip-support-optional-where-possibl.patch \
	file://0274-sh-pfc-Kill-off-unused-pinmux-bias-flags.patch \
	file://0275-sh-pfc-Verify-pin-type-encoding-size-at-build-time.patch \
	file://0276-sh-pfc-Shuffle-PFC-support-core.patch \
	file://0277-sh-pfc-Dumb-GPIO-stringification.patch \
	file://0278-sh-pfc-Rudimentary-pinctrl-backed-GPIO-support.patch \
	file://0279-sh-pfc-pinctrl-legacy-function-support.patch \
	file://0280-sh-pfc-Make-pr_fmt-consistent-across-pfc-drivers.patch \
	file://0281-sh-pfc-Export-pinctrl-binding-init-symbol.patch \
	file://0282-sh-pfc-Ignore-pinmux-GPIOs-with-invalid-enum-IDs.patch \
	file://0283-sh-pfc-pinctrl-legacy-group-support.patch \
	file://0284-sh-pfc-Prefer-DRV_NAME-over-KBUILD_MODNAME.patch \
	file://0285-sh-pfc-pin-config-get-set-support.patch \
	file://0286-sh-pfc-Build-fix-for-pinctrl_remove_gpio_range-chang.patch \
	file://0287-sh-pfc-Fix-up-init-ordering-mess.patch \
	file://0288-sh-pfc-Release-spinlock-in-sh_pfc_gpio_request_enabl.patch \
	file://0289-sh-pfc-Fix-up-GPIO-mux-type-reconfig-case.patch \
	file://0290-sh-pfc-Error-out-on-pinctrl-init-resolution-failure.patch \
	file://0291-ARM-shmobile-move-custom-gpio-functions-to-sh-gpio.h.patch \
	file://0292-Drivers-misc-remove-__dev-attributes.patch \
	file://0293-sh-sh7723-Rename-GPIO_FN_SIUOSPD-to-GPIO_FN_SIUAOSPD.patch \
	file://0294-sh-sh7757-Fix-GPIO_FN_ET0_MDIO-and-GPIO_FN_ET1_MDIO-.patch \
	file://0295-sh-sh7786-Fix-port-E-G-and-J-GPIOs.patch \
	file://0296-sh-sh7786-Fix-last-GPIO-index.patch \
	file://0297-sh-shx3-Fix-last-GPIO-index.patch \
	file://0298-sh-pfc-Split-platform-data-from-the-sh_pfc-structure.patch \
	file://0299-sh-pfc-Move-private-definitions-and-declarations-to-.patch \
	file://0300-sh-pfc-Merge-PFC-core-and-pinctrl.patch \
	file://0301-sh-pfc-Merge-PFC-core-and-gpio.patch \
	file://0302-sh-pfc-Move-platform-device-and-driver-to-the-core.patch \
	file://0303-sh-pfc-Use-devm_kzalloc.patch \
	file://0304-sh-pfc-Use-devm_ioremap_nocache.patch \
	file://0305-sh-pfc-Let-the-compiler-decide-whether-to-inline-fun.patch \
	file://0306-sh-pfc-Remove-check-for-impossible-error-condition.patch \
	file://0307-sh-pfc-Sort-headers-alphabetically.patch \
	file://0308-sh-pfc-Use-sh_pfc_-namespace-prefix-through-the-whol.patch \
	file://0309-sh-pfc-Split-platform-device-and-platform-driver-reg.patch \
	file://0310-sh-pfc-Support-passing-resources-through-platform-de.patch \
	file://0311-ARM-shmobile-Select-PINCTRL.patch \
	file://0312-ARM-shmobile-r8a7740-Register-PFC-platform-device.patch \
	file://0313-ARM-shmobile-r8a7779-Register-PFC-platform-device.patch \
	file://0314-ARM-shmobile-sh7372-Register-PFC-platform-device.patch \
	file://0315-ARM-shmobile-sh73a0-Register-PFC-platform-device.patch \
	file://0316-ARM-shmobile-r8a7740-Add-pin-control-resources.patch \
	file://0317-ARM-shmobile-sh7372-Add-pin-control-resources.patch \
	file://0318-ARM-shmobile-sh73a0-Add-pin-control-resources.patch \
	file://0319-sh-Add-PFC-platform-device-registration-helper-funct.patch \
	file://0320-sh-sh7203-Register-PFC-platform-device.patch \
	file://0321-sh-sh7720-Register-PFC-platform-device.patch \
	file://0322-sh-sh7722-Register-PFC-platform-device.patch \
	file://0323-sh-sh7723-Register-PFC-platform-device.patch \
	file://0324-sh-sh7724-Register-PFC-platform-device.patch \
	file://0325-sh-sh7757-Register-PFC-platform-device.patch \
	file://0326-sh-sh7785-Register-PFC-platform-device.patch \
	file://0327-sh-sh7786-Register-PFC-platform-device.patch \
	file://0328-sh-shx3-Register-PFC-platform-device.patch \
	file://0329-sh-pfc-Remove-platform-device-registration.patch \
	file://0330-sh-pfc-Remove-unused-resource-and-num_resources-plat.patch \
	file://0331-sh-pfc-Move-driver-from-drivers-sh-to-drivers-pinctr.patch \
	file://0332-sh-pfc-Support-pinmux-info-in-driver-data-instead-of.patch \
	file://0333-sh-pfc-Add-r8a7740-pinmux-support.patch \
	file://0334-ARM-shmobile-r8a7779-PFC-rename-PENCx-USB_PENCx.patch \
	file://0335-sh-pfc-Add-r8a7779-pinmux-support.patch \
	file://0336-sh-pfc-Add-sh7372-pinmux-support.patch \
	file://0337-sh-pfc-Add-sh73a0-pinmux-support.patch \
	file://0338-sh-pfc-Add-sh7203-pinmux-support.patch \
	file://0339-sh-pfc-Add-sh7264-pinmux-support.patch \
	file://0340-sh-pfc-Add-sh7269-pinmux-support.patch \
	file://0341-sh-pfc-Add-sh7720-pinmux-support.patch \
	file://0342-sh-pfc-Add-sh7722-pinmux-support.patch \
	file://0343-sh-pfc-Add-sh7723-pinmux-support.patch \
	file://0344-sh-pfc-Add-sh7724-pinmux-support.patch \
	file://0345-sh-pfc-Add-sh7734-pinmux-support.patch \
	file://0346-sh-pfc-Add-sh7757-pinmux-support.patch \
	file://0347-sh-pfc-Add-sh7785-pinmux-support.patch \
	file://0348-sh-pfc-Add-sh7786-pinmux-support.patch \
	file://0349-sh-pfc-Add-shx3-pinmux-support.patch \
	file://0350-ARM-shmobile-Remove-SH7367-support.patch \
	file://0351-ARM-shmobile-Remove-SH7377-support.patch \
	file://0352-ARM-shmobile-r8a7740-Use-driver-provided-pinmux-info.patch \
	file://0353-ARM-shmobile-r8a7779-Use-driver-provided-pinmux-info.patch \
	file://0354-ARM-shmobile-sh7372-Use-driver-provided-pinmux-info.patch \
	file://0355-ARM-shmobile-sh73a0-Use-driver-provided-pinmux-info.patch \
	file://0356-sh-sh7203-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0357-sh-sh7720-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0358-sh-sh7722-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0359-sh-sh7723-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0360-sh-sh7724-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0361-sh-sh7757-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0362-sh-sh7785-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0363-sh-sh7786-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0364-sh-shx3-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0365-sh-Remove-unused-sh_pfc_register_info-function.patch \
	file://0366-sh-pfc-Remove-pinmux_info-definition.patch \
	file://0367-sh-pfc-Move-sh_pfc.h-from-include-linux-to-driver-di.patch \
	file://0368-sh-pfc-Declare-operation-structures-as-const.patch \
	file://0369-sh-pfc-Don-t-define-the-per-device-pinctrl-struct-in.patch \
	file://0370-sh-pfc-Fix-a-typo-and-simplify-a-definition-on-sh73a.patch \
	file://0371-sh-pfc-Drop-the-sh_pfc_pinctrl-spinlock.patch \
	file://0372-sh-pfc-Don-t-take-the-sh_pfc-spinlock-in-sh_pfc_map_.patch \
	file://0373-sh-pfc-Use-GPIO_FN-instead-of-PINMUX_GPIO-where-poss.patch \
	file://0374-sh-pfc-Replace-first_gpio-and-last_gpio-with-nr_gpio.patch \
	file://0375-sh-pfc-Replace-SoC-info-data-and-mark-ranges-with-a-.patch \
	file://0376-sh-pfc-Remove-unused-sh_pfc_soc_info-reserved_id-fie.patch \
	file://0377-sh-pfc-Initialize-pinmux_gpio-flags-statically.patch \
	file://0378-sh-pfc-Make-struct-pinmux_gpio-enum_id-field-const.patch \
	file://0379-sh-pfc-Shrink-the-pinctrl-GPIO-range-to-include-real.patch \
	file://0380-sh-pfc-Don-t-needlessly-check-GPIO-type-in-sh_gpio_f.patch \
	file://0381-sh-pfc-Split-pins-and-functions-definition-tables.patch \
	file://0382-sh-pfc-Split-pins-and-functions-into-separate-gpio_c.patch \
	file://0383-sh-pfc-Rename-struct-pinmux_pin-to-struct-sh_pfc_pin.patch \
	file://0384-sh-pfc-Look-up-IRQ-table-entries-by-GPIO-number.patch \
	file://0385-sh-pfc-Share-the-PORT_10_REV-PORT_32-and-PORT_32_REV.patch \
	file://0386-sh-pfc-Use-pinmux-identifiers-in-the-pin-muxing-API.patch \
	file://0387-sh-pfc-Simplify-the-sh_pfc_gpio_is_pin-logic.patch \
	file://0388-sh-pfc-Add-function-to-retrieve-a-pin-instance-from-.patch \
	file://0389-sh-pfc-Replace-pinctrl_add_gpio_range-with-gpiochip_.patch \
	file://0390-sh-pfc-Add-support-for-sparse-pin-numbers.patch \
	file://0391-ARM-shmobile-ag5evm-Use-gpio_request_one.patch \
	file://0392-ARM-shmobile-kota2-Use-gpio_request_one.patch \
	file://0393-ARM-shmobile-kzm9g-Use-gpio_request_one.patch \
	file://0394-ARM-shmobile-sh73a0-Support-sparse-GPIO-numbers.patch \
	file://0395-ARM-shmobile-ap4evb-Use-gpio_request_one.patch \
	file://0396-ARM-shmobile-use-common-extra-gpio-functions-on-ap4e.patch \
	file://0397-ARM-shmobile-ap4-evb-Replace-GPIO_PORTx-enum-with-GP.patch \
	file://0398-ARM-shmobile-armadillo800eva-Use-gpio_request_one.patch \
	file://0399-ARM-shmobile-armadillo800eva-Use-gpio_set_value-to-s.patch \
	file://0400-ARM-shmobile-armadillo-Replace-GPIO_PORTx-enum-with-.patch \
	file://0401-ARM-shmobile-bonito-Use-gpio_request_one.patch \
	file://0402-ARM-shmobile-bonito-Replace-GPIO_PORTx-enum-with-GPI.patch \
	file://0403-ARM-shmobile-mackerel-Use-gpio_request_one.patch \
	file://0404-ARM-shmobile-use-common-extra-gpio-functions-on-Mack.patch \
	file://0405-ARM-shmobile-mackerel-Replace-GPIO_PORTx-enum-with-G.patch \
	file://0406-sh-pfc-Expose-real-groups-and-functions-in-pinctrl-p.patch \
	file://0407-sh-pfc-Fix-return-value-check-in-sh_pfc_register_pin.patch \
	file://0408-sh-pfc-Move-GPIO-registers-access-functions-to-gpio..patch \
	file://0409-sh-pfc-Don-t-map-data-registers-individually.patch \
	file://0410-sh-pfc-Drop-unused-support-for-1-1-physical-to-virtu.patch \
	file://0411-sh-pfc-Don-t-modify-pinmux_data_reg-SoC-data.patch \
	file://0412-sh-pfc-Don-t-modify-sh_pfc_pin-SoC-data.patch \
	file://0413-sh-pfc-Remove-configuration-dry-run-and-free.patch \
	file://0414-sh-pfc-Constify-all-SoC-data.patch \
	file://0415-sh-pfc-Use-proper-error-codes.patch \
	file://0416-sh-pfc-Implement-generic-pinconf-support.patch \
	file://0417-sh-pfc-Merge-sh_pfc_reconfig_pin-into-sh_pfc_gpio_se.patch \
	file://0418-sh-pfc-Clean-up-pin-configuration-type-handling.patch \
	file://0419-sh-pfc-Convert-message-printing-from-pr_-to-dev_.patch \
	file://0420-sh-pfc-Return-an-error-if-a-pin-doesn-t-support-the-.patch \
	file://0421-sh-pfc-r8a7779-Add-DU-pin-groups-and-functions.patch \
	file://0422-sh-pfc-r8a7779-Add-SDHI-and-MMCIF-pin-groups-and-fun.patch \
	file://0423-sh-pfc-r8a7779-Add-SCIF-pin-groups-and-functions.patch \
	file://0424-sh-pfc-r8a7779-Add-HSPI-pin-groups-and-functions.patch \
	file://0425-sh-pfc-r8a7779-Add-USB0-and-USB1-PENC-pinmux-support.patch \
	file://0426-sh-pfc-r8a7779-Add-USB-pin-groups-and-functions.patch \
	file://0427-sh-pfc-r8a7779-Add-LBSC-pin-groups-and-functions.patch \
	file://0428-sh-pfc-r8a7779-Add-INTC-pin-groups-and-functions.patch \
	file://0429-ARM-shmobile-marzen-Register-pinctrl-mappings-for-SD.patch \
	file://0430-ARM-shmobile-marzen-Register-pinctrl-mappings-for-SC.patch \
	file://0431-ARM-shmobile-marzen-Register-pinctrl-mappings-for-LB.patch \
	file://0432-ARM-shmobile-marzen-Register-pinctrl-mappings-for-IN.patch \
	file://0433-sh-pfc-r8a7779-Remove-DU1_DOTCLKOUT1-GPIO.patch \
	file://0434-sh-pfc-r8a7779-Remove-SDHI-and-MMCIF-function-GPIOS.patch \
	file://0435-sh-pfc-r8a7779-Remove-SCIF-function-GPIOS.patch \
	file://0436-sh-pfc-r8a7779-Remove-HSPI-function-GPIOS.patch \
	file://0437-sh-pfc-r8a7779-Remove-USB-function-GPIOS.patch \
	file://0438-sh-pfc-r8a7779-Remove-LBSC-function-GPIOS.patch \
	file://0439-sh-pfc-r8a7779-Remove-INTC-function-GPIOS.patch \
	file://0440-ARM-shmobile-r8a7779-Remove-DU-function-GPIOs.patch \
	file://0441-ARM-shmobile-r8a7779-Remove-SDHI-and-MMCIF-function-.patch \
	file://0442-ARM-shmobile-r8a7779-Remove-SCIF-function-GPIOs.patch \
	file://0443-ARM-shmobile-r8a7779-Remove-HSPI-function-GPIOs.patch \
	file://0444-ARM-shmobile-r8a7779-Remove-USB-function-GPIOs.patch \
	file://0445-ARM-shmobile-r8a7779-Remove-LBSC-function-GPIOs.patch \
	file://0446-ARM-shmobile-r8a7779-Remove-INTC-function-GPIOs.patch \
	file://0447-gpio-Renesas-R-Car-GPIO-driver-V3.patch \
	file://0448-sh-pfc-r8a7779-Remove-function-GPIOs.patch \
	file://0449-sh-pfc-r8a7779-Don-t-use-GPIO-enum-entries.patch \
	file://0450-ARM-shmobile-r8a7779-Remove-all-GPIOs.patch \
	file://0451-ARM-shmobile-add-gic_iid-macro-for-ICCIAR-interrupt-.patch \
	file://0452-gpio-rcar-Add-pinctrl-support.patch \
	file://0453-sh-pfc-Make-function-GPIOs-support-optional.patch \
	file://0454-sh-pfc-Make-GPIO-support-optional.patch \
	file://0455-sh-pfc-Skip-gpiochip-registration-when-no-GPIO-resou.patch \
	file://0456-sh-pfc-Configure-pins-as-GPIOs-at-request-time-when-.patch \
	file://0457-ARM-shmobile-r8a7779-Register-GPIO-devices.patch \
	file://0458-sh-pfc-r8a7779-Remove-GPIO-data.patch \
	file://0459-ARM-shmobile-marzen-Add-GPIO-LEDs.patch \
	file://0460-sh-pfc-r8a7779-Split-DU-input-and-output-pixel-clock.patch \
	file://0461-sh-pfc-Initial-r8a7790-PFC-support.patch \
	file://0462-sh-pfc-Remove-dependency-on-GPIOLIB.patch \
	file://0463-gpio-rcar-Add-RCAR_GP_PIN-macro.patch \
	file://0464-sh-pfc-r8a7790-Add-ETH-pin-groups-and-functions.patch \
	file://0465-sh-pfc-r8a7790-Add-INTC-pin-groups-and-functions.patch \
	file://0466-sh-pfc-r8a7790-Add-SCIF-SCIFA-and-SCIFB-pin-groups-a.patch \
	file://0467-sh-pfc-r8a7790-Remove-GPIO-data.patch \
	file://0468-sh-pfc-r8a7790-Remove-function-GPIOs.patch \
	file://0469-sh-pfc-r8a7790-Don-t-use-GPIO-enum-entries.patch \
	file://0470-ARM-shmobile-r8a7790-Register-GPIO-devices.patch \
	file://0471-ARM-shmobile-r8a7790-Remove-all-GPIOs.patch \
	file://0472-ARM-shmobile-Initial-r8a7790-Lager-board-support.patch \
	file://0473-ARM-shmobile-use-r8a7790-timer-setup-code-on-Lager.patch \
	file://0474-ARM-shmobile-lager-Initialize-pinmux.patch \
	file://0475-h2-bsp-v-0-2-0.patch \
        "

S = "${WORKDIR}/git"

FILESEXTRAPATHS_prepend_lager := "${THISDIR}/${PN}:"

KERNEL_DEFCONFIG = "shmobile_defconfig"

do_configure_prepend() {
        install -m 0644 ${S}/arch/${ARCH}/configs/${KERNEL_DEFCONFIG} ${WORKDIR}/defconfig || die "No default configuration for ${MACHINE} / ${KERNEL_DEFCONFIG} available."
}
