require linux.inc
require linux-dtb.inc

DESCRIPTION = "Linux kernel for the lager board"
COMPATIBLE_MACHINE = "lager"

PR = "r0"
PV_append = "+git${SRCREV}"

SRCREV = "4938ff7a961bcf44ef53c4a928f6cf9c4e6ddb4d"
SRC_URI = "git://git.yoctoproject.org/linux-yocto-3.4.git;protocol=git;branch=ltsi \
        file://0001-ARM-local-timers-Add-A15-architected-timer-support.patch \
        file://0002-ARM-architected-timers-Add-A15-specific-sched_clock-.patch \
        file://0003-ARM-architected-timers-add-DT-support.patch \
        file://0004-ARM-architected-timers-add-support-for-UP-timer.patch \
        file://0005-ARM-architected-timers-remove-support-for-non-DT-pla.patch \
        file://0006-ARM-7451-1-arch-timer-implement-read_current_timer-a.patch \
        file://0007-ARM-7452-1-delay-allow-timer-based-delay-implementat.patch \
        file://0008-ARM-7444-1-kernel-add-arch-timer-C3STOP-feature.patch \
        file://0009-ARM-7523-1-arch_timers-enable-the-use-of-the-virtual.patch \
        file://0010-ARM-7522-1-arch_timers-register-a-time-cycle-counter.patch \
        file://0011-ARM-7538-1-delay-add-registration-mechanism-for-dela.patch \
        file://0012-ARM-7461-1-topology-Add-arch_scale_freq_power-functi.patch \
        file://0013-ARM-7462-1-topology-factorize-the-update-of-sibling-.patch \
        file://0014-ARM-7463-1-topology-Update-cpu_power-according-to-DT.patch \
        file://0015-ARM-kernel-update-topology-to-use-new-MPIDR-macros.patch \
        file://0016-ARM-kernel-enhance-MPIDR-macro-definitions.patch \
        file://0017-ARM-shmobile-Register-ARM-architected-timer.patch \
        file://0018-ARM-mm-implement-LoUIS-API-for-cache-maintenance-ops.patch \
        file://0019-ARM-kernel-update-__cpu_disable-to-use-cache-LoUIS-m.patch \
        file://0020-ARM-kernel-update-cpu_suspend-code-to-use-cache-LoUI.patch \
        file://0021-ARM-mm-rename-jump-labels-in-v7_flush_dcache_all-fun.patch \
        file://0022-ARM-7542-1-mm-fix-cache-LoUIS-API-for-xscale-and-fer.patch \
        file://0023-ARM-gic-use-a-private-mapping-for-CPU-target-interfa.patch \
        file://0024-ARM-kernel-smp_setup_processor_id-updates.patch \
        file://0025-ARM-kernel-add-device-tree-init-map-function.patch \
        file://0026-ARM-kernel-add-cpu-logical-map-DT-init-in-setup_arch.patch \
        file://0027-ARM-kernel-add-logical-mappings-look-up.patch \
        file://0028-i2c-add-Renesas-R-Car-I2C-driver.patch \
        file://0029-i2c-rcar-used-devm_request_and_ioremap-instead-of-de.patch \
        file://0030-i2c-rcar-fix-section-mismatch.patch \
        file://0031-ARM-shmobile-r8a7779-add-I2C-driver-support.patch \
        file://0032-drm-Move-drm_format_num_planes-to-drm_crtc.c.patch \
        file://0033-drm-Add-drm_format_plane_cpp-utility-function.patch \
        file://0034-drm-Add-drm_format_-horz-vert-_chroma_subsampling-ut.patch \
        file://0035-drm-Add-sanity-checks-to-framebuffer-creation.patch \
        file://0036-drm-Fix-EDID-color-format-parsing.patch \
        file://0037-drm-Parse-color-format-information-in-CEA-blocks.patch \
        file://0038-drm-add-the-VIC-number-to-the-CEA-EDID-modes.patch \
        file://0039-drm-add-DRM_MODE_FLAG_DBLCLK-to-CEA-modes-requiring-.patch \
        file://0040-drm-edid-Document-drm_mode_find_dmt.patch \
        file://0041-drm-edid-Rewrite-drm_mode_find_dmt-search-loop.patch \
        file://0042-drm-edid-Allow-drm_mode_find_dmt-to-hunt-for-reduced.patch \
        file://0043-drm-edid-Remove-a-misleading-comment.patch \
        file://0044-drm-edid-s-drm_gtf_modes_for_range-drm_dmt_modes_for.patch \
        file://0045-drm-edid-Add-the-reduced-blanking-DMT-modes-to-the-D.patch \
        file://0046-drm-edid-Fix-some-comment-typos-in-the-DMT-mode-list.patch \
        file://0047-drm-edid-Do-drm_dmt_modes_for_range-for-all-range-de.patch \
        file://0048-drm-edid-Give-the-est3-mode-struct-a-real-name.patch \
        file://0049-drm-edid-Add-extra_modes.patch \
        file://0050-drm-edid-Generate-modes-from-extra_modes-for-range-d.patch \
        file://0051-drm-edid-add-missing-NULL-checks.patch \
        file://0052-drm-replace-open-coded-ARRAY_SIZE-with-macro.patch \
        file://0053-drm-edid-Add-a-workaround-for-1366x768-HD-panel.patch \
        file://0054-drm-Unify-and-fix-idr-error-handling.patch \
        file://0055-drm-edid-Try-harder-to-fix-up-base-EDID-blocks.patch \
        file://0056-drm-Store-vendor-IDs-directly-in-the-EDID-quirk-stru.patch \
        file://0057-drm-edid-fix-collision-between-two-patches-breaking-.patch \
        file://0058-drm-kms-reduce-some-messages-to-debug-level-v2.patch \
        file://0059-drm-add-drm_property_change_is_valid.patch \
        file://0060-drm-WARN-when-drm_connector_attach_property-fails.patch \
        file://0061-drm-create-struct-drm_object_properties-and-use-it.patch \
        file://0062-drm-add-generic-ioctls-to-get-set-properties-on-any-.patch \
        file://0063-drm-make-the-connector-properties-code-use-the-objec.patch \
        file://0064-drm-add-count-to-struct-drm_object_properties.patch \
        file://0065-drm-add-CRTC-properties.patch \
        file://0066-drm-Don-t-initialize-local-ret-variable-when-not-nee.patch \
        file://0067-drm-Miscellaneous-typo-fixes-and-documentation-updat.patch \
        file://0068-drm-Constify-drm_mode_config_funcs-pointer.patch \
        file://0069-drm-Make-the-CRTC-gamma_set-operation-optional.patch \
        file://0070-drm-add-bitmask-property-type.patch \
        file://0071-drm-add-plane-properties.patch \
        file://0072-drm-Constify-params-to-format_check-and-framebuffer_.patch \
        file://0073-drm-Use-stdint-types-for-consistency.patch \
        file://0074-drm-edid-quirks-ViewSonic-VA2026w.patch \
        file://0075-drm-edid-Make-the-header-fixup-threshold-tunable.patch \
        file://0076-drm-increase-DRM_OBJECT_MAX_PROPERTY-to-24.patch \
        file://0077-drm-edid-Don-t-add-inferred-modes-with-higher-resolu.patch \
        file://0078-drm-fb-helper-delay-hotplug-handling-when-partially-.patch \
        file://0079-drm-fb-helper-don-t-call-drm_crtc_helper_set_config.patch \
        file://0080-drm-remove-the-list_head-from-drm_mode_set.patch \
        file://0081-drm-edid-Fix-potential-memory-leak-in-edid_load.patch \
        file://0082-drm-fb-helper-don-t-clobber-output-routing-in-setup_.patch \
        file://0083-drm-Remove-two-unused-fields-from-struct-drm_display.patch \
        file://0084-Documentation-DocBook-DRM-framework-documentation.patch \
        file://0085-drm-remove-the-raw_edid-field-from-struct-drm_displa.patch \
        file://0086-drm-Initialize-object-type-when-using-DRM_MODE-macro.patch \
        file://0087-drm-Add-misssing-static-storage-class-specifier-in-d.patch \
        file://0088-drm-Add-EDID_QUIRK_FORCE_REDUCED_BLANKING-for-ASUS-V.patch \
        file://0089-drm-fb-helper-don-t-call-drm_helper_connector_dpms-d.patch \
        file://0090-drm-consistently-name-interlaced-modes.patch \
        file://0091-drm-edid-Add-some-bounds-checking.patch \
        file://0092-drm-edid-Add-bounds-checking-to-HDMI-VSDB-parsing.patch \
        file://0093-drm-edid-Refactor-HDMI-VSDB-detection.patch \
        file://0094-drm-edid-add-support-for-E-DDC.patch \
        file://0095-drm-edid-limit-printk-when-facing-bad-edid.patch \
        file://0096-DRM-Add-DRM-GEM-CMA-helper.patch \
        file://0097-drm-Add-NV24-and-NV42-pixel-formats.patch \
        file://0098-drm-refcnt-drm_framebuffer-v4.1.patch \
        file://0099-drm-support-for-rotated-scanout.patch \
        file://0100-drm-Export-drm_probe_ddc.patch \
        file://0101-UAPI-Refer-to-the-DRM-UAPI-headers-with-.-and-from-c.patch \
        file://0102-drm-rename-drm_dp_i2c_helper.c-to-drm_dp_helper.c.patch \
        file://0103-drm-dp-helper-extract-drm_dp_channel_eq_ok.patch \
        file://0104-drm-Be-more-paranoid-with-integer-overflows.patch \
        file://0105-drm-Constify-some-function-arguments.patch \
        file://0106-drm-Ignore-blob-propertys-in-drm_property_change_is_.patch \
        file://0107-drm-add-helper-to-sort-panels-to-the-head-of-the-con.patch \
        file://0108-drm-fb_helper-Fix-checkpatch-errors.patch \
        file://0109-drm-fb_helper-Convert-printk-to-pr_-and-dev_.patch \
        file://0110-drm-drm_fb_helper-Remove-unnecessary-braces.patch \
        file://0111-drm-get-cea-video-id-code-for-a-given-display-mode.patch \
        file://0112-drm-fix-documentation-for-drm_crtc_set_mode.patch \
        file://0113-drm-Reject-addfb2-with-undefined-flag-bits-set.patch \
        file://0114-drm-crtc-Remove-redundant-NULL-check-before-kfree.patch \
        file://0115-drm-crtc-Fix-potential-NULL-pointer-dereference.patch \
        file://0116-drm-fb_helper-Fix-potential-NULL-pointer-dereference.patch \
        file://0117-drm-add-drm_send_vblank_event-helper-v5.patch \
        file://0118-drm-extract-drm_kms_helper_hotplug_event.patch \
        file://0119-drm-handle-HPD-and-polled-connectors-separately.patch \
        file://0120-drm-run-the-hpd-irq-event-code-directly.patch \
        file://0121-drm-properly-init-reset-connector-status.patch \
        file://0122-drm-don-t-start-the-poll-engine-in-probe_single_conn.patch \
        file://0123-drm-don-t-poll-forced-connectors.patch \
        file://0124-drm-use-memchr_inv.patch \
        file://0125-drm-don-t-unnecessarily-enable-the-polling-work.patch \
        file://0126-drm-edid-tune-down-debug-message-in-parse_hdmi_vsdb.patch \
        file://0127-drm-doc-Helpers-are-not-a-Midlayer.patch \
        file://0128-drm-doc-integrate-crtc-helper-api-into-docbook.patch \
        file://0129-drm-doc-integrate-fb-helper-reference-into-docs.patch \
        file://0130-drm-doc-add-new-dp-helpers-into-drm-DocBook.patch \
        file://0131-drm-add-drm_mode_cea_vic.patch \
        file://0132-drm-remove-legacy-drm_connector_property-fxns.patch \
        file://0133-drm-edid-Update-range-descriptor-struct-for-EDID-1.4.patch \
        file://0134-drm-edid-Add-packed-attribute-to-new-gtf2-and-cvt-st.patch \
        file://0135-DRM-Add-DRM-KMS-FB-CMA-helper.patch \
        file://0136-drm-Make-the-.mode_fixup-operations-mode-argument-a-.patch \
        file://0137-drm-Constify-gem_vm_ops-pointer.patch \
        file://0138-dma-buf-mmap-support.patch \
        file://0139-common-dma-mapping-introduce-dma_get_sgtable-functio.patch \
        file://0140-dma-buf-add-vmap-interface.patch \
        file://0141-ARM-dma-mapping-add-support-for-dma_get_sgtable.patch \
        file://0142-devres-Add-devres_release.patch \
        file://0143-ARM-7376-1-clkdev-Implement-managed-clk_get.patch \
        file://0144-ARM-7534-1-clk-Make-the-managed-clk-functions-generi.patch \
        file://0145-ARM-7537-1-clk-Fix-release-in-devm_clk_put.patch \
        file://0146-drm-GEM-CMA-Split-object-creation-into-object-alloc-.patch \
        file://0147-drm-GEM-CMA-Add-DRM-PRIME-support.patch \
        file://0148-drm-Renesas-R-Car-Display-Unit-DRM-driver.patch \
        file://0149-drm-rcar-du-Use-drm_encoder_cleanup-directly-as-.des.patch \
        file://0150-drm-rcar-du-Enable-alpha-blending-support.patch \
        file://0151-drm-rcar-du-Don-t-re-reserve-hardware-plane-at-each-.patch \
        file://0152-drm-rcar-du-Fix-planes-allocation-for-multiplanar-fo.patch \
        file://0153-drm-rcar-du-Add-DRM-PRIME-support.patch \
        file://0154-drm-rcar-du-Fix-race-condition-between-page-flip-req.patch \
        file://0155-drm-rcar-du-Add-configurable-z-order-support-for-pla.patch \
        file://0156-drm-rcar-du-Support-configurable-color-keying-for-pl.patch \
        file://0157-drm-rcar-du-Update-plane-format-after-releasing-hard.patch \
        file://0158-drm-rcar-du-Fix-register-access-for-global-registers.patch \
        file://0159-drm-rcar-du-Fix-plane-index-wrap-around-for-multi-pl.patch \
        file://0160-drm-rcar-du-Enable-the-DE-signal.patch \
        file://0161-drm-rcar-du-Split-hardware-and-KMS-planes.patch \
        file://0162-drm-rcar-du-Add-support-for-the-second-CRTC.patch \
        file://0163-drm-rcar-du-Name-the-encoder-platform-data-union.patch \
        file://0164-drm-rcar-du-Fix-crash-when-disabling-an-already-disa.patch \
        file://0165-drm-rcar-du-Prepare-unprepare-clock.patch \
        file://0166-drm-rcar-du-Centralize-DU-device-core-resource-manag.patch \
        file://0167-drm-rcar-du-Reorganize-CRTC-start-stop-and-power-man.patch \
        file://0168-drm-rcar-du-Create-common-encoder-and-connector-stru.patch \
        file://0169-drm-rcar-du-Add-support-for-cloned-mode-on-DU1.patch \
        file://0170-drm-rcar-du-Add-FBDEV-emulation-support.patch \
        file://0171-ARM-shmobile-Add-r8a7790-support.patch \
        file://0172-ARM-shmobile-r8a7790-Add-rcar-du-driver-support.patch \
        file://0173-usb-r8a7790-Add-ohci-ehci-host-driver-support.patch \
        file://0174-ARM-shmobile-r8a7790-Add-ohci-ehci-host-driver-suppo.patch \
        file://0175-i2c-rcar-Add-extended-clock-division-factor-field-su.patch \
        file://0176-ARM-shmobile-r8a7790-Add-rcar-i2c-driver-support.patch \
        file://0177-dma-sh-Add-shdma-desc-driver.patch \
        file://0178-ARM-shmobile-r8a7790-Add-shdma-desc-driver-support.patch \
        file://0179-dma-sh-Add-audma-pp-driver.patch \
        file://0180-ARM-shmobile-r8a7790-Add-audma-pp-driver-support.patch \
        file://0181-sound-soc-sh-Add-scu_pcm-driver.patch \
        file://0182-ARM-shmobile-r8a7790-Add-scu_pcm-driver-support.patch \
        "

S = "${WORKDIR}/git"

FILESEXTRAPATHS_prepend_lager := "${THISDIR}/${PN}:"

KERNEL_DEFCONFIG = "lager_defconfig"

do_configure_prepend() {
        install -m 0644 ${S}/arch/${ARCH}/configs/${KERNEL_DEFCONFIG} ${WORKDIR}/defconfig || die "No default configuration for ${MACHINE} / ${KERNEL_DEFCONFIG} available."
}
