RENESAS_BSP_URL = " \
    git://github.com/renesas-rcar/linux-bsp.git;protocol=https"
RENESAS_BSP_BRANCH_rcar-v3x = "v5.4.72/rcar-4.1.0.rc18"
RENESAS_BSP_SRCREV_rcar-v3x = "902a351a2509743fbc0a8c0bbb74476379dec975"

RENESAS_BSP_BRANCH_rcar-v4x = "v5.10.41/rcar-5.1.5.pt14"
RENESAS_BSP_SRCREV_rcar-v4x = "28ba841b8342a8ef6966bdb5deb9a8a90f8c684d"

# Renesas Yocto BSP version
BSP_RENESAS_VERSION_rcar-v3x = "Renesas-Yocto-v4.19.2"
BSP_RENESAS_VERSION_rcar-v4x = "Renesas-Yocto-v6.2.0"
