require recipes-kernel/linux-libc-headers/linux-libc-headers.inc
FILESEXTRAPATHS_prepend := "${THISDIR}/../linux/linux-yocto/:"

PR = "r1"

LINUX_VERSION = "3.4.46"
PROVIDES = "linux-libc-headers"
RPROVIDES_${PN}-dev = "linux-libc-headers-dev"
RPROVIDES_${PN}-dbg = "linux-libc-headers-dbg"

SRCREV = "83c6aae2029aedea44145101c26e2b37ba33e4aa"
S = "${WORKDIR}/git"

KBRANCH_DEFAULT = "standard/base"
KBRANCH = "${KBRANCH_DEFAULT}"

SRC_URI = "git://git.kernel.org/pub/scm/linux/kernel/git/horms/renesas-backport.git;protocol=git;branch=ltsi-3.4.46 \
	file://0001-drm-Move-drm_format_num_planes-to-drm_crtc.c.patch \
	file://0002-drm-Add-drm_format_plane_cpp-utility-function.patch \
	file://0003-drm-Add-drm_format_-horz-vert-_chroma_subsampling-ut.patch \
	file://0004-drm-Add-sanity-checks-to-framebuffer-creation.patch \
	file://0005-drm-Fix-EDID-color-format-parsing.patch \
	file://0006-drm-Parse-color-format-information-in-CEA-blocks.patch \
	file://0007-drm-add-the-VIC-number-to-the-CEA-EDID-modes.patch \
	file://0008-drm-add-DRM_MODE_FLAG_DBLCLK-to-CEA-modes-requiring-.patch \
	file://0009-drm-edid-Document-drm_mode_find_dmt.patch \
	file://0010-drm-edid-Rewrite-drm_mode_find_dmt-search-loop.patch \
	file://0011-drm-edid-Allow-drm_mode_find_dmt-to-hunt-for-reduced.patch \
	file://0012-drm-edid-Remove-a-misleading-comment.patch \
	file://0013-drm-edid-s-drm_gtf_modes_for_range-drm_dmt_modes_for.patch \
	file://0014-drm-edid-Add-the-reduced-blanking-DMT-modes-to-the-D.patch \
	file://0015-drm-edid-Fix-some-comment-typos-in-the-DMT-mode-list.patch \
	file://0016-drm-edid-Do-drm_dmt_modes_for_range-for-all-range-de.patch \
	file://0017-drm-edid-Give-the-est3-mode-struct-a-real-name.patch \
	file://0018-drm-edid-Add-extra_modes.patch \
	file://0019-drm-edid-Generate-modes-from-extra_modes-for-range-d.patch \
	file://0020-drm-edid-add-missing-NULL-checks.patch \
	file://0021-drm-replace-open-coded-ARRAY_SIZE-with-macro.patch \
	file://0022-drm-edid-Add-a-workaround-for-1366x768-HD-panel.patch \
	file://0023-drm-Unify-and-fix-idr-error-handling.patch \
	file://0024-drm-edid-Try-harder-to-fix-up-base-EDID-blocks.patch \
	file://0025-drm-Store-vendor-IDs-directly-in-the-EDID-quirk-stru.patch \
	file://0026-drm-edid-fix-collision-between-two-patches-breaking-.patch \
	file://0027-drm-kms-reduce-some-messages-to-debug-level-v2.patch \
	file://0028-drm-add-drm_property_change_is_valid.patch \
	file://0029-drm-WARN-when-drm_connector_attach_property-fails.patch \
	file://0030-drm-create-struct-drm_object_properties-and-use-it.patch \
	file://0031-drm-add-generic-ioctls-to-get-set-properties-on-any-.patch \
	file://0032-drm-make-the-connector-properties-code-use-the-objec.patch \
	file://0033-drm-add-count-to-struct-drm_object_properties.patch \
	file://0034-drm-add-CRTC-properties.patch \
	file://0035-drm-Don-t-initialize-local-ret-variable-when-not-nee.patch \
	file://0036-drm-Miscellaneous-typo-fixes-and-documentation-updat.patch \
	file://0037-drm-Constify-drm_mode_config_funcs-pointer.patch \
	file://0038-drm-Make-the-CRTC-gamma_set-operation-optional.patch \
	file://0039-drm-add-bitmask-property-type.patch \
	file://0040-drm-add-plane-properties.patch \
	file://0041-drm-Constify-params-to-format_check-and-framebuffer_.patch \
	file://0042-drm-Use-stdint-types-for-consistency.patch \
	file://0043-drm-edid-Make-the-header-fixup-threshold-tunable.patch \
	file://0044-drm-increase-DRM_OBJECT_MAX_PROPERTY-to-24.patch \
	file://0045-drm-edid-Don-t-add-inferred-modes-with-higher-resolu.patch \
	file://0046-drm-fb-helper-delay-hotplug-handling-when-partially-.patch \
	file://0047-drm-fb-helper-don-t-call-drm_crtc_helper_set_config.patch \
	file://0048-drm-remove-the-list_head-from-drm_mode_set.patch \
	file://0049-drm-edid-Fix-potential-memory-leak-in-edid_load.patch \
	file://0050-drm-fb-helper-don-t-clobber-output-routing-in-setup_.patch \
	file://0051-drm-Remove-two-unused-fields-from-struct-drm_display.patch \
	file://0052-Documentation-DocBook-DRM-framework-documentation.patch \
	file://0053-drm-remove-the-raw_edid-field-from-struct-drm_displa.patch \
	file://0054-drm-Initialize-object-type-when-using-DRM_MODE-macro.patch \
	file://0055-drm-Add-misssing-static-storage-class-specifier-in-d.patch \
	file://0056-drm-Add-EDID_QUIRK_FORCE_REDUCED_BLANKING-for-ASUS-V.patch \
	file://0057-drm-fb-helper-don-t-call-drm_helper_connector_dpms-d.patch \
	file://0058-drm-consistently-name-interlaced-modes.patch \
	file://0059-drm-edid-Add-some-bounds-checking.patch \
	file://0060-drm-edid-Add-bounds-checking-to-HDMI-VSDB-parsing.patch \
	file://0061-drm-edid-Refactor-HDMI-VSDB-detection.patch \
	file://0062-drm-edid-add-support-for-E-DDC.patch \
	file://0063-drm-edid-limit-printk-when-facing-bad-edid.patch \
	file://0064-DRM-Add-DRM-GEM-CMA-helper.patch \
	file://0065-drm-Add-NV24-and-NV42-pixel-formats.patch \
	file://0066-drm-refcnt-drm_framebuffer-v4.1.patch \
	file://0067-drm-support-for-rotated-scanout.patch \
	file://0068-drm-Export-drm_probe_ddc.patch \
	file://0069-UAPI-Refer-to-the-DRM-UAPI-headers-with-.-and-from-c.patch \
	file://0070-drm-rename-drm_dp_i2c_helper.c-to-drm_dp_helper.c.patch \
	file://0071-drm-dp-helper-extract-drm_dp_channel_eq_ok.patch \
	file://0072-drm-Be-more-paranoid-with-integer-overflows.patch \
	file://0073-drm-Constify-some-function-arguments.patch \
	file://0074-drm-Ignore-blob-propertys-in-drm_property_change_is_.patch \
	file://0075-drm-add-helper-to-sort-panels-to-the-head-of-the-con.patch \
	file://0076-drm-fb_helper-Fix-checkpatch-errors.patch \
	file://0077-drm-fb_helper-Convert-printk-to-pr_-and-dev_.patch \
	file://0078-drm-drm_fb_helper-Remove-unnecessary-braces.patch \
	file://0079-drm-get-cea-video-id-code-for-a-given-display-mode.patch \
	file://0080-drm-fix-documentation-for-drm_crtc_set_mode.patch \
	file://0081-drm-Reject-addfb2-with-undefined-flag-bits-set.patch \
	file://0082-drm-crtc-Remove-redundant-NULL-check-before-kfree.patch \
	file://0083-drm-crtc-Fix-potential-NULL-pointer-dereference.patch \
	file://0084-drm-fb_helper-Fix-potential-NULL-pointer-dereference.patch \
	file://0085-drm-add-drm_send_vblank_event-helper-v5.patch \
	file://0086-drm-extract-drm_kms_helper_hotplug_event.patch \
	file://0087-drm-handle-HPD-and-polled-connectors-separately.patch \
	file://0088-drm-run-the-hpd-irq-event-code-directly.patch \
	file://0089-drm-properly-init-reset-connector-status.patch \
	file://0090-drm-don-t-start-the-poll-engine-in-probe_single_conn.patch \
	file://0091-drm-don-t-poll-forced-connectors.patch \
	file://0092-drm-use-memchr_inv.patch \
	file://0093-drm-don-t-unnecessarily-enable-the-polling-work.patch \
	file://0094-drm-edid-tune-down-debug-message-in-parse_hdmi_vsdb.patch \
	file://0095-drm-doc-Helpers-are-not-a-Midlayer.patch \
	file://0096-drm-doc-integrate-crtc-helper-api-into-docbook.patch \
	file://0097-drm-doc-integrate-fb-helper-reference-into-docs.patch \
	file://0098-drm-doc-add-new-dp-helpers-into-drm-DocBook.patch \
	file://0099-drm-add-drm_mode_cea_vic.patch \
	file://0100-drm-remove-legacy-drm_connector_property-fxns.patch \
	file://0101-drm-edid-Update-range-descriptor-struct-for-EDID-1.4.patch \
	file://0102-drm-edid-Add-packed-attribute-to-new-gtf2-and-cvt-st.patch \
	file://0103-DRM-Add-DRM-KMS-FB-CMA-helper.patch \
	file://0104-drm-Make-the-.mode_fixup-operations-mode-argument-a-.patch \
	file://0105-drm-Constify-gem_vm_ops-pointer.patch \
	file://0106-dma-buf-mmap-support.patch \
	file://0107-common-dma-mapping-introduce-dma_get_sgtable-functio.patch \
	file://0108-dma-buf-add-vmap-interface.patch \
	file://0109-ARM-gic-use-a-private-mapping-for-CPU-target-interfa.patch \
	file://0110-ARM-GIC-fix-GIC-cpumask-initialization.patch \
	file://0111-ARM-GIC-remove-assembly-ifdefs-from-gic.h.patch \
	file://0112-ARM-Realview-use-SGI0-to-wake-secondary-CPUs.patch \
	file://0113-ARM-dma-mapping-add-support-for-dma_get_sgtable.patch \
	file://0114-devres-Add-devres_release.patch \
	file://0115-ARM-7498-1-mach-shmobile-Use-SGI0-to-wake-secondary-.patch \
	file://0116-ARM-7376-1-clkdev-Implement-managed-clk_get.patch \
	file://0117-ARM-7534-1-clk-Make-the-managed-clk-functions-generi.patch \
	file://0118-ARM-7537-1-clk-Fix-release-in-devm_clk_put.patch \
	file://0119-drm-GEM-CMA-Split-object-creation-into-object-alloc-.patch \
	file://0120-drm-GEM-CMA-Add-DRM-PRIME-support.patch \
	file://0121-drm-Renesas-R-Car-Display-Unit-DRM-driver.patch \
	file://0122-drm-rcar-du-Use-drm_encoder_cleanup-directly-as-.des.patch \
	file://0123-drm-rcar-du-Enable-alpha-blending-support.patch \
	file://0124-drm-rcar-du-Don-t-re-reserve-hardware-plane-at-each-.patch \
	file://0125-drm-rcar-du-Fix-planes-allocation-for-multiplanar-fo.patch \
	file://0126-drm-rcar-du-Add-DRM-PRIME-support.patch \
	file://0127-drm-rcar-du-Fix-race-condition-between-page-flip-req.patch \
	file://0128-drm-rcar-du-Add-configurable-z-order-support-for-pla.patch \
	file://0129-drm-rcar-du-Support-configurable-color-keying-for-pl.patch \
	file://0130-drm-rcar-du-Update-plane-format-after-releasing-hard.patch \
	file://0131-drm-rcar-du-Fix-register-access-for-global-registers.patch \
	file://0132-drm-rcar-du-Fix-plane-index-wrap-around-for-multi-pl.patch \
	file://0133-drm-rcar-du-Enable-the-DE-signal.patch \
	file://0134-drm-rcar-du-Split-hardware-and-KMS-planes.patch \
	file://0135-drm-rcar-du-Add-support-for-the-second-CRTC.patch \
	file://0136-drm-rcar-du-Name-the-encoder-platform-data-union.patch \
	file://0137-drm-rcar-du-Fix-crash-when-disabling-an-already-disa.patch \
	file://0138-drm-rcar-du-Prepare-unprepare-clock.patch \
	file://0139-drm-rcar-du-Centralize-DU-device-core-resource-manag.patch \
	file://0140-drm-rcar-du-Reorganize-CRTC-start-stop-and-power-man.patch \
	file://0141-drm-rcar-du-Create-common-encoder-and-connector-stru.patch \
	file://0142-drm-rcar-du-Add-support-for-cloned-mode-on-DU1.patch \
	file://0143-drm-rcar-du-Add-FBDEV-emulation-support.patch \
	file://0144-ARM-7536-1-smp-Formalize-an-IPI-for-wakeup.patch \
	file://0145-ARM-7571-1-SMP-add-function-arch_send_wakeup_ipi_mas.patch \
	file://0146-ARM-GIC-remove-direct-use-of-gic_raise_softirq.patch \
	file://0147-arm-add-set_handle_irq-to-register-the-parent-IRQ-co.patch \
	file://0148-ARM-GIC-set-handle_arch_irq-in-GIC-initialization.patch \
	file://0149-ARM-remove-mach-.handle_irq-for-GIC-users.patch \
	file://0150-irqchip-Move-ARM-GIC-to-drivers-irqchip.patch \
	file://0151-ARM-use-common-irqchip_init-for-GIC-init.patch \
	file://0152-irqchip-Move-ARM-gic.h-to-include-linux-irqchip-arm-.patch \
	file://0153-irqchip-fix-typo-when-moving-gic_raise_softirq.patch \
	file://0154-Documentation-pinctrl-add-missing-spi0_0-grp-in-exam.patch \
	file://0155-pinctrl-mark-const-init-data-with-__initconst-instea.patch \
	file://0156-pinctrl-implement-pinctrl-deferred-probing.patch \
	file://0157-pinctrl-fix-a-minor-harmless-typo.patch \
	file://0158-Documentation-pinctrl.txt-Fix-some-misspelled-macros.patch \
	file://0159-trivial-pinctrl-core-remove-extraneous-code-lines.patch \
	file://0160-pinctrl-document-semantics-vs-GPIO.patch \
	file://0161-pinctrl-Fix-potential-memory-leak-in-pinctrl_registe.patch \
	file://0162-pinctrl-fix-missing-unlock-on-error-in-pinctrl_group.patch \
	file://0163-pinctrl-fix-comment-mistake.patch \
	file://0164-pinctrl-skip-deferral-of-hogs.patch \
	file://0165-pinctrl-core-get-devname-from-pinctrl_dev.patch \
	file://0166-drivers-pinctrl-grab-default-handles-from-device-cor.patch \
	file://0167-gpio-add-flags-to-export-GPIOs-when-requesting.patch \
	file://0168-gpio-Move-DT-support-code-into-drivers-gpio.patch \
	file://0169-gpiolib-Implement-devm_gpio_request_one.patch \
	file://0170-pinctrl-allow-pctldevs-to-decode-pin-config-in-debug.patch \
	file://0171-gpio-Adjust-of_xlate-API-to-support-multiple-GPIO-ch.patch \
	file://0172-gpiolib-quiet-gpiochip_add-boot-message-noise.patch \
	file://0173-gpiolib-Remove-const-from-data-argument-of-gpiochip_.patch \
	file://0174-gpio-of-fix-a-typo-of-comment-message.patch \
	file://0175-gpio-propagate-of_parse_phandle_with_args-errors.patch \
	file://0176-gpiolib-Defer-failed-gpio-requests-by-default.patch \
	file://0177-gpio-of_get_named_gpio_flags-return-EPROBE_DEFER-if-.patch \
	file://0178-gpio-Fix-debug-message-in-of_get_named_gpio_flags.patch \
	file://0179-gpiolib-Use-seq_file-s-iterator-interface.patch \
	file://0180-gpio-Document-device_node-s-det_debounce.patch \
	file://0181-gpiolib-Refactor-gpio_export.patch \
	file://0182-gpiolib-add-gpio-get-direction-callback-support.patch \
	file://0183-gpiolib-unlock-on-error-in-gpio_export.patch \
	file://0184-gpiolib-provide-provision-to-register-pin-ranges.patch \
	file://0185-gpiolib-fix-up-function-prototypes-etc.patch \
	file://0186-gpiolib-of-staticize-the-pin-range-calls.patch \
	file://0187-gpiolib-remove-duplicate-pin-range-code.patch \
	file://0188-gpiolib-call-pin-removal-in-chip-removal-function.patch \
	file://0189-gpiolib-separation-of-pin-concerns.patch \
	file://0190-gpiolib-iron-out-include-ladder-mistakes.patch \
	file://0191-gpiolib-let-gpiochip_add_pin_range-specify-offset.patch \
	file://0192-gpiolib-rename-find_pinctrl_.patch \
	file://0193-gpiolib-return-any-error-code-from-range-creation.patch \
	file://0194-gpiolib-rename-pin-range-arguments.patch \
	file://0195-gpiolib-Fix-use-after-free-in-gpiochip_add_pin_range.patch \
	file://0196-gpio-use-pinctrl-device-name-for-add-range.patch \
	file://0197-gpio-fix-warning-of-struct-gpio_chip-declaration.patch \
	file://0198-gpio-devm_gpio_-support-should-not-depend-on-GPIOLIB.patch \
	file://0199-gpiolib-remove-gpiochip_reserve.patch \
	file://0200-gpiolib-add-missing-braces-in-gpio_direction_show.patch \
	file://0201-gpiolib-link-all-gpio_chips-using-a-list.patch \
	file://0202-gpiolib-use-gpio_chips-list-in-gpiolib_sysfs_init.patch \
	file://0203-pinctrl-generic-dump-pin-configuration.patch \
	file://0204-Revert-pinctrl-remove-pinctrl_remove_gpio_range.patch \
	file://0205-pinctrl-Declare-operation-structures-as-const.patch \
	file://0206-pinctrl-generic-Fix-compilation-error.patch \
	file://0207-sh-pfc-Split-out-gpio-chip-support.patch \
	file://0208-sh-pfc-Make-gpio-chip-support-optional-where-possibl.patch \
	file://0209-sh-pfc-Kill-off-unused-pinmux-bias-flags.patch \
	file://0210-sh-pfc-Verify-pin-type-encoding-size-at-build-time.patch \
	file://0211-sh-pfc-Shuffle-PFC-support-core.patch \
	file://0212-sh-pfc-Dumb-GPIO-stringification.patch \
	file://0213-sh-pfc-Rudimentary-pinctrl-backed-GPIO-support.patch \
	file://0214-sh-pfc-pinctrl-legacy-function-support.patch \
	file://0215-sh-pfc-Make-pr_fmt-consistent-across-pfc-drivers.patch \
	file://0216-sh-pfc-Export-pinctrl-binding-init-symbol.patch \
	file://0217-sh-pfc-Ignore-pinmux-GPIOs-with-invalid-enum-IDs.patch \
	file://0218-sh-pfc-pinctrl-legacy-group-support.patch \
	file://0219-sh-pfc-Prefer-DRV_NAME-over-KBUILD_MODNAME.patch \
	file://0220-sh-pfc-pin-config-get-set-support.patch \
	file://0221-sh-pfc-Build-fix-for-pinctrl_remove_gpio_range-chang.patch \
	file://0222-sh-pfc-Fix-up-init-ordering-mess.patch \
	file://0223-sh-pfc-Release-spinlock-in-sh_pfc_gpio_request_enabl.patch \
	file://0224-sh-pfc-Fix-up-GPIO-mux-type-reconfig-case.patch \
	file://0225-sh-pfc-Error-out-on-pinctrl-init-resolution-failure.patch \
	file://0226-ARM-shmobile-move-custom-gpio-functions-to-sh-gpio.h.patch \
	file://0227-Drivers-misc-remove-__dev-attributes.patch \
	file://0228-sh-sh7723-Rename-GPIO_FN_SIUOSPD-to-GPIO_FN_SIUAOSPD.patch \
	file://0229-sh-sh7757-Fix-GPIO_FN_ET0_MDIO-and-GPIO_FN_ET1_MDIO-.patch \
	file://0230-sh-sh7786-Fix-port-E-G-and-J-GPIOs.patch \
	file://0231-sh-sh7786-Fix-last-GPIO-index.patch \
	file://0232-sh-shx3-Fix-last-GPIO-index.patch \
	file://0233-sh-pfc-Split-platform-data-from-the-sh_pfc-structure.patch \
	file://0234-sh-pfc-Move-private-definitions-and-declarations-to-.patch \
	file://0235-sh-pfc-Merge-PFC-core-and-pinctrl.patch \
	file://0236-sh-pfc-Merge-PFC-core-and-gpio.patch \
	file://0237-sh-pfc-Move-platform-device-and-driver-to-the-core.patch \
	file://0238-sh-pfc-Use-devm_kzalloc.patch \
	file://0239-sh-pfc-Use-devm_ioremap_nocache.patch \
	file://0240-sh-pfc-Let-the-compiler-decide-whether-to-inline-fun.patch \
	file://0241-sh-pfc-Remove-check-for-impossible-error-condition.patch \
	file://0242-sh-pfc-Sort-headers-alphabetically.patch \
	file://0243-sh-pfc-Use-sh_pfc_-namespace-prefix-through-the-whol.patch \
	file://0244-sh-pfc-Split-platform-device-and-platform-driver-reg.patch \
	file://0245-sh-pfc-Support-passing-resources-through-platform-de.patch \
	file://0246-ARM-shmobile-Select-PINCTRL.patch \
	file://0247-ARM-shmobile-r8a7740-Register-PFC-platform-device.patch \
	file://0248-ARM-shmobile-r8a7779-Register-PFC-platform-device.patch \
	file://0249-ARM-shmobile-sh7372-Register-PFC-platform-device.patch \
	file://0250-ARM-shmobile-sh73a0-Register-PFC-platform-device.patch \
	file://0251-ARM-shmobile-r8a7740-Add-pin-control-resources.patch \
	file://0252-ARM-shmobile-sh7372-Add-pin-control-resources.patch \
	file://0253-ARM-shmobile-sh73a0-Add-pin-control-resources.patch \
	file://0254-sh-Add-PFC-platform-device-registration-helper-funct.patch \
	file://0255-sh-sh7203-Register-PFC-platform-device.patch \
	file://0256-sh-sh7720-Register-PFC-platform-device.patch \
	file://0257-sh-sh7722-Register-PFC-platform-device.patch \
	file://0258-sh-sh7723-Register-PFC-platform-device.patch \
	file://0259-sh-sh7724-Register-PFC-platform-device.patch \
	file://0260-sh-sh7757-Register-PFC-platform-device.patch \
	file://0261-sh-sh7785-Register-PFC-platform-device.patch \
	file://0262-sh-sh7786-Register-PFC-platform-device.patch \
	file://0263-sh-shx3-Register-PFC-platform-device.patch \
	file://0264-sh-pfc-Remove-platform-device-registration.patch \
	file://0265-sh-pfc-Remove-unused-resource-and-num_resources-plat.patch \
	file://0266-sh-pfc-Move-driver-from-drivers-sh-to-drivers-pinctr.patch \
	file://0267-sh-pfc-Support-pinmux-info-in-driver-data-instead-of.patch \
	file://0268-sh-pfc-Add-r8a7740-pinmux-support.patch \
	file://0269-ARM-shmobile-r8a7779-PFC-rename-PENCx-USB_PENCx.patch \
	file://0270-sh-pfc-Add-r8a7779-pinmux-support.patch \
	file://0271-sh-pfc-Add-sh7372-pinmux-support.patch \
	file://0272-sh-pfc-Add-sh73a0-pinmux-support.patch \
	file://0273-sh-pfc-Add-sh7203-pinmux-support.patch \
	file://0274-sh-pfc-Add-sh7264-pinmux-support.patch \
	file://0275-sh-pfc-Add-sh7269-pinmux-support.patch \
	file://0276-sh-pfc-Add-sh7720-pinmux-support.patch \
	file://0277-sh-pfc-Add-sh7722-pinmux-support.patch \
	file://0278-sh-pfc-Add-sh7723-pinmux-support.patch \
	file://0279-sh-pfc-Add-sh7724-pinmux-support.patch \
	file://0280-sh-pfc-Add-sh7734-pinmux-support.patch \
	file://0281-sh-pfc-Add-sh7757-pinmux-support.patch \
	file://0282-sh-pfc-Add-sh7785-pinmux-support.patch \
	file://0283-sh-pfc-Add-sh7786-pinmux-support.patch \
	file://0284-sh-pfc-Add-shx3-pinmux-support.patch \
	file://0285-ARM-shmobile-Remove-SH7367-support.patch \
	file://0286-ARM-shmobile-Remove-SH7377-support.patch \
	file://0287-ARM-shmobile-r8a7740-Use-driver-provided-pinmux-info.patch \
	file://0288-ARM-shmobile-r8a7779-Use-driver-provided-pinmux-info.patch \
	file://0289-ARM-shmobile-sh7372-Use-driver-provided-pinmux-info.patch \
	file://0290-ARM-shmobile-sh73a0-Use-driver-provided-pinmux-info.patch \
	file://0291-sh-sh7203-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0292-sh-sh7720-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0293-sh-sh7722-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0294-sh-sh7723-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0295-sh-sh7724-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0296-sh-sh7757-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0297-sh-sh7785-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0298-sh-sh7786-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0299-sh-shx3-pinmux-Use-driver-provided-pinmux-info.patch \
	file://0300-sh-Remove-unused-sh_pfc_register_info-function.patch \
	file://0301-sh-pfc-Remove-pinmux_info-definition.patch \
	file://0302-sh-pfc-Move-sh_pfc.h-from-include-linux-to-driver-di.patch \
	file://0303-sh-pfc-Declare-operation-structures-as-const.patch \
	file://0304-sh-pfc-Don-t-define-the-per-device-pinctrl-struct-in.patch \
	file://0305-sh-pfc-Fix-a-typo-and-simplify-a-definition-on-sh73a.patch \
	file://0306-sh-pfc-Drop-the-sh_pfc_pinctrl-spinlock.patch \
	file://0307-sh-pfc-Don-t-take-the-sh_pfc-spinlock-in-sh_pfc_map_.patch \
	file://0308-sh-pfc-Use-GPIO_FN-instead-of-PINMUX_GPIO-where-poss.patch \
	file://0309-sh-pfc-Replace-first_gpio-and-last_gpio-with-nr_gpio.patch \
	file://0310-sh-pfc-Replace-SoC-info-data-and-mark-ranges-with-a-.patch \
	file://0311-sh-pfc-Remove-unused-sh_pfc_soc_info-reserved_id-fie.patch \
	file://0312-sh-pfc-Initialize-pinmux_gpio-flags-statically.patch \
	file://0313-sh-pfc-Make-struct-pinmux_gpio-enum_id-field-const.patch \
	file://0314-sh-pfc-Shrink-the-pinctrl-GPIO-range-to-include-real.patch \
	file://0315-sh-pfc-Don-t-needlessly-check-GPIO-type-in-sh_gpio_f.patch \
	file://0316-sh-pfc-Split-pins-and-functions-definition-tables.patch \
	file://0317-sh-pfc-Split-pins-and-functions-into-separate-gpio_c.patch \
	file://0318-sh-pfc-Rename-struct-pinmux_pin-to-struct-sh_pfc_pin.patch \
	file://0319-sh-pfc-Look-up-IRQ-table-entries-by-GPIO-number.patch \
	file://0320-sh-pfc-Share-the-PORT_10_REV-PORT_32-and-PORT_32_REV.patch \
	file://0321-sh-pfc-Use-pinmux-identifiers-in-the-pin-muxing-API.patch \
	file://0322-sh-pfc-Simplify-the-sh_pfc_gpio_is_pin-logic.patch \
	file://0323-sh-pfc-Add-function-to-retrieve-a-pin-instance-from-.patch \
	file://0324-sh-pfc-Replace-pinctrl_add_gpio_range-with-gpiochip_.patch \
	file://0325-sh-pfc-Add-support-for-sparse-pin-numbers.patch \
	file://0326-ARM-shmobile-ag5evm-Use-gpio_request_one.patch \
	file://0327-ARM-shmobile-kota2-Use-gpio_request_one.patch \
	file://0328-ARM-shmobile-kzm9g-Use-gpio_request_one.patch \
	file://0329-ARM-shmobile-sh73a0-Support-sparse-GPIO-numbers.patch \
	file://0330-ARM-shmobile-ap4evb-Use-gpio_request_one.patch \
	file://0331-ARM-shmobile-use-common-extra-gpio-functions-on-ap4e.patch \
	file://0332-ARM-shmobile-ap4-evb-Replace-GPIO_PORTx-enum-with-GP.patch \
	file://0333-ARM-shmobile-armadillo800eva-Use-gpio_request_one.patch \
	file://0334-ARM-shmobile-armadillo800eva-Use-gpio_set_value-to-s.patch \
	file://0335-ARM-shmobile-armadillo-Replace-GPIO_PORTx-enum-with-.patch \
	file://0336-ARM-shmobile-bonito-Use-gpio_request_one.patch \
	file://0337-ARM-shmobile-bonito-Replace-GPIO_PORTx-enum-with-GPI.patch \
	file://0338-ARM-shmobile-mackerel-Use-gpio_request_one.patch \
	file://0339-ARM-shmobile-use-common-extra-gpio-functions-on-Mack.patch \
	file://0340-ARM-shmobile-mackerel-Replace-GPIO_PORTx-enum-with-G.patch \
	file://0341-sh-pfc-Expose-real-groups-and-functions-in-pinctrl-p.patch \
	file://0342-sh-pfc-Fix-return-value-check-in-sh_pfc_register_pin.patch \
	file://0343-sh-pfc-Move-GPIO-registers-access-functions-to-gpio..patch \
	file://0344-sh-pfc-Don-t-map-data-registers-individually.patch \
	file://0345-sh-pfc-Drop-unused-support-for-1-1-physical-to-virtu.patch \
	file://0346-sh-pfc-Don-t-modify-pinmux_data_reg-SoC-data.patch \
	file://0347-sh-pfc-Don-t-modify-sh_pfc_pin-SoC-data.patch \
	file://0348-sh-pfc-Remove-configuration-dry-run-and-free.patch \
	file://0349-sh-pfc-Constify-all-SoC-data.patch \
	file://0350-sh-pfc-Use-proper-error-codes.patch \
	file://0351-sh-pfc-Implement-generic-pinconf-support.patch \
	file://0352-sh-pfc-Merge-sh_pfc_reconfig_pin-into-sh_pfc_gpio_se.patch \
	file://0353-sh-pfc-Clean-up-pin-configuration-type-handling.patch \
	file://0354-sh-pfc-Convert-message-printing-from-pr_-to-dev_.patch \
	file://0355-sh-pfc-Return-an-error-if-a-pin-doesn-t-support-the-.patch \
	file://0356-sh-pfc-r8a7779-Add-DU-pin-groups-and-functions.patch \
	file://0357-sh-pfc-r8a7779-Add-SDHI-and-MMCIF-pin-groups-and-fun.patch \
	file://0358-sh-pfc-r8a7779-Add-SCIF-pin-groups-and-functions.patch \
	file://0359-sh-pfc-r8a7779-Add-HSPI-pin-groups-and-functions.patch \
	file://0360-sh-pfc-r8a7779-Add-USB0-and-USB1-PENC-pinmux-support.patch \
	file://0361-sh-pfc-r8a7779-Add-USB-pin-groups-and-functions.patch \
	file://0362-sh-pfc-r8a7779-Add-LBSC-pin-groups-and-functions.patch \
	file://0363-sh-pfc-r8a7779-Add-INTC-pin-groups-and-functions.patch \
	file://0364-ARM-shmobile-marzen-Register-pinctrl-mappings-for-SD.patch \
	file://0365-ARM-shmobile-marzen-Register-pinctrl-mappings-for-SC.patch \
	file://0366-ARM-shmobile-marzen-Register-pinctrl-mappings-for-LB.patch \
	file://0367-ARM-shmobile-marzen-Register-pinctrl-mappings-for-IN.patch \
	file://0368-sh-pfc-r8a7779-Remove-DU1_DOTCLKOUT1-GPIO.patch \
	file://0369-sh-pfc-r8a7779-Remove-SDHI-and-MMCIF-function-GPIOS.patch \
	file://0370-sh-pfc-r8a7779-Remove-SCIF-function-GPIOS.patch \
	file://0371-sh-pfc-r8a7779-Remove-HSPI-function-GPIOS.patch \
	file://0372-sh-pfc-r8a7779-Remove-USB-function-GPIOS.patch \
	file://0373-sh-pfc-r8a7779-Remove-LBSC-function-GPIOS.patch \
	file://0374-sh-pfc-r8a7779-Remove-INTC-function-GPIOS.patch \
	file://0375-ARM-shmobile-r8a7779-Remove-DU-function-GPIOs.patch \
	file://0376-ARM-shmobile-r8a7779-Remove-SDHI-and-MMCIF-function-.patch \
	file://0377-ARM-shmobile-r8a7779-Remove-SCIF-function-GPIOs.patch \
	file://0378-ARM-shmobile-r8a7779-Remove-HSPI-function-GPIOs.patch \
	file://0379-ARM-shmobile-r8a7779-Remove-USB-function-GPIOs.patch \
	file://0380-ARM-shmobile-r8a7779-Remove-LBSC-function-GPIOs.patch \
	file://0381-ARM-shmobile-r8a7779-Remove-INTC-function-GPIOs.patch \
	file://0382-gpio-Renesas-R-Car-GPIO-driver-V3.patch \
	file://0383-sh-pfc-r8a7779-Remove-function-GPIOs.patch \
	file://0384-sh-pfc-r8a7779-Don-t-use-GPIO-enum-entries.patch \
	file://0385-ARM-shmobile-r8a7779-Remove-all-GPIOs.patch \
	file://0386-ARM-shmobile-add-gic_iid-macro-for-ICCIAR-interrupt-.patch \
	file://0387-gpio-rcar-Add-pinctrl-support.patch \
	file://0388-sh-pfc-Make-function-GPIOs-support-optional.patch \
	file://0389-sh-pfc-Make-GPIO-support-optional.patch \
	file://0390-sh-pfc-Skip-gpiochip-registration-when-no-GPIO-resou.patch \
	file://0391-sh-pfc-Configure-pins-as-GPIOs-at-request-time-when-.patch \
	file://0392-ARM-shmobile-r8a7779-Register-GPIO-devices.patch \
	file://0393-sh-pfc-r8a7779-Remove-GPIO-data.patch \
	file://0394-ARM-shmobile-marzen-Add-GPIO-LEDs.patch \
	file://0395-sh-pfc-r8a7779-Split-DU-input-and-output-pixel-clock.patch \
	file://0396-ARM-shmobile-Initial-r8a7790-SoC-support.patch \
	file://0397-ARM-shmobile-r8a7790-SCIF-support.patch \
	file://0398-ARM-shmobile-r8a7790-IRQC-support.patch \
	file://0399-ARM-shmobile-r8a7790-PFC-support.patch \
	file://0400-ARM-shmobile-r8a7790-SoC-64-bit-DT-support.patch \
	file://0401-ARM-shmobile-Add-second-I-O-range-for-r8a7790-PFC.patch \
	file://0402-ARM-shmobile-force-enable-of-r8a7790-arch-timer.patch \
	file://0403-sh-pfc-Initial-r8a7790-PFC-support.patch \
	file://0404-sh-pfc-Remove-dependency-on-GPIOLIB.patch \
	file://0405-gpio-rcar-Add-RCAR_GP_PIN-macro.patch \
	file://0406-sh-pfc-r8a7790-Add-ETH-pin-groups-and-functions.patch \
	file://0407-sh-pfc-r8a7790-Add-INTC-pin-groups-and-functions.patch \
	file://0408-sh-pfc-r8a7790-Add-SCIF-SCIFA-and-SCIFB-pin-groups-a.patch \
	file://0409-sh-pfc-r8a7790-Remove-GPIO-data.patch \
	file://0410-sh-pfc-r8a7790-Remove-function-GPIOs.patch \
	file://0411-sh-pfc-r8a7790-Don-t-use-GPIO-enum-entries.patch \
	file://0412-ARM-shmobile-r8a7790-Register-GPIO-devices.patch \
	file://0413-ARM-shmobile-r8a7790-Remove-all-GPIOs.patch \
	file://0414-sh-pfc-r8a7790-Rename-DU1_DOTCLKIN-to-DU_DOTCLKIN1.patch \
	file://0415-sh-pfc-r8a7790-Add-DU-pin-groups-and-functions.patch \
	file://0416-drm-make-buffer-management-work-without-DRM_MASTER.patch \
	file://0417-drm-change-ioctl-permissions.patch \
	file://0418-drm-pass-dev-to-drm_vm_-open-close-_locked.patch \
	file://0419-drm-gem-Split-drm_gem_mmap-into-object-search-and-ob.patch \
	file://0420-r8a7779-add-SDHI-clock-support.patch \
	file://0421-ARM-shmobile-r8a7779-use-__iomem-pointers-for-MMIO.patch \
	file://0422-ARM-shmobile-r8a7779-add-HSPI-clock-support.patch \
	file://0423-ARM-shmobile-r8a7779-add-I2C-clock-support.patch \
	file://0424-ARM-shmobile-r8a7779-add-USB-EHCI-clock-support.patch \
	file://0425-ARM-shmobile-r8a7779-add-USB-OHCI-clock-support.patch \
	file://0426-r8a7779-Add-Display-Unit-clock-support.patch \
	file://0427-drm-GEM-CMA-Split-object-mapping-into-GEM-mapping-an.patch \
	file://0428-drm-rcar-du-Add-XRGB1555-format-support.patch \
	file://0429-drm-rcar-du-Add-plane-property-to-set-global-alpha-v.patch \
	file://0430-drm-rcar-du-Don-t-modify-mode-active-size-in-encoder.patch \
	file://0431-drm-rcar-du-Use-the-mode-active-size-in-mode-set.patch \
	file://0432-drm-rcar-du-Take-offsets-into-account-in-the-mode_se.patch \
	file://0433-drm-rcar-du-Fix-plane-source-position-configuration.patch \
	file://0434-drm-rcar-du-Don-t-clean-up-mode-setting-if-it-hasn-t.patch \
	file://0435-ARM-shmobile-r8a7779-Add-DU-support.patch \
	file://0436-ARM-shmobile-marzen-Add-Display-Unit-support.patch \
	file://0437-ARM-7376-1-clkdev-Implement-managed-clk_get.patch \
	file://0438-ARM-7534-1-clk-Make-the-managed-clk-functions-generi.patch \
	file://0439-libata-add-R-Car-SATA-driver.patch \
	file://0440-libata-do-not-limit-R-Car-SATA-driver-to-shmobile.patch \
	file://0441-LTSI-ARM-shmobile-r8a7779-fixup-LTSI-conflict.patch \
	file://0442-ARM-mach-shmobile-r8a7779-add-SATA-support.patch \
	file://0443-ARM-mach-shmobile-marzen-add-SATA-support.patch \
	file://0444-mmc-sh_mmcif-remove-unneeded-clock-connection-ID.patch \
	file://0445-mmc-sh_mmcif-force-to-fail-CMD52-immediately.patch \
	file://0446-mmc-sh_mmcif-add-support-for-bundled-MMCIF-IRQs.patch \
	file://0447-sh-pfc-Add-r8a7778-pinmux-support.patch \
	file://0448-sh-pfc-r8a7778-add-common-PFC-macro-helper.patch \
	file://0449-sh-pfc-r8a7778-add-SDHI-support.patch \
	file://0450-sh-pfc-r8a7778-Fix-outdated-GPIO_FN-comments.patch \
	file://0451-sh-pfc-r8a7778-tidyup-SDHI-naming-suffixes-and-sort-.patch \
	file://0452-sh-pfc-r8a7778-add-USB-pin-groups.patch \
	file://0453-sh-pfc-r8a7778-add-VIN-pin-groups.patch \
	file://0454-sh-pfc-r8a7778-add-Ether-pin-groups.patch \
	file://0455-sh-pfc-r8a7778-fixup-IRQ1A-settings.patch \
	file://0456-sh-pfc-r8a7778-add-I2C-pin-groups.patch \
	file://0457-sh-pfc-r8a7778-add-HSPI-pin-groups.patch \
	file://0458-sh-pfc-r8a7778-add-MMCIF-pin-groups.patch \
	file://0459-spi-hspi-fixup-long-delay-time.patch \
	file://0460-spi-spi-sh-hspi-drop-frees-of-devm_-alloc-d-data.patch \
	file://0461-spi-sh-hspi-add-CS-manual-control-support.patch \
	file://0462-spi-sh-hspi-fix-return-value-check-in-hspi_probe.patch \
	file://0463-mtd-m25p80-add-support-for-Everspin-MR25H256-MRAM-ch.patch \
	file://0464-mtd-add-m25p80-id-for-mx25l2005a.patch \
	file://0465-mtd-m25p80-Add-support-for-Winbond-W25Q80BW.patch \
	file://0466-mtd-add-JEDEC-ID-for-w25q32dw-to-chip-table.patch \
	file://0467-mtd-m25p80-Add-support-for-m25pe20.patch \
	file://0468-mtd-m25p80-Add-support-for-n25q064.patch \
	file://0469-mtd-m25p80-Add-support-for-Atmel-at45db081d.patch \
	file://0470-mtd-m25p80-Add-support-for-serial-flash-STM-Micron-N.patch \
	file://0471-mtd-m25p80-add-support-for-Spansion-s25sl064p-chip.patch \
	file://0472-mtd-m25p80-Fix-the-Spansion-chip-detection.patch \
	file://0473-mtd-m25p80-add-support-for-Micron-N25Q256A.patch \
	file://0474-mtd-m25p80-add-support-for-Micron-N25Q128.patch \
	file://0475-mtd-m25p80-add-support-for-the-EON-EN25Q64-chip.patch \
	file://0476-mtd-m25p80-Disable-4KiB-erase-for-s25sl032p-s25sl064.patch \
	file://0477-mtd-m25p80-Make-fast-read-configurable-via-DT.patch \
	file://0478-mtd-m25p80-add-support-for-the-windbond-w25q256-chip.patch \
	file://0479-mtd-m25p80-add-support-for-the-Winbond-w25q80bl-chip.patch \
	file://0480-mtd-m25p80-modify-info-for-Micron-N25Q128.patch \
	file://0481-mtd-m25p80-Flash-protection-support-for-STmicro-chip.patch \
	file://0482-mtd-chips-Add-support-for-GigaDevice-GD25Q32-GD25Q64.patch \
	file://0483-mtd-m25p80-add-support-for-Macronix-MX66L51235L.patch \
	file://0484-mtd-m25p80-add-support-for-EON-EN25QH256.patch \
	file://0485-mtd-m25p80-n25q064-is-Micron-not-Intel-Numonyx.patch \
	file://0486-mtd-m25p80-introduce-SST_WRITE-flag-for-SST-byte-pro.patch \
	file://0487-mtd-m25p80-add-support-for-SST25VF064C.patch \
	file://0488-mtd-m25p80-add-entry-for-w25q128.patch \
	file://0489-ARM-shmobile-add-struct-clk_ratio-and-fixed-ratio-cl.patch \
	file://0490-ARM-shmobile-add-GPIO-IRQ-macro.patch \
	file://0491-ARM-shmobile-remove-from-SH_FIXED_RATIO_CLK-macro.patch \
	file://0492-ARM-shmobile-add-R8A7778-basis-support.patch \
	file://0493-ARM-shmobile-r8a7778-SCIF-support.patch \
	file://0494-ARM-shmobile-r8a7778-remove-pointless-PLATFORM_INFO.patch \
	file://0495-LTSI-ARM-shmobile-r8a7778-setup-early-timer.patch \
	file://0496-ARM-shmobile-r8a7778-add-r8a7778_init_irq_extpin.patch \
	file://0497-ARM-shmobile-R8A7778-add-Ether-support.patch \
	file://0498-ARM-shmobile-r8a7778-fixup-Ether-setup-code-position.patch \
	file://0499-ARM-shmobile-R8A7778-fix-Ether-device-name.patch \
	file://0500-ARM-shmobile-r8a7778-Register-PFC-device.patch \
	file://0501-ARM-shmobile-r8a7778-Register-SDHI-device.patch \
	file://0502-ARM-shmobile-r8a7778-use-fixed-ratio-clock.patch \
	file://0503-ARM-shmobile-r8a7778-add-SDHI-clock-support.patch \
	file://0504-ARM-shmobile-r8a7778-add-GPIO-support.patch \
	file://0505-ARM-shmobile-r8a7778-add-__initdata-on-resource-and-.patch \
	file://0506-ARM-shmobile-r8a7778-add-I2C-support.patch \
	file://0507-ARM-shmobile-r8a7778-add-HSPI-support.patch \
	file://0508-ARM-shmobile-r8a7778-add-MMCIF-support.patch \
	file://0509-ARM-shmobile-add-R-Car-M1A-Bock-W-platform-support.patch \
	file://0510-ARM-shmobile-bockw-add-SMSC-ethernet-support.patch \
	file://0511-ARM-shmobile-bockw-enable-SMSC-ethernet-on-defconfig.patch \
	file://0512-LTSI-ARM-shmobile-bockw-fixup-early-timer-dtb-compil.patch \
	file://0513-ARM-shmobile-bockw-add-CN9-SCIF-RCAN-selection-dipsw.patch \
	file://0514-ARM-shmobile-bockw-add-dummy-regulators-for-SMSC.patch \
	file://0515-ARM-shmobile-bockw-add-pinctrl-support.patch \
	file://0516-ARM-shmobile-bockw-define-FPGA-address-and-rename-io.patch \
	file://0517-ARM-shmobile-bockw-add-SDHI0-support.patch \
	file://0518-ARM-shmobile-bockw-enable-SDHI-on-defconfig.patch \
	file://0519-ARM-shmobile-BOCK-W-enable-I2C-in-defconfig.patch \
	file://0520-ARM-shmobile-BOCK-W-enable-CONFIG_PM_RUNTIME-in-defc.patch \
	file://0521-ARM-shmobile-BOCK-W-enable-USB-in-defconfig.patch \
	file://0522-ARM-shmobile-bockw-add-I2C-device-support.patch \
	file://0523-ARM-shmobile-bockw-add-SPI-FLASH-support.patch \
	file://0524-ARM-shmobile-bockw-add-MMCIF-support.patch \
	file://0525-ARM-shmobile-bockw-defconfig-add-RTC-RX8581-support.patch \
	file://0526-ARM-shmobile-bockw-defconfig-add-M25P80-support.patch \
	file://0527-ARM-shmobile-bockw-defconfig-add-MMCIF-support.patch \
	file://0528-LTSI-ARM-shmobile-r8a7778-keep-TMU-resource-for-LTSI.patch \
	file://0529-LTSI-ARM-shmobile-bockw-enable-CONFIG_EXPERIMENTAL.patch \
	file://0530-Local-sh-pfc-r8a7778-add-SRU-SSI-pin-support.patch \
	file://0531-ASoC-simple-card-use-struct-device-pointer-for-dev_x.patch \
	file://0532-ASoC-simple-card-add-asoc_simple_dai-for-initializin.patch \
	file://0533-Local-ASoC-add-ak4554-driver.patch \
	file://0534-Local-ASoC-add-Renesas-R-Car-core-feature.patch \
	file://0535-Local-ASoC-add-Renesas-R-Car-module-feature.patch \
	file://0536-Local-ASoC-add-Renesas-R-Car-Generation-feature.patch \
	file://0537-Local-ASoC-add-Renesas-R-Car-SCU-feature.patch \
	file://0538-Local-ASoC-add-Renesas-R-Car-ADG-feature.patch \
	file://0539-Local-ASoC-add-Renesas-R-Car-SSI-feature.patch \
	file://0540-Local-ARM-shmobile-r8a7778-add-rcar_sound-driver-sup.patch \
	file://0541-LTSI-ASoC-rcar-tidyup-framework-mismatch.patch \
	file://0542-ASoC-rsnd-remove-platform-dai-and-add-dai_id-on-plat.patch \
	file://0543-Local-ARM-shmobile-bockw-add-R-Car-sound-support.patch \
	file://0544-Local-ARM-shmobile-bockw-add-R-Car-Sound-support-on-.patch \
	file://0545-LTSI-ARM-shmobile-r8a7778-tidyup-sound-card-detectio.patch \
	file://0546-gpio-rcar-R-Car-GPIO-IRQ-share-interrupt.patch \
	file://0547-usb-host-ehci-platform-add-platform-specific-power-c.patch \
	file://0548-ehci-platform-add-pre_setup-method-to-platform-data.patch \
	file://0549-USB-Add-driver-for-NXP-ISP1301-USB-transceiver.patch \
	file://0550-usb-host-ohci-platform-BUG_ON-to-WARN_ON-on-probe.patch \
	file://0551-usb-host-ehci-platform-BUG_ON-to-WARN_ON-on-probe.patch \
	file://0552-usb-host-ohci-platform-add-platform-specific-power-c.patch \
	file://0553-usb-phy-Fix-Kconfig-dependency-for-Phy-drivers.patch \
	file://0554-usb-phy-mv_u3d-Add-usb-phy-driver-for-mv_u3d.patch \
	file://0555-usb-phy-isp1301-Remove-unused-static-array-and-defin.patch \
	file://0556-usb-phy-add-R-Car-USB-phy-driver.patch \
	file://0557-LTSI-usb-phy-rename-rcar-phy.patch \
	file://0558-phy-rcar-usb-remove-EHCI-internal-buffer-setup.patch \
	file://0559-phy-rcar-usb-add-platform-data.patch \
	file://0560-phy-rcar-usb-handle-platform-data.patch \
	file://0561-phy-rcar-usb-add-R8A7778-support.patch \
	file://0562-phy-rcar-usb-correct-base-address.patch \
	file://0563-ARM-shmobile-r8a7778-add-USB-support.patch \
	file://0564-ARM-shmobile-BOCK-W-add-USB-support.patch \
	file://0565-LTSI-ARM-shmobile-r8a7778-tidyup-generation-conflict.patch \
	file://0566-LTSI-usb-fixup-generation-conflict.patch \
	file://0567-soc-camera-Add-plane-layout-information-to-struct-so.patch \
	file://0568-soc-camera-Add-soc_mbus_image_size.patch \
	file://0569-V4L2-soc-camera-move-generic-functions-into-a-separa.patch \
	file://0570-Add-OKI-Semiconductor-ML86V7667-video-decoder-driver.patch \
	file://0571-Add-Renesas-R-Car-VIN-Video-In-V4L2-driver.patch \
	file://0572-ARM-shmobile-r8a7778-add-VIN-support.patch \
	file://0573-ARM-shmobile-BOCK-W-add-VIN-and-ML86V7667-support.patch \
	file://0574-ARM-shmobile-BOCK-W-enable-VIN-and-ML86V7667-in-defc.patch \
	file://0575-drm-gp2d-DRM-Support-for-Renesas-R-Car-GP2D.patch \
	file://0576-drm-gp2d-support-AAFC-and-JUMP-command.patch \
	file://0577-gp2d-work-queue-timeout-fix-event-dealloc-fix-was-ke.patch \
	file://0578-gp2d-add-some-supports-for-R-GP2D-acceleration.patch \
	file://0579-sh-pfc-r8a7778-add-DU-pin-support.patch \
	file://0580-ARM-shmobile-bockw-Add-Display-Unit-support.patch \
	file://0581-ARM-mach-shmobile-r8a7778-add-GP2D-clock-support.patch \
	file://0582-ARM-shmobile-bockw-add-R-Car-GP2D-device-support.patch \
	file://0583-ARM-shmobile-BOCK-W-enable-DU-and-GP2D-in-defconfig.patch \
	file://0584-sh-pfc-r8a7778-tidyup-MMC_D1-pin.patch \
	file://0585-drm-gp2d-suppress-debug-logs-output.patch \
	file://0586-ARM-shmobile-r8a7778-add-ICB-clock-support.patch \
	file://0587-ARM-shmobile-bockw-enable-ICB-clock.patch \
	file://0588-ARM-shmobile-r8a7778-add-IPMMU-support.patch \
	file://0589-ARM-shmobile-r8a7778-add-VPC-clock-support.patch \
	file://0590-RM-shmobile-r8a7778-add-VPC-support.patch \
	file://0591-ARM-shmobile-r8a7778-add-MERAM-clock-support.patch \
	file://0592-ARM-shmobile-r8a7778-add-MERAM-support.patch \
	file://0593-ARM-shmobile-r8a7778-add-MERAM-support.patch \
	file://0594-ARM-shmobile-r8a7778-add-ICB-MERAM-work-around.patch \
	file://0595-ARM-shmobile-bockw-invoke-ICB-MERAM-workaround.patch \
	file://0596-ARM-shmobile-r8a7778-add-VIO-clock-support.patch \
	file://0597-ARM-shmobile-r8a7778-add-VIO-support.patch \
	file://0598-ARM-shmobile-r8a7778-add-VPU-clock-support.patch \
	file://0599-ARM-shmobile-r8a7778-add-VPU-support.patch \
	file://0600-ARM-shmobile-r8a7778-add-SSB-workaround.patch \
	file://0601-ARM-shmobile-bockw-invoke-SSB-workaround.patch \
	file://0602-ARM-shmobile-r8a7778-add-a-register-region-for-an-IC.patch \
	file://0603-ARM-shmobile-r8a7778-add-PWM-clock-support.patch \
	file://0604-mach-shmobile-add-R-Car-PWM-driver.patch \
	file://0605-arm-mach-shmobile-bockw-add-platform_device-for-PWM6.patch \
	file://0606-watchdog-add-R-Car-WDT-driver.patch \
	file://0607-ARM-shmobile-r8a7778-add-WDT-support.patch \
	file://0608-workqueue-reorder-queueing-functions-so-that-_on-var.patch \
	file://0609-workqueue-make-queueing-functions-return-bool.patch \
	file://0610-workqueue-disable-irq-while-manipulating-PENDING.patch \
	file://0611-ARM-shmobile-bockw-Add-suport-mtd-info.patch \
	file://0612-r8a7778-Add-Clocks-for-SGX.patch \
	file://0613-ARM-mach-shmobile-r8a7778-Don-t-use-SCSCR_CKE1.patch \
	file://0614-ARM-shmobile-bockw-Change-MMC-Card-detect.patch \
	file://add_gp2d_drm_kbuild.patch \
	"
