IMAGE_FEATURES += "\
    tools-sdk \
    tools-debug \
    debug-tweaks \
    dev-pkgs \
"

CORE_IMAGE_EXTRA_INSTALL += "\
    net-tools \
    inetutils-ftp \
    ethtool \
    util-linux \
    mtd-utils \
    mtd-utils-jffs2 \
    dosfstools \
    lrzsz \
    gcov \
    rt-tests \
    iperf3 \
    iproute2 \
    iproute2-tc \
    perf \
    e2fsprogs \
    e2fsprogs-mke2fs \
    e2fsprogs-tune2fs \
    e2fsprogs-e2fsck \
    nvme-cli \
"
